### ISSUE TITLE
Create a simple "api editor" component in angular 2 for testing purposes

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#1]
The reason to create this API Editor component (which should be a simple <textarea/>) is to test and confirm the ability to embed such a component in other JS applications/web sites.

The editor component should have a very simple API:
- Set value
- Get value
- Fire event: onChange when the editor's value changes

It should be created in its own repository (or alternatively its own sub-directory of apiman-studio).

**Comment by kahboom** [comment]
😮 How flattering that I get the first issue! :octocat:
