### ISSUE TITLE
Project failing to compile on java!=1.8

### ISSUE THREAD

**Issue by wtrocki** [Apicurio/apicurio-studio#1010]
Not that this is an issue for me but recently needed to update my java version and I have noticed that project is failing to compile on javadoc generator (but possibly other targets will fail as well)

**Comment by wtrocki** [comment]
Created PR to clarify this: https://github.com/Apicurio/apicurio-studio/pull/1009/files

**Comment by EricWittmann** [comment]
Why did you close this?  What version of java did the build fail on?

**Comment by wtrocki** [comment]
Java 11.. So README.md specifies that it works with java 1.8+
I needed to use java 11 LTS for other projects and switched and maven started to fail on various steps like javadoc target. I have closed an issue as it was just my confusion that README do not clearly specify version where in fact it is there as prerequisites - I just did not seen it initially.

**Comment by wtrocki** [comment]
Sadly I lost error log. Using latest version of Java on mac will definietly cause build to fail, but I think that is ok.

**Comment by EricWittmann** [comment]
Ah yes - it probably fails on the javadoc step.  The java 11 javadoc step is very strict.  We should open an issue about that - I'd certainly like the build to work using jdk11.
