### ISSUE TITLE
[Question] Contribution guide to the Apicurio studio

### ISSUE THREAD

**Issue by wtrocki** [Apicurio/apicurio-studio#1012]
I'm trying to figure out how to efficiently work with the js layer without the constant clean rebuild of the entire project. It looks like when using quickstart. 

Readme recommends steps like unzipping some target files etc. everytime. Additionally, when doing it database is lost. I have tried to use plugin like vscode-sever-connector but with no success. Is there any way to run the project in live edit mode (for UI especially)

https://github.com/redhat-developer/vscode-server-connector

**Comment by wtrocki** [comment]
I just have noticed that studio is using quarkus so it might be better to document how to run it using quarkus dev mode?

**Comment by EricWittmann** [comment]
I think this is what you're looking for:  https://apicurio-studio.readme.io/docs/setting-up-a-development-environment

Which readme were you looking at?  I should update it to point to the article above...

Also note - Apicurio Studio does not yet run on Quarkus.  The goal is to migrate to that, but right now we run on Wildfly or Thorntail.

**Comment by EricWittmann** [comment]
Also sorry for the lateness of the reply.  I fully took off the holiday this year. :)

**Comment by wtrocki** [comment]
Ah.. I forgot to check website! My bad. I was using repository readme

**Comment by wtrocki** [comment]
Added link to README
