### ISSUE TITLE
Preview throws "internal server error" without further explanation

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1036]
I fixed my OpenAPI spec to only use schema references in the path.
It finally [loads in ReDoc as designed](https://redocly.github.io/redoc/?url=http://www.projectcastle.io/demo.yaml), however doesn't load in apicurio.

On closer inspection, the call to load the YAML fails:
https://studio.apicur.io/download?type=api&format=json&id=20598

with "Internal Server Error" (but still HTTP code 200).

Wonder what I missed?

**Comment by EricWittmann** [comment]
HTTP code 200 with an internal error body?  That's not good.  

I confirmed that the API Design itself is fine.  I imported it into Apicurio Studio and then viewed the documentation.  You can see it here:  

https://studio-ws.apicur.io/sharing/0eac4037-57a2-4107-b8ed-fd38f6ded2c7

So the problem must be something else.  Would you be willing to share the API design with me (e.g. email me a collaborator link)?  

Another thing to try is to Clone the API Design and see if the cloned one exhibits the same problem(s).

**Comment by iudex-** [comment]
I just ran into the same issue.
Not just the preview fails, also the yaml and json exports break.
![image](https://user-images.githubusercontent.com/56843/72528967-92e00600-386c-11ea-8e86-50e6073fb139.png)

**Step to reproduce:**
- In any existing or newly created project change anything related to INHERITANCE on any datatype
- done, the API can't be exported or previewed anymore
![image](https://user-images.githubusercontent.com/56843/72529168-ff5b0500-386c-11ea-9220-753e634852c6.png)

**Comment by EricWittmann** [comment]
Thanks for reporting this and narrowing it down.  I'll have a look at this asap.

**Comment by EricWittmann** [comment]
Amazingly enough this was a deployment config error!  Try now and let me know if things work.

**Comment by EricWittmann** [comment]
@iudex- and @Stwissel ^^^^

**Comment by iudex-** [comment]
It does, thank you very much! :)

**Comment by Stwissel** [comment]
Works like a charm. I owe you 🍺!

**Comment by Stwissel** [comment]
Problem reappeared. Config error resurfaced?
