### ISSUE TITLE
store to git repo on online version

### ISSUE THREAD

**Issue by dario-frongillo** [Apicurio/apicurio-studio#1043]
Hi,
i m using apicurio online version and i not find the feature that allow to save with a commit the changes done on a specification stored in a git repo.
can y help me ?

**Comment by EricWittmann** [comment]
There is an action labeled "Publish" that will do what you want:

![image](https://user-images.githubusercontent.com/1890703/72816665-87a72480-3c36-11ea-8229-2f837bcc1136.png)

This feature will work for GitHub, GitLab, and Bitbucket online services.  You'll need to link your Apicurio Studio account to your e.g. GitHub account first.  That can be done in Settings->Linked Accounts.

**Comment by EricWittmann** [comment]
We don't currently have a feature where your API design is automatically "linked" in any way to a resource in git.  There is an issue for that in the backlog, but it has not been implemented.
