### ISSUE TITLE
How to model ODATA URLs?

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1066]
This might be a question better suited for an OpenAPI forum, but it might be relevant here.

From the ODATA website
> An open protocol to allow the creation and consumption of queryable and interoperable RESTful APIs in a simple and standard way.

The [URLs they build](https://www.odata.org/getting-started/basic-tutorial/) are, lets say, uncommon (Where `serviceRoot` would be something like `https://yourserver.com/api` :

- `GET serviceRoot/People`
- `GET serviceRoot/People('russellwhyte')`
- `GET serviceRoot/Airports('KSFO')/Name`
- `GET serviceRoot/People?$filter=Emails/any(s:endswith(s, 'contoso.com'))`

Catching `$filter` seems easy, it's just a query parameter. I wonder how I should model the difference between `People` ( = List of resource type people) and `People('russellwhyte')` ( = one resource of type person)

Would it do something like this:

- `/api/{resourcetype}`
- `/api/{resoucetype}('{resourceid}')`
- `/api/{resoucetype}('{resourceid}')/{propertyName}`

Insights appreciated

**Comment by EricWittmann** [comment]
There is actually an Oasis spec around this topic.  The spec seems stale, but it might useful anyway. You can find it here:

http://docs.oasis-open.org/odata/odata-openapi/v1.0/cnprd01/odata-openapi-v1.0-cnprd01.html

I don't have any specific insights or opinions on the matter myself, because I don't have much experience with OData - more of just an awareness of it. :)

**Comment by Stwissel** [comment]
The main challenge is how path are defined. Usually we have slashes that separate list from individual records. A list would be `/api/{resourcetype}` e.g. `/api/animals` - works everywhere including oDATA. An individual item would be `/api/{resourcetype}/{id}` e.g. `/api/animals/lion`

However oDATA would use `/api/animal('lion')` which would be `/api/{resourcetype}('{id}')` The OpenAPI (or at least the apicur.io) path matchers can't deal with that.

`/api/{resourcetype}` matches for both `/api/animals` and `/api/animal('lion')`- but these two operation have very different return value structures

Or do I miss something?

**Comment by Stwissel** [comment]
The [document describes single queries](https://docs.oasis-open.org/odata/odata-openapi/v1.0/cn01/odata-openapi-v1.0-cn01.html#sec_PathsforSingleEntities) and in example 22 suggests keys can be segments too and don't need to be in round brackets. Interesting question: do Odata consumers (Excel springs to mind) honour that. -> a question beyond this ticket.

**Comment by EricWittmann** [comment]
It's very likely that the path matching logic can't handle it but that's perfectly valid.  I can't find much on the requirements of the format of a path template in the OpenAPI spec.  So I suspect we are much more strict that we should be.
