### ISSUE TITLE
Separate concerns and implement the Language Server Protocol

### ISSUE THREAD

**Issue by mickaelistria** [Apicurio/apicurio-studio#108]
Just like all code edition tools, it's important to separate the pure "Front-End" with the "code assist" features to allow reusing those code-assist features in other editors/IDEs.
Please make the code-assist part implement the Language Server Protocol (https://github.com/Microsoft/language-server-protocol ) so it will be very easy to integrate with many clients: https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations

**Comment by EricWittmann** [comment]
Apicurio is not a code editor, it is a form editor.  So, for example, right now there are no text based auto-complete features and Apicurio does not perform updates on the **text** of the source file.  Instead, structural changes are made to the data model.

Based on my reading of the language server protocol here:

https://microsoft.github.io/language-server-protocol/overview

I think the approach that Apicurio takes is fundamentally incompatible.

Feel free to re-open if you disagree and I'm reading this all wrong. :)
