### ISSUE TITLE
Deprecated endpoint not supported

### ISSUE THREAD

**Issue by aoudiamoncef** [Apicurio/apicurio-studio#1104]
Hi, 
It could be useful to add support for paths deprecation from the UI which is supported on OpenAPI 3 spec.

![image](https://user-images.githubusercontent.com/22281426/78300921-9b291280-7538-11ea-997d-6af2e90a7898.png)

Thanks

**Comment by EricWittmann** [comment]
That should be easy enough to support in the editor.  Do you know if ReDoc already supports it?

Also as a side note - is that Swagger UI that  you're showing in the screenshot?  And if so - do they really spell **deprecated** that way?  lol

**Comment by aoudiamoncef** [comment]
Hi @EricWittmann,
Yes, ReDoc already handle it.

The screenshit comes from [OpenApi Viewer ](https://github.com/mrin9/OpenAPI-Viewer/blob/master/README.md), don't panic, there is some spelling mistakes 😅 in the hole project.
