### ISSUE TITLE
Redirect uri issue when app port is changed

### ISSUE THREAD

**Issue by shivinm** [Apicurio/apicurio-studio#1109]
Trying to run API Curio locally on a port different than the defaults 8080/8443 as there is a service already running on those ports on a different webapp server. 

These lines were modified in standalone-apicurio.xml.
```     
         <socket-binding name="http" port="${jboss.http.port:5000}"/>
         <socket-binding name="https" port="${jboss.https.port:5001}"/>
```

Command to start the app:
```
./distro/quickstart/target/apicurio-studio-*-SNAPSHOT/bin/standalone.sh -c standalone-apicurio.xml
```

When I point the browser to `http://localhost:5000`, I get an error: 
![Screen Shot 2020-04-08 at 11 56 13 AM](https://user-images.githubusercontent.com/5727055/78817543-88776900-7990-11ea-972b-a7f46cf9a8cc.png)

This is the GET request being made to `https://studio-auth.apicur.io`
```
https://studio-auth.apicur.io/auth/realms/apicurio-local/protocol/openid-connect/auth?response_type=code&client_id=apicurio-studio&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fstudio%2F&state=34f989b6-1437-4f47-999e-baa553f9469c&login=true&scope=openid
```

![Screen Shot 2020-04-08 at 11 56 20 AM](https://user-images.githubusercontent.com/5727055/78817560-90370d80-7990-11ea-81fb-bcb51c45600a.png)

Response:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="login-pf">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">

            <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <title>Log in to apicurio-local</title>
    <link rel="icon" href="/auth/resources/4.1.0.final/login/apicurio/img/favicon.ico" />
            <link href="/auth/resources/4.1.0.final/login/apicurio/node_modules/patternfly/dist/css/patternfly.css" rel="stylesheet" />
            <link href="/auth/resources/4.1.0.final/login/apicurio/node_modules/patternfly/dist/css/patternfly-additions.css" rel="stylesheet" />
            <link href="/auth/resources/4.1.0.final/login/apicurio/lib/zocial/zocial.css" rel="stylesheet" />
            <link href="/auth/resources/4.1.0.final/login/apicurio/css/login.css" rel="stylesheet" />
</head>

<body class="">
  <div class="login-pf-page">
    <div id="kc-header" class="login-pf-page-header">
      <div id="kc-header-wrapper" class="">apicurio-local</div>
    </div>
    <div class="card-pf ">
      <header class="login-pf-header">
        <h1 id="kc-page-title">        We&#39;re sorry...
</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">


        <div id="kc-error-message">
            <p class="instruction">Invalid parameter: redirect_uri</p>
                <p><a id="backToApplication" href="https://localhost:8443/studio">&laquo; Back to Application</a></p>
        </div>

        </div>
      </div>

    </div>
  </div>
</body>
</html>

```
-- 
Any idea why this is erroring and is there a workaround for it? 
It says invalid redirect_uri for "https://localhost:8443/studio" however that's not the redirect_uri that was sent in the GET request, and the secure url has been configured at "https://localhost:5001/studio"

**Comment by EricWittmann** [comment]
Because the Apicurio Studio quickstart is using a cloud version of Keycloak for authentication, you can't use any arbitrary port or else the auth dance will fail.  Here are some ALT ports you can use and the auth server will allow it:

* 8080
* 8888
* 8443
* 7443
* 8180

If those ports won't work, let me know and I can add to that list.

Alternatively you can install your own Keycloak server and then do whatever you want.  If you're installing for something other than evaluation, that's obviously my suggestion.  Don't rely on my cloud auth server!  :)  It's only meant for dev/eval systems.
