### ISSUE TITLE
Migrate microservice impls from Thorntail to Quarkus

### ISSUE THREAD

**Issue by carlesarnal** [Apicurio/apicurio-studio#1110]
Add quarkus as an available platform to deploy the apicurio-studio application.

**Comment by EricWittmann** [comment]
@carlesarnal Once everything is working on Quarkus we can deprecate the Thorntail deployments and eventually delete them.  But we'll want to replace the docker images with the Quarkus version ASAP.  Note that the cloud version of Apicurio Studio running here [ https://studio.apicur.io/ ] is powered by the Thorntail based docker images.  So once we update the docker images we should know pretty quickly if anything goes wrong. :) :)

**Comment by carlesarnal** [comment]
@EricWittmann at this moment, we are able to created docker images based on the Quarkus deployments (and even run them with `docker-compose`), maybe we can close this.
