### ISSUE TITLE
unable to open the editor because a web socket request is hanging

### ISSUE THREAD

**Issue by hosun-g** [Apicurio/apicurio-studio#1116]
In Chrome and Firefox, I am unable to open the API editor (https://studio.apicur.io/apis/22450/editor) and I tried a few times today but the issue is persistent. 

I believe that the web socket request is hanging.

`wss://studio-ws.apicur.io/designs/22450`

The UI shows the loading icon for a while and then "Lost Connection" error appears.

<img width="1254" alt="Screen Shot 2020-04-15 at 7 53 46 PM" src="https://user-images.githubusercontent.com/56849276/79409630-45e6fb00-7f53-11ea-9fa6-1bfafd3d2a3d.png">

<img width="674" alt="Screen Shot 2020-04-15 at 8 01 56 PM" src="https://user-images.githubusercontent.com/56849276/79409938-f9e88600-7f53-11ea-8f36-d3cb455f7855.png">

Can you please let help me on this?

Thank you.

**Comment by AraConnect** [comment]
I have also the same problem.

**Comment by oliosien** [comment]
Me too.

**Comment by AnupamDeb1807** [comment]
I am also facing same issue for last couple of hours, any help is appreciated?

Thanks

**Comment by hosun-g** [comment]
Now, it works fine for me.  The web socket connection does not hang and I can access the editor.

**Comment by EricWittmann** [comment]
Hey everyone - thanks for reporting this problem.  Sorry for the delay in response.  Apparently whatever was causing the issue has resolved itself.  I'll look into the logs to see if I can find insight into what happened.

Also please remember that [https://studio.apicur.io/](https://studio.apicur.io/) is intended to be an evaluation version of Apicurio Studio, and is not suitable for critical production workloads.  You are more than welcome to continue using it in whatever capacity you choose, but just be aware that there aren't any SLAs or anything like that.  :)

**Comment by hosun-g** [comment]
@EricWittmann  Thank you for your help and clarification about studio.apicur.io.  👍
