### ISSUE TITLE
Docker Compose problem with new Quarkus based images

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#1130]

**Comment by EricWittmann** [comment]
@carlesarnal can you please explain here what the problem is with docker-compose?

**Comment by carlesarnal** [comment]
Hi @EricWittmann, when the `exec `command is executed the default values defined in the Dockerfile are taking precedence. Instead, the command should use the env vars defined with` docker-compose` (Supposedly if the environment variables exist then they take precedence over the Dockerfile defined ones, more info [here](https://docs.docker.com/compose/environment-variables/)  ). If I run the docker image with `docker run` and add the env vars with -e, everything works fine.

Also, if I execute `docker-compose config` with the docker-compose.yml and the .env file everything looks good.

Let me know if you need further clarification.

**Comment by carlesarnal** [comment]
Ok, with the last PR I've opened the problem with docker-compose and quarkus should be solved [1132](https://github.com/Apicurio/apicurio-studio/pull/1132)
