### ISSUE TITLE
Apicur.io sizing?

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1141]
I'm looking at deploying Apicur.io onto our own, behind a firewall, infrastructure (potentially OpenShift). My infra guys want to know about sizing. What should I tell them?

I have about 10 concurrent users and large APIs (> 5000 lines).

What sizing does the public site use?

**Comment by EricWittmann** [comment]
We haven't really done much analysis for sizing requirements, but what you've described obviously is quite small.  The size of the APIs shouldn't really matter much from a server-sizing POV, though it might slow down the editor (in the browser).  

The public site is running in an OpenShift cluster using the default sizing values found in this template:  https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-standalone-template.yml

If you scroll to the bottom you will find a bunch of parameters with default values for the sizes of the various pods.  That's the best info I have for you.

**Comment by Stwissel** [comment]
Awesome. Thank you
