### ISSUE TITLE
Helm installation

### ISSUE THREAD

**Issue by tomassatka** [Apicurio/apicurio-studio#1190]
Hi Team

Would you accept PR if i write helm chart installation as a new distro option?

**Comment by EricWittmann** [comment]
That's a really good question actually.  I think having a kubernetes operator is high on our wish-list, although I think our plan was to write one in golang.  That said, I don't know when we will be able to get to that work (a golang operator) - so having a Helm based one as an interim solution for installing on Kubernetes I think would be fantastic.

So yeah ... short answer is "for sure!"  :)

**Comment by tomassatka** [comment]
With pleasure. We install all our applications by helm & helmfile into openshift but since it is k8s based it requires only small adaptation from ingress -> routes and so on. So works well for us at the end. Will try to create PR soon.

**Comment by tomassatka** [comment]
thanks for merging
