### ISSUE TITLE
Feature request: Schema format

### ISSUE THREAD

**Issue by Herrick19** [Apicurio/apicurio-studio#1193]
Hi,

It would be nice if you could support all of the OAS 3 imported types from JSON Schema. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object

- title
- multipleOf
- maximum
- exclusiveMaximum
- minimum
- exclusiveMinimum
- maxLength
- minLength
- pattern
- maxItems
- minItems
- uniqueItems
- maxProperties
- minProperties
- required
- enum

Also the nullable, readOnly, writeOnly

Ideally, the valid choices would be related to the data type.

For example for strings:
- maxLength
- minLength
- pattern

For integers and float:
- multipleOf
- maximum
- exclusiveMaximum
- minimum
- exclusiveMinimum

For arrays:
- maxItems
- minItems
- uniqueItems

For objects:
- maxProperties
- minProperties

Support for this is very rare and would make apicurio the most complete Editor beside commercial products

Thanks in advance for considering

**Comment by vvilerio** [comment]
Hi,
I'm starting to work on , today :)

**Comment by vvilerio** [comment]
![minmax](https://user-images.githubusercontent.com/78545082/123960642-d3bfd200-d9af-11eb-930a-b2aba4190cb2.png)

**Comment by pedy711** [comment]
could you please give me an example of the pattern for an enum?

I want to have id and displayed name separately. Would that be possible with a pattern?

Ex: 
`enum {
    TEST_1: "fast",
    TEST_2: "medium"
    TEST_3: "slow"
}`

**Comment by vvilerio** [comment]
@see https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object

pattern (This string SHOULD be a valid regular expression, according to the Ecma-262 Edition 5.1 regular expression dialect)

**Comment by pedy711** [comment]
@vvilerio thanks for your comment, but I am still unsure if what I want to achieve is doable in OpenAPI Specification. I would be thankful if you could help me out. 

I want to build the following that contains id and label for enums.

Ex:
enum { TEST_1: "fast", TEST_2: "medium" TEST_3: "slow" }

**Comment by EricWittmann** [comment]
I think enough of this feature request has been implemented that we can close it.  Thanks @vvilerio !  

As for @pedy711 - enums in OpenAPI are just a list of possible values for a property.  If you wanted to model something with multiple values, you'll need to find another way.
