### ISSUE TITLE
Does APICurio allow you to export OpenAPI specification to a repository?

### ISSUE THREAD

**Issue by pkaleta** [Apicurio/apicurio-studio#1202]
I'd like to be able to have a respository containing OpenAPI specification for my APICurio-designed APIs. I'd like such repository to stay in sync with what is visible in APICurio when designing APIs. Is this possible?

**Comment by EricWittmann** [comment]
We don't yet have automatic sync.  We have the ability to publish content to GitHub, GitLab, or Bitbucket.  But the user must manually run the action.  There is an API for the publish action, so you could automate it.  But I'm not sure what the trigger might be.

**Comment by EricWittmann** [comment]
All of our documentation is really focused on installation and configuration use-cases, not really user documentation.  That's obviously not ideal, but it is the unfortunate reality.  However, I can explain it quickly here.  

First you need to link your e.g. GitHub account to your Apicurio Studio account.  You can do that from the Settings->Linked Accounts page:

![image](https://user-images.githubusercontent.com/1890703/86140706-232ea200-babf-11ea-9728-dd9c48309772.png)

Once your account is linked, you can use the "Publish" action from the API details page:

![image](https://user-images.githubusercontent.com/1890703/86140802-435e6100-babf-11ea-90ab-461edd477247.png)
![image](https://user-images.githubusercontent.com/1890703/86140892-5f620280-babf-11ea-865d-ab2ecbf7917d.png)

That's pretty much it!

If you are actually asking about how to configure your own Apicurio Studio local installation to support this feature, we *do* have [documentation](https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio) about that.

**Comment by pkaleta** [comment]
Thanks so much @EricWittmann!

I'm getting this error when trying to link my GH, is this something on my end?

<img width="569" alt="Screen Shot 2020-07-08 at 2 40 31 PM" src="https://user-images.githubusercontent.com/51424/86920403-0bdc5e00-c12a-11ea-87b0-f8ef54c8a1fe.png">

**Comment by EricWittmann** [comment]
Hey @pkaleta sorry for the delay - I've been on vacation.  :) 

So are you getting this error on the demo/cloud version of Apicurio Studio?  The one at https://studio.apicur.io ?  If yes, then I'm guessing there is something weird about your GitHub account that isn't be handled properly.  If you're using a local installation of Apicurio Studio then you have a configuration problem.  Can you clarify the situation?

**Comment by pkaleta** [comment]
I'm using local installation. Problem is prob on my end, so I'll close this for now and reopen in case I find out that's not the case. Thank you very much for screenshots and guide!

**Comment by pkaleta** [comment]
one last q, is this version of ApiCurio fresh enough to get that working?

<img width="615" alt="Screen Shot 2020-08-13 at 1 35 09 AM" src="https://user-images.githubusercontent.com/51424/90078459-4a56d100-dd05-11ea-803b-6d194916fe68.png">

**Comment by EricWittmann** [comment]
Yep - that version should be fine!  There is documentation available regarding how to configure a local installation of Apicurio and Keycloak to get this working:

https://www.apicur.io/studio/docs/setting-up-keycloak-for-use-with-apicurio

If you're running Apicurio locally you should really also be running a local installation of Keycloak for authentication.  The link above explains how to do that.

**Comment by pkaleta** [comment]
thanks again
