### ISSUE TITLE
the current oauth security template for swagger is missing a parameter

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-studio#127]
this might be related to the way swagger-ui is implemented but to complete the Authorization Code Flow a parameter needs to be passed, which is the oauth2RedirectUrl at the moment not present in the standard fields.

**Comment by EricWittmann** [comment]
Do you have a concrete example of this you can share?  What you're describing is not present in version 2 of the OpenAPI spec.

**Comment by lucamaf** [comment]
if I add the Oauth configuration I'm not presented with the RedirectURI field. I checked the the specs as well and there is no mention, which is weird. I guess the concept is since you are going to initiate the flow from the server hosting the swagger-ui that will act as (implicit) redirect url

**Comment by EricWittmann** [comment]
I'm guessing this feature is an extension to the spec.  Is there a swagger editor of some sort that allows you to add a redirect url?  If so (or I guess regardless of how you created your swagger/openapi doc), can you post a sample of the resulting YAML?

**Comment by EricWittmann** [comment]
Any update on this?  Can you provide an example document that has this field?

**Comment by EricWittmann** [comment]
@lucamaf ^^^^^^^^^^^  :)
