### ISSUE TITLE
Cant create new API: Path mandatory?

### ISSUE THREAD

**Issue by kasriniv** [Apicurio/apicurio-studio#128]
Hello
I am trying to create a new API. The path value seems to be required not optional...I understood that when creating a new API, one does not need to provide the openapi.json and path to it..
Here is a screenshot
<img width="1421" alt="screen shot 2017-06-21 at 10 30 32 am" src="https://user-images.githubusercontent.com/10718966/27389567-b66f03b2-566c-11e7-9953-edad46b60d9e.png">

**Comment by EricWittmann** [comment]
For anyone seeing this in the future, the path to the resource is required when creating an API so that we know where to specifically store the content.  Perhaps we could default to /openapi.json but currently the user is simply required to provide the location. :)
