### ISSUE TITLE
JDBC_PARAMS: "useSSL=false" is required in docker-compose.keycloak.yml to prevent error

### ISSUE THREAD

**Issue by yohanesgultom** [Apicurio/apicurio-studio#1343]
When running docker-compose distro in a server using IP address as hostname, `JDBC_PARAMS: "useSSL=false"` is required in `docker-compose.keycloak.yml` to avoid exception below in Keycloak container:

```
javax.resource.ResourceException: IJ031084: Unable to create connection Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```

Is this expected? I was a bit confused because it's not mentioned anywhere in the doc

**Comment by EricWittmann** [comment]
I don't have any insight into this, unfortunately.  @carlesarnal , @famartinrh , @jsenko any thoughts on this?

For SSL errors the usual problem is invalid certs  (e.g. self-signed).  But this error you've included is something I've not seen before.  A quick Google search reveals this:

https://stackoverflow.com/questions/38205947/sslhandshakeexception-no-appropriate-protocol

**Comment by yohanesgultom** [comment]
Thanks for the response. I didn't use ssl at all. I used `distro/docker-compose` as it is inside a VPS

**Comment by carlesarnal** [comment]
Hello @yohanesgultom, first of all, sorry for the late response. This is not intended since as it's stated in the docs this distro is meant for development purposes and comes without ssl support.  Let's see if we can see what's happening. Could you please share the set of commands that you've used in order to deploy the application? Have you modified the `.env` after the execution of those commands? Thanks.

**Comment by ravredd** [comment]
Found same issue.  adding ```JDBC_PARAMS: "useSSL=false"``` to the environment section for jboss-keyclock service in docker-compose.keycloak.yml file is a workaround for this.  If the docker-compose setup/ran is not meant for production and comes without ssl support than this should be added to the yaml file to work.

**Comment by EricWittmann** [comment]
@ravredd Any interest in submitting a PR for that change to `docker-compose.keycloak.yml`? :)
