### ISSUE TITLE
API Editor: Clicking "As JSON" in causes unsaved editing to be lost. 

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#136]
To reproduce:

* Enter editor mode for an entity
* Add some new content, but do not save
* Click "As JSON" and the manually entered content will disappear
* Returning to "As YAML" and the content does not reappear

The state can be retrieved by repeated CTRL+Z thankfully.

**Comment by EricWittmann** [comment]
Thanks for the report!
