### ISSUE TITLE
Error Instatiating Template

### ISSUE THREAD

**Issue by raffamendes** [Apicurio/apicurio-studio#1364]
I got this error when trying to create the template on a Openshift 4.6.1 on AWS

![image](https://user-images.githubusercontent.com/54948088/103575096-e4cfd080-4eaf-11eb-92be-afe48297a63a.png)

I solved by changing the first line from 
```yaml
apiVersion: v1
```
to 
```yaml
apiVersion: template.openshift.io/v1
```

I'll create a PR addressing this issue if it's ok.

**Comment by EricWittmann** [comment]
Not deprecated, no - just broken apart from the main one.
