### ISSUE TITLE
API Editor: When mandatory /info entries omitted clicking "Go To Problem" on prompt results in page blank

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#137]
![image](https://user-images.githubusercontent.com/423513/28126744-4d92e40a-6722-11e7-8237-2513400ff8af.png)
![image](https://user-images.githubusercontent.com/423513/28126776-6cb81760-6722-11e7-9021-0ec88599c87f.png)

No console entries are created for this action.

**Comment by EricWittmann** [comment]
This has been fixed in some long forgotten refactoring of how user selection works. :)
