### ISSUE TITLE
[docker-compose] distro not working properly ?

### ISSUE THREAD

**Issue by hanyEthan** [Apicurio/apicurio-studio#1386]
Environment - Windows 10 pro / Docker for windows v20.10.2 / Google Chrome 87.0.4280.141
ApiCurio release - latest on Master branch (on the time of this comment)
Issue description:

we have been trying to test ApiCurio on our local Docker compose to evaluate it, as we have been hearing good feedback about it so far, but we are having difficult time setting it up using its Docker Compose distro ...
1. [docker-compose distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose) is not running correctly due to an issue connecting to mysql without SSL.
2. [quarkus docker-compose](https://github.com/Apicurio/apicurio-studio/tree/master/distro/quarkus/docker-compose) has been installed correctly
   - but not initially, as we had to replace this string in the .env file in order for Apicurio to integrate with the auth service correctly ...
      - `APICURIO_KC_AUTH_URL=http://192.168.1.40:8090/auth/realms/apicurio` replaced with `APICURIO_KC_AUTH_URL=http://192.168.1.40:8090/auth`
   - and all 3 portals opened correctly after that (keycloack, microcks, & Apicurio)
   - but Apicurio portal couldn't work with its api due to CORS issue
![Screenshot 2021-01-24 172036](https://user-images.githubusercontent.com/24544821/105634818-9ab38c80-5e68-11eb-91d3-cce202627a40.png)

are we missing any configurations ?

Thank you.

**Comment by carlesarnal** [comment]
Hi @hanyEthan,

Regarding the [docker-compose-distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose) this is the distro that you should use right now and a potential workaround for what you're describing can be found [here](https://github.com/Apicurio/apicurio-studio/issues/1343).

Regarding the [quarkus-compose-distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/quarkus/docker-compose), the APICURIO_KC_AUTH_URL value in the `.env` is correct since that's the value that the quarkus image expects. That said since that distro isn't part of any release the images aren't publicly available at this moment and therefore this distro should not be used. If you still want to try the quarkus distro I'll be more than happy to give you some instructions on how to get it up & running (basically you'll need to build the images locally).

**Comment by hanyEthan** [comment]
Thank you so much @carlesarnal for your response.
- i'll re-test the [recommended distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose) today with the suggested workaround, and i'll let you know.
- based on the results, we will see if we need to try the [quarkus-compose-distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/quarkus/docker-compose) or not.

thank you again.

**Comment by hanyEthan** [comment]
Hi @carlesarnal,

- i tried the suggested [workaround](https://github.com/Apicurio/apicurio-studio/issues/1343), and it worked (thank you).
- but it seems that i'm facing another issue with the auth service configuration, preventing both microcks and apicurio from starting.
![image](https://user-images.githubusercontent.com/24544821/105722223-1deae600-5f2e-11eb-8bbd-e719e9893514.png)
![image](https://user-images.githubusercontent.com/24544821/105722265-280ce480-5f2e-11eb-8bae-f5de06ddd146.png)
![image](https://user-images.githubusercontent.com/24544821/105722315-33601000-5f2e-11eb-8797-1e844aa91cc1.png)
![image](https://user-images.githubusercontent.com/24544821/105722475-5f7b9100-5f2e-11eb-96d7-87201035205b.png)

- did we miss something else ?

thank you for your support.

**Comment by carlesarnal** [comment]
Hi @hanyEthan, afaik, no, you aren't missing anything. Could you please share the server log?

**Comment by hanyEthan** [comment]
hi @carlesarnal, thank you for replying,

- we have restarted all configurations, and retried again, this time, the ApiCurio system error disappeared (_we didn't know why_),
- but the microcks is still having the same auth issue.
- these are the microcks realm config, and logs for trying to open it, and then, trying to integrate with it [configs & logs.zip](https://github.com/Apicurio/apicurio-studio/files/5872551/configs.logs.zip).

thank you again,

**Comment by carlesarnal** [comment]
hi @hanyEthan, thanks, I'll take a look and try to reproduce this issue.

**Comment by carlesarnal** [comment]
Hi @hanyEthan, I'm glad you raised this cause it led me to found a bug in the `docker-compose` distro. We had a problem with the microcks realm template, causing the redirect URI to be invalid.  I've linked a PR that should fix the issue.

Thanks!

**Comment by hanyEthan** [comment]
thank you @carlesarnal, the installation and auth are working properly now.
we will continue our evaluation, and will report any blockers.
