### ISSUE TITLE
Connect Apicurio with PostgreSQL

### ISSUE THREAD

**Issue by MoMueSe** [Apicurio/apicurio-studio#1392]
We tried to connect apicurio to postgres following the documentation.
On starting the standalone-sh with standalone.sh -c standalone-apicurio.xml -b 0.0.0.0 -Djboss.socket.binding.port-offset=110 we're getting the following error.

![Apicurio-Error](https://user-images.githubusercontent.com/78088725/105998165-a4c5cd00-60ac-11eb-9a2a-aa4ff78a3234.png)

The standalone-apicurio.xml looks like this
[standalone-apicurio.zip](https://github.com/Apicurio/apicurio-studio/files/5880549/standalone-apicurio.zip)

Spezifications: 
PostgreSql 12
Open-JDK 8

We use the ddl to initialized the database

**Comment by MoSeMue** [comment]
We found the issue. 
The old process was runing in the background.

**Comment by EricWittmann** [comment]
Glad you found the issue!
