### ISSUE TITLE
Integration between [ApiCurio] and [Microcks] is having an issue ...

### ISSUE THREAD

**Issue by hanyEthan** [Apicurio/apicurio-studio#1401]
hello @carlesarnal, and everyone,

- we are having another issue with the [[Docker Compose] distro](https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose), after you have solved the previous issue we encountered #1386.
- when we try to integrate between [ApiCurio] and [Microcks], we get this issue ...
![image](https://user-images.githubusercontent.com/24544821/106448973-24c4ac00-648c-11eb-8828-9a9e0998f419.png)
![image](https://user-images.githubusercontent.com/24544821/106449069-4160e400-648c-11eb-9a66-fa33cb5da4c6.png)

is it still related to [KeyCloak] configurations ?

thank you.

**Comment by carlesarnal** [comment]
Hello @hanyEthan, this will probably be a problem in the microcks keycloak config, let me try to reproduce it.

**Comment by carlesarnal** [comment]
Hi @hanyEthan, sorry for the delay. I've submitted a new PR #1416 fixing this issue. It was a problem with the microcks realm config.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-studio/pull/1416
