### ISSUE TITLE
Need more info in README regarding compatible versions of Java

### ISSUE THREAD

**Issue by jeffory-orrok** [Apicurio/apicurio-studio#1404]
I tried to use OpenJDK 15 which results in a NoClassDefFoundError within keycloak.  Limited [research](https://stackoverflow.com/questions/61932188/keycloak-server-caused-by-java-lang-classnotfoundexception-java-security-acl-g) into the problem suggests that it has to do with java.security.acl.Group being deprecated and removed in more recent versions of Java.  **It would be nice to replace 8+ in the README file with the correct range of Java versions that will work out of the box.**

[apicurio_NoClassDefFoundError.txt](https://github.com/Apicurio/apicurio-studio/files/5926840/apicurio_NoClassDefFoundError.txt)

**Comment by jeffory-orrok** [comment]
JDK 11 seems to work ok

**Comment by EricWittmann** [comment]
https://github.com/Apicurio/apicurio-studio/commit/3b872b194429843ec72ea6c176412b67904fd66f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
