### ISSUE TITLE
Typo in hub_mysql5.ddl

### ISSUE THREAD

**Issue by mecseid** [Apicurio/apicurio-studio#1408]
I think there is a bug in the mysql initialization file:
https://github.com/Apicurio/apicurio-studio/blob/f9778094b318d2918be42b4a10862dc924e41b4a/back-end/hub-core/src/main/resources/io/apicurio/hub/core/storage/jdbc/hub_mysql5.ddl#L15

The column with name `modifed_on` should be `modified_on`.
As I see it comes with commit https://github.com/Apicurio/apicurio-studio/commit/72a2c63256869384fb4fe410084296537dc64d94

**Comment by EricWittmann** [comment]
Thank you!  https://github.com/Apicurio/apicurio-studio/commit/9b6ed2a142eee9c7bd50fc2446d17c81cbec669c
