### ISSUE TITLE
Api Editor: Add ability to duplicate elements (definition, paths, etc)

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#141]
It would be good to be able to make a duplicate (with different name) for elements such as definitions and paths. Quite often you can use one as a basis for the next thing rather than starting from scratch each time.

For example, my `clients` element is quite similar to my `apis` element and just requires some changes to descriptions, references, etc.

**Comment by EricWittmann** [comment]
Yeah this is definitely on my list.  So much so that I'm shocked I didn't have an issue already created for it!

In any case, it's great that we have one now.  Totally agree that a "clone" operation is needed for paths and definitions!
