### ISSUE TITLE
Mysqld error on docker-compose execution

### ISSUE THREAD

**Issue by jonathanvila** [Apicurio/apicurio-studio#1415]
I try to execute "apicurio-studio" from the docker-compose version ( bc I want to use Microcks ) and I see error on jboss-keycloak-mysql not allowing to start the db for keycloak, and at the end the script finishes with an error bc it can not find the db.

Steps on apicurio-studio/distro/docker-compose :
$ ./setup.sh  192.168.1.139 mysql
$ ./start-mysql-environment.sh

Environment : 
SO : Fedora 33

09:12:54 ❯ docker version
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.15.1
 Git commit:        4484c46
 Built:             Fri Oct  2 19:31:30 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.1
  Git commit:       4484c46
  Built:            Fri Oct  2 00:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff

09:12:57 ❯ docker-compose version
docker-compose version 1.27.4, build unknown
docker-py version: 4.3.1
CPython version: 3.9.1
OpenSSL version: OpenSSL 1.1.1i FIPS  8 Dec 2020

LOG
[apicurio-run.log](https://github.com/Apicurio/apicurio-studio/files/5987058/apicurio-run.log)

**Comment by carlesarnal** [comment]
Hi @jonathanvila, I've tested it and it's working for me with a similar environment. Are you using the version from master? I'm going to upgrade my environment to see if I can reproduce it (my docker-compose version slightly differ from yours).

**Comment by jonathanvila** [comment]
Hi @carlesarnal yes I'm using master branch from apicurio-studio.

**Comment by jonathanvila** [comment]
Using Carles branch with KC - Postgresql has worked perfectly :) 
https://github.com/carlesarnal/apicurio-studio/tree/expand-docker-compose-db-choice-keycloak

**Comment by carlesarnal** [comment]
Closing this
