### ISSUE TITLE
Downloading / Preview Schema with Dereference all external $ref leads to server error

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1417]
Steps to reproduce:

Open API: https://studio.apicur.io/apis/24175
Select preview docs...

Error:
```
"https://studio.apicur.io/download?type=api&format=json&dereference=true&id=24175" is not a valid JSON Schema
Stack trace
SyntaxError: "https://studio.apicur.io/download?type=api&format=json&dereference=true&id=24175" is not a valid JSON Schema
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:28051)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:54299

ReDoc Version: 2.0.0-rc.50
Commit: 8bee3d5
```

Download schema with dereference results in:
```
<html><head><title>Error</title></head><body>Internal Server Error</body></html>
```

Downloading without dereference works as designed.

**Comment by EricWittmann** [comment]
I think this has been fixed, we just need a new upstream release to get the fix pushed to the cloud version.  Let me see if that can be done sooner rather than later.

@carlesarnal Any objection to an upstream release.  I know we haven't transitioned to the Quarkus release yet, but I think our existing upstream release process (using thorntail) will continue working fine for now, right?

**Comment by EricWittmann** [comment]
Note to @jsenko - I assigned this to you but I think it's already been fixed on `master`.  So nothing to do here yet.  I'll ping you here in the future if we do an upstream release and this problem isn't fixed.

**Comment by Stwissel** [comment]
It had worked before, so might be a regression?

**Comment by EricWittmann** [comment]
Always possible, but we haven't done a release in awhile so I think unlikely.

**Comment by carlesarnal** [comment]
No objections to an upstream release. The existing release process has not been modified so everything will continue working fine for now.

**Comment by jsenko** [comment]
hi, @Stwissel version `0.2.49.Final` is running on https://studio.apicur.io/ . Can you please check if the issue has been resolved?

**Comment by Stwissel** [comment]
Looks good. I like the new features

**Comment by carlesarnal** [comment]
Closing this one as it has been open for a while. Re-open if needed.
