### ISSUE TITLE
API Editor: disable Design tab for Definitions if too complex

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#142]
If the Definition's schema contains elements that the Designer is unable to understand, then disable the Design tab and force the user to edit the source code.

**Comment by msavy** [comment]
I dunno, I kinda like the idea that you can still continue adding stuff using the designer tab and it just leaves alone any stuff it doesn't know about (assuming it is syntactically valid or whatever caveats you need to apply).

**Comment by EricWittmann** [comment]
OK interesting thoughts.  Will need to be careful not to damage parts of the data model when making changes in the design view.  It already tries not to harm anything, but ymmv.

**Comment by msavy** [comment]
Yes, in the one I did (https://github.com/msavy/oai-docs/blob/master/apiman-gateway/gateway-api.oai.json) I added extra attributes but still found the design tab useful.
