### ISSUE TITLE
apicurio-ui CrashLoopBackOff in Openshift 4 

### ISSUE THREAD

**Issue by tillias** [Apicurio/apicurio-studio#1423]
Hello folks,

Many thanks for a very nice product.

We have a problem with apicurio-ui Pod in Openshift 4. It triggers CrashLoopBackOff  because of following stuff:

WARN org.keycloack.adapters.KeycloackDeployment  something related to route not available

1. Is there any possibility to clean uninstall it? What is the easiest way?
2. Is it possible to trace the problem further?

We're using OS Template. All other pods are running fine (-api and -ws)

Thanks

**Comment by tillias** [comment]
Now apicurio-studio-ui-deploy pod is dead and I can't read any messages from actual apicurio-ui anymore :(

**Comment by EricWittmann** [comment]
I'm not sure this is enough to go on.  Maybe with more log information we could help.  The UI pod is the simplest of the pods, so not sure what could cause a crash loop. :(

**Comment by tillias** [comment]
How can I restart ui-deploy pod? Also regarding cleanup is not clear how to proceed. If it was helm chart(s) there will be enough to helm uninstall. Not sure if it works with OS templates same way

**Comment by EricWittmann** [comment]
@jsenko or @famartinrh - you guys know more about openshift - can you offer any suggestions here?  Studio on OpenShift 4...
