### ISSUE TITLE
Gitlab projects not showing up when publishing APIs

### ISSUE THREAD

**Issue by mikisou** [Apicurio/apicurio-studio#1447]
When I try to publish an API and select gitlab, the project registered from gitlab does not show up.

<img width="1060" alt="スクリーンショット 2021-03-15 11 30 33" src="https://user-images.githubusercontent.com/28696649/111096667-695f5f00-8583-11eb-90a0-a5b0d09f5f4f.png">

**Comment by EricWittmann** [comment]
Is this a local installation of Studio or are you using studio.apicur.io?

Are there any errors in the browser console when you click the GitLab icon?

If it's a local installation of Studio, are there any relevant errors/stack traces in the server logs?

One thing you can try to see if you can narrow down the error is to use the corresponding Studio back-end APIs:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/IAccountsResource.java

For example, I can hit this endpoint:

`https://studio-api.apicur.io/accounts/GitLab/groups`

And get back my list of GitLab groups.  And then I can hit this:

`https://studio-api.apicur.io/accounts/GitLab/groups/Apicurio/projects`

For that to work you will need an auth token (bearer token auth) which you can get from here:

https://studio.apicur.io/config.js

It may be that your response will simply be "Internal Server Error" but I'm hoping for more. :)

**Comment by EricWittmann** [comment]
Oh sorry - I didn't notice that you linked to a PR that fixes this problem.  LOL  Sorry about that.  I'll leave my unhelpful comment above as an example to myself to be less hasty in the future. :)
