### ISSUE TITLE
Custom $references make the redoc documentation crash

### ISSUE THREAD

**Issue by DyspC** [Apicurio/apicurio-studio#1455]
When using the documentation feature on a specification with imported components the document is not rendered on the shareable link (the preview is OK)

Eg: https://studio-ws.apicur.io/sharing/516f17c7-408c-47f9-8746-42eb891175d4  
`Error downloading apicurio:40220 Failed to fetch`

I think this is because the preview uses the api with the `dereference` option and the sharing uses the raw DB document.

/apicurio-studio/front-end/servlet/src/main/java/io/apicurio/studio/fe/servlet/servlets/PreviewServlet.java  
`        String specURL = "download?type=api&format=json&dereference=true&id=" + apiId;`

/apicurio-studio/back-end/hub-editing/src/main/java/io/apicurio/hub/editing/sharing/SharingServlet.java  
`            ApiDesignContent adc = storage.getLatestContentDocumentForSharing(uuid);`

**Comment by EricWittmann** [comment]
Thanks for the report.  @carlesarnal can I assign this to you?

**Comment by carlesarnal** [comment]
Sure, I'll take a look.

**Comment by DyspC** [comment]
I'm no longer getting the issue on https://studio-ws.apicur.io/sharing/516f17c7-408c-47f9-8746-42eb891175d4 but the dereference part still causes errors (#1646)
