### ISSUE TITLE
API Editor: Save as both YAML and JSON? 

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#146]
At the moment AFAICT the primary save format is JSON. This is liable to have the side effect of eliminating certain YAML-only features such as multi-line syntaxes, handling of escaping, etc (as JSON is a subset of YAML). 

Hence, it might be cool to consider the ability to save both in YAML and/or JSON.

**Comment by msavy** [comment]
Although, I've been playing with the Swagger Editor a bit, and it seems to have neat auto-conversion between various types of JSON strings with control characters to YAML equivalents. That may be sufficient.

**Comment by EricWittmann** [comment]
JSON and YAML are now both supported in the source view as well as the *Download* action.
