### ISSUE TITLE
custom validate apicurio data models in apicurio studio

### ISSUE THREAD

**Issue by datnd-miagi** [Apicurio/apicurio-studio#1461]
When i custom validate apicurio data models and re-build apicurio data models, apicurio studio but the build takes too long time. 
Is there a faster way of mapping into apicurio studio?

**Comment by EricWittmann** [comment]
This is definitely a problem.  What I do is just copy the files in dist (after an apicurio-data-models build) into the appropriate location in `node_modules` in Studio.  I think that requires a restart of the UI dev server, but not a rebuild.
