### ISSUE TITLE
API Editor: Edit global consumes/produces

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#149]
It would be good at the preview and edit global level attributes of the document.

For example, I wanted to add 'consumes' and error codes to the top level, but this seems not to be possible at the moment.

```yaml
swagger: '2.0'
info:
  title: Apiman Gateway API
  description: The Apiman Gateway API
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  version: 1.3.0
# Bits I want to add
consumes: ['application/json']
responses:
  415:
    description: Unsupported Media Type.
```

**Comment by EricWittmann** [comment]
I have consumes/produces support as a separate ticket, and re-usable Response support as a separate ticket as well. 

Are there any other global settings you wanted to edit?

**Comment by EricWittmann** [comment]
Perhaps the first task would be to support source-editing at the global level.  That's on the radar too but I don't think there is a ticket for it.

**Comment by msavy** [comment]
Yeah, they were just examples. The purpose of this ticket is mainly to preview and edit globally.

**Comment by EricWittmann** [comment]
There is a separate ticket for managing re-usable responses.
