### ISSUE TITLE
Compatibility with newer postgres authentication schemes

### ISSUE THREAD

**Issue by DyspC** [Apicurio/apicurio-studio#1506]
Hello, 

I'm preparing a corporate deployment of apicurio studio using the 0.2.48 release and a postgresql storage and had a bit of trouble when this error happened `org.postgresql.util.PSQLException: The authentication type 10 is not supported.`

Looking into it I found that the postgres server tries to use [this scheme](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L75) that was released later and there are no tries for an older scheme. 
This is probably due to how our data department configured the database and I don't think I should try to lower their security settings.

However I tried using the latest version of the driver (42.2.20) in my local quarkus dev mode and it appears to run fine.

Is there anything that blocks the studio from using newer versions than 9.4.1212? This one dates back from Nov 2016 

--
The authentication scheme that appears to be required https://www.postgresql.org/docs/10/sasl-authentication.html

**Comment by EricWittmann** [comment]
No reason except it's the version we tested when starting the project.  :)  I have no reason to expect that a newer DB and DB driver would be a problem.

**Comment by DyspC** [comment]
That's nice to know thanks. 

There are probably more things to test than listing designs and a few edits though.

Do you have an ETA for the next release? Perhaps an upgrade of the driver could be added in?

**Comment by EricWittmann** [comment]
We're working on some improvements to the upcoming AsyncAPI editor.  So a new release is probably "soon".  :)  Any chance you could submit a PR to update the driver?

**Comment by DyspC** [comment]
Erm if you can write me down a checklist of what's to be tested along the driver update I should get some time next week.

Is there something I should know about the Aai editor improvements? Since I'm working on this I'd prefer avoiding surprises :) (We have a planned meet with @lbroudoux new week as well)

**Comment by EricWittmann** [comment]
Oh thanks - it sounds like you've done some basic testing and it looks OK.  I can followup this week with some testing on my end before we merge.  What version of PG did you test against?

**Comment by DyspC** [comment]
Our server version is 12.6 from what I can find using psql

**Comment by EricWittmann** [comment]
I've tested the new driver with PG 9 and PG 12 with no troubles.  Thanks for the PR.  Closing this now.

PR: https://github.com/Apicurio/apicurio-studio/pull/1511
