### ISSUE TITLE
Imports must be resolved before mocking in Microcks

### ISSUE THREAD

**Issue by bodograumann** [Apicurio/apicurio-studio#1533]
When trying to mock an API (that contains imported types) with microcks, the following errors occurs in the browser:

> io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
>	at io.apicurio.hub.api.rest.impl.DesignsResource.mockApi(DesignsResource.java:933)
> […]
> Caused by: io.apicurio.hub.api.microcks.MicrocksConnectorException: InternalServerError returned by Microcks server
>	at io.apicurio.hub.api.microcks.MicrocksConnector.uploadResourceContent(MicrocksConnector.java:171)
> […]

Microcks logs the following:
> 12:21:55.071 ERROR 1 --- [080-exec-3] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Invalid input: JSON Pointer expression must start with '/': "picurio:9#/components/responses/ForbiddenResponse"] with root cause
> 
>java.lang.IllegalArgumentException: Invalid input: JSON Pointer expression must start with '/': "picurio:9#/components/responses/ForbiddenResponse"

where `ForbiddenResponse` is the imported type.

This leads me to believe that imports are currently not resolved before sending the API definition to microcks and microcks itself is unable to do so (which makes sense).

**Comment by EricWittmann** [comment]
Yes this should be a simple matter of resolving the imports before sending to microcks.  If anyone is interested in trying to fix this, the dereferencing is easy enough.  An example is here:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/impl/DesignsResource.java#L622-L624

It's just a matter of figuring out where the submit-to-microcks action happens and introducing the dereferencer there.
