### ISSUE TITLE
Task: Upgrade to Postgres 12

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#1538]
We need to test PG 12 for both Studio and for Keycloak.  PG 9 is end of life soon.

**Comment by bthdimension** [comment]
Hi, is this already being worked on? I'm asking because PostgreSQL 9.6 is supported until November 11, 2021 and after this it would be considered a security issue in our company. Thank you very much!

**Comment by EricWittmann** [comment]
Thanks for the reminder.

**Comment by EricWittmann** [comment]
@carlesarnal what do you think is the fastest way to test this?  Upgrade the docker compose to PG 12?

**Comment by carlesarnal** [comment]
> @carlesarnal what do you think is the fastest way to test this? Upgrade the docker compose to PG 12?

Yes, that's probably the easiest way to see if anything breaks.

**Comment by carlesarnal** [comment]
@EricWittmann this one can be closed, right?
