### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by Emmanuel35** [Apicurio/apicurio-studio#1553]
Hi,

After last upgrade of https://studio.apicur.io/, my account is unavailable. A short message "Forbidden" is shown.

My account have :
* some API
* GitHub link

Could you help me ?

**Comment by megan-4c** [comment]
Clear all cookies and cache. Works until you have to re-log back in again :( But it's a temp work around

**Comment by EricWittmann** [comment]
Yes we are currently having issues with a Forbidden error popping up.  We're looking into it - apologies for the inconvenience.

**Comment by Stwissel** [comment]
I face the same issue. I'm sure you you will handle. Love your work

**Comment by EricWittmann** [comment]
I think this **should** be fixed now.  Please report immediately if you continue to see authentication problems.
