### ISSUE TITLE
Maven frontend build failing if maven is configured to use a proxy

### ISSUE THREAD

**Issue by DyspC** [Apicurio/apicurio-studio#1561]
Hello, 

I'm using maven behind a corporate proxy that I configured in my `~/.m2/settings.xml` and some part in the build chain tries to pass my proxy settings to every task, including the frontend's `ng build --prod` that fails because the `--https-proxy` & `--proxy` parameters are not wanted there.

The real issue probably lies with yarn or the maven plugin but setting this configuration in the main pom.xml fixes the issue in my case.

```xml
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>${version.frontend-maven.plugin}</version>
    <configuration>
        <yarnInheritsProxyConfigFromMaven>false</yarnInheritsProxyConfigFromMaven>
    </configuration>
</plugin>
```

If you don't see any issue perhaps it could be used in the main repository as well

**Comment by EricWittmann** [comment]
I don't see any issues.  What do you think @riprasad ?

**Comment by riprasad** [comment]
@DyspC You're absolutely right with your observations. I have come across similar issues when trying to build apicurio-registry behind Red Hat's proxy and we had to introduce a bunch of proxy settings, including the one you've suggested, to make it work.

@EricWittmann we already use this configuration in the registry [here](https://github.com/Apicurio/apicurio-registry/blob/master/ui/pom.xml#L89). So I don't see any issues either.

**Comment by EricWittmann** [comment]
OK great!  Who wants to submit the PR?  :) :)
