### ISSUE TITLE
Broken style for AsyncApi operation-section

### ISSUE THREAD

**Issue by DyspC** [Apicurio/apicurio-studio#1605]
Hello, 

I noticed a style issue in my latest deployment (0.2.49.Final based)

On page init the channel-operation-section has no style 
![image](https://user-images.githubusercontent.com/17125930/126641482-1a5dab57-65ae-4e97-af6b-c50d6fa703fe.png)

It appears to be because the first div in the section has no class instead of `"section {{ type }}-section panel-group"` 
![image](https://user-images.githubusercontent.com/17125930/126641992-ba8901f0-1e67-423d-b0bb-79bff0ab5246.png)

Changing the selected operation sets the correct classes and the UI looks fine after but and I can't reproduce the issue on openapi documents

On an older version the UI was this 
![image](https://user-images.githubusercontent.com/17125930/126643612-2f36cb04-c051-4ea1-a1d1-319b7ebdebff.png)

I ran bisect but couldn't go thinner than this due to typescript version issues

ec33902594dd14273d6051d5c8f5843e025d4e94 (refs/bisect/bad) chore: upgrade to Node.js 14
c21d05edd7ea7e8ddc8ef29ae553e171ab1160d2 chore: upgrade ngx-clipboard to 12.3.1
abb52050357fa850fdcdb15beacda45f6627b0e3 (HEAD) chore: add @angular/animations
b06bd13d3d586365b92df2a656b6509985178eb4 (refs/bisect/skip-b06bd13d3d586365b92df2a656b6509985178eb4) chore: upgrade ngx-boostrap to 5.5.0
f1f57f61f55dafc2fd8619db6a4d6bf4c44d7674 (refs/bisect/skip-f1f57f61f55dafc2fd8619db6a4d6bf4c44d7674) chore: upgrade to Angular 8
5d13d1183e8c67b9f6edaaafc70d9cdcb4f66fec (refs/bisect/skip-5d13d1183e8c67b9f6edaaafc70d9cdcb4f66fec) chore: upgrade Node.js to v10
12535eb9895d44f6401697de780e698df8c04120 (refs/bisect/skip-12535eb9895d44f6401697de780e698df8c04120) chore: upgrade typescript to 3.5.3

It also appears the top user/signedup title is missing but this part was not tested during my bisect

**Comment by EricWittmann** [comment]
Ah perhaps this is a casualty of the angular upgrade.  :(

**Comment by EricWittmann** [comment]
This was not a regression or a casualty of the angular upgrade.  Instead it was just a straightforward bug.  :)

I've actually found two bugs while looking into this.  Will be fixed shortly.

**Comment by EricWittmann** [comment]
Fixed!
