### ISSUE TITLE
Linked Account: Bitbucket

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#162]
Now that Apicurio supports account linking, add Bitbucket as one of the supported account types.  Currently Bitbucket is already included in the UI but disabled (with messages about support coming soon).

There are various changes required to add Bitbucket support:

* _Keycloak_: Configure a Bitbucket Identity Provider in Keycloak with alias "Bitbucket" (may require the latest version of KC)
* _UI_: Update the **Create API** page to enable the Bitbucket button.  Clicking that button should display Bitbucket-specific form fields similar to how the current GitHub form fields work.
* _UI_: Update the **Settings>Accounts** page to enable Bitbucket account linking
* _Back-End_: Add a Bitbucket implementation of a [ISourceConnector](https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/connectors/ISourceConnector.java)
* _Back-End_: Add the Bitbucket source connector to the [SourceConnectorFactory](https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/connectors/SourceConnectorFactory.java)

**Comment by EricWittmann** [comment]
Note that the source connector is the class that actually connects Apicurio to Bitbucket.  It should basically consist of a bunch of REST calls to the [Bitbucket API](https://developer.atlassian.com/static/rest/bitbucket-server/5.3.0/bitbucket-rest.html) and will only function if the user has a linked Bitbucket account.

**Comment by BabuGiri** [comment]
this feature is already part of 0.1.9 release?

**Comment by EricWittmann** [comment]
It's not part of 0.1.9 but it should be added soon (by the end of the month).

**Comment by BabuGiri** [comment]
ok thank you
