### ISSUE TITLE
k8s deploy Apicurio-ui-deploy.yaml error

### ISSUE THREAD

**Issue by Aiden-zht** [Apicurio/apicurio-studio#1665]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/64518464/133885066-77f75bbd-3640-459c-a3a0-0cbf69d8543b.png">
Is this env right？
kubectl apply -f apicurio-studio-ui-deployment.yaml 
error: error parsing apicurio-studio-ui-deployment.yaml: error converting YAML to JSON: yaml: line 71: did not find expected key
I had to comment it out
I don't know if it makes any difference

**Comment by EricWittmann** [comment]
Commenting that out should be fine, especially if you're not using Studio to edit AsyncAPI docs.  But even if you are, that should only impact the modal for creating channels.

Looking at that value, it does seem like it might fail to parse given there is a quote inside the pattern.  Might just need to escape the quote following the 7f.

**Comment by craicoverflow** [comment]
I _think_ this might have been fixed in https://github.com/Apicurio/apicurio-studio/pull/1736/files

**Comment by Aiden-zht** [comment]
Yes .
Thank you very much


| |
郑昊田
|
|
***@***.***
|
签名由网易邮箱大师定制


On 01/24/2022 ***@***.***> wrote：

I think this might have been fixed in https://github.com/Apicurio/apicurio-studio/pull/1736/files

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
