### ISSUE TITLE
Steps to build and deploy in Windows PC

### ISSUE THREAD

**Issue by BabuGiri** [Apicurio/apicurio-studio#167]
Hi i am trying to build and deploy latest source from git master on Windows 7 PC, tried below steps looks like they are not complete. 

mvn clean install
cd distro\quickstart\target\apicurio-studio-0.1.9
bin\standalone.sh -c standalone-apicurio.xml

above build and deployment instructions for Windows 7 is valid? if so please suggest if i am missing some thing.

Thank you

**Comment by EricWittmann** [comment]
Those are probably not exactly correct.  Something like this (from master) instead:

```
mvn clean install
mkdir C:\Temp\apicurio
copy distro\quickstart\target\apicurio-studio-0.1.10-SNAPSHOT-quickstart.zip C:\Temp\apicurio
cd C:\temp\apicurio
unzip apicurio-studio-0.1.10-SNAPSHOT-quickstart.zip
cd apicurio-studio-0.1.10-SNAPSHOT
bin\standalone.bat -c standalone-apicurio.xml
```

I just confirmed these steps on Windows 10 - so I *think* they should work, assuming you have jdk 8 installed and a reasonable version of maven.

Note that if you are interested in efficiently making code changes and seeing the results, I recommend our documentation on setting up a development environment:

https://apicurio-studio.readme.io/v0.1.9/docs/setting-up-a-development-environment

**Comment by EricWittmann** [comment]
Of course, you probably won't have an "unzip" tool on your path, so I assume you'll use 7zip or something to accomplish that step. :)

Also note that the reason you have to use the ZIP file (rather than running directly from target/apicurio-studio-VERSION as you attempted to do) is that the ZIP file contains extra stuff like the Keycloak adapter and some config files.

**Comment by BabuGiri** [comment]
Thank you, after using zip file i am able to deploy locally

i did not see https://apicurio-studio.readme.io/v0.1.9/docs/setting-up-a-development-environment this is very useful info.

**Comment by EricWittmann** [comment]
You are quite welcome. :)

**Comment by BabuGiri** [comment]
looks like when deployed locally "Google" authentication is not enabled and forgot password option also does not work for the account that are authenticated through Oauth (Google) any suggestion to proceed for authentication
