### ISSUE TITLE
Apicurio APIs for schema registry client not working.

### ISSUE THREAD

**Issue by nehasewda** [Apicurio/apicurio-studio#1673]
I want to use Apicurio's API and methods like client.listArtifacts(), client.getArtifactByGlobalId(X), createArtifact(),etc.
I have followed all the given official documents and included all the required configuration setup but still not able to use the above mentioned methods in my kafka streams application.

Please find the sample code used - 
streamsConfig.putIfAbsent(AbstractKafkaSerDe.REGISTRY_URL_CONFIG_PARAM, schemaRegUrl);
        streamsConfig.putIfAbsent(AbstractKafkaSerializer.REGISTRY_ARTIFACT_ID_STRATEGY_CONFIG_PARAM, SimpleTopicIdStrategy.class.getName());
        streamsConfig.putIfAbsent(AbstractKafkaSerializer.REGISTRY_GLOBAL_ID_STRATEGY_CONFIG_PARAM, GetOrCreateIdStrategy.class.getName());
        streamsConfig.putIfAbsent(JsonSchemaSerDeConstants.REGISTRY_JSON_SCHEMA_VALIDATION_ENABLED, Boolean.TRUE);

RegistryRestClient client = RegistryRestClientFactory.create(schemaRegUrl);
System.out.println(client.listArtifacts());
System.out.println(client.getArtifactByGlobalId(6));
System.out.println(client.getLatestArtifact("artifactId").toString());

In response to above statements, I am getting exception - javax.ws.rs.WebApplicationException.

Kindly help.

**Comment by jsenko** [comment]
hi @nehasewda I think this issue belongs to https://github.com/Apicurio/apicurio-registry/issues . Could you please reopen it there?

**Comment by jsenko** [comment]
You can also find examples of how to use registry rest client and serializers/deserializers here https://github.com/Apicurio/apicurio-registry-examples

**Comment by nehasewda** [comment]
> hi @nehasewda I think this issue belongs to https://github.com/Apicurio/apicurio-registry/issues . Could you please reopen it there?

Sure I will reopen it in there.

**Comment by nehasewda** [comment]
> You can also find examples of how to use registry rest client and serializers/deserializers here https://github.com/Apicurio/apicurio-registry-examples

I have already followed the same process but not getting the expected result.

**Comment by EricWittmann** [comment]
This has been moved to:  https://github.com/Apicurio/apicurio-registry/issues/1871
