### ISSUE TITLE
authentication problem when deployed locally

### ISSUE THREAD

**Issue by BabuGiri** [Apicurio/apicurio-studio#168]
looks like when deployed locally "Google" authentication is not enabled and forgot password option also does not work for the account that are authenticated through Oauth (Google) any suggestion to proceed for authentication

i followed instructions mentioned at https://apicurio-studio.readme.io/v0.1.9/docs/setting-up-a-development-environment step 7 in "User Interface Development" directs to login where i see above problem.

**Comment by EricWittmann** [comment]
I have been meaning to enable Google auth for local authentications, so I'll do that this morning.

However, you should still be able to log in by registering an account.  Authentication for Apicurio Studio (localhost) and authentication for Apicurio Studio (try live) is done through separate realms in the cloud version of Keycloak I've set up - so you can't use your "try live" account credentials to log into the "local" version of the app.

**Comment by BabuGiri** [comment]
when i try registering in localhost realm i get error email id (i am using same email id that i have registered for try live) is already registered.

**Comment by EricWittmann** [comment]
Really?   What email address are you using?

**Comment by EricWittmann** [comment]
Oh I see it.  You have two users registered in that realm.

**Comment by EricWittmann** [comment]
If you want, I can delete both those users and you can login via Google now that I've enabled that functionality. :)

**Comment by BabuGiri** [comment]
yes sure

**Comment by EricWittmann** [comment]
OK done.  Log out (if you're logged in now) and try again.  Google login should be enabled.

**Comment by BabuGiri** [comment]
Google Login for localhost is forking now.
"Linked account section" is still not ok, getting below error 

"Connection Error (Could Not Reach Server)

We couldn't reach the Apicurio Studio server! Perhaps try reloading this page in a few minutes? Maybe check your internet connection?"

**Comment by EricWittmann** [comment]
Trying to link your GitHub account failed?

**Comment by EricWittmann** [comment]
If so - are there any errors either in your Wildfly console (or in server.log) or in the browser's javascript console?

**Comment by BabuGiri** [comment]
"Linked account section" does not show option to link github before itself i see above error

**Comment by BabuGiri** [comment]
there was a problem back-end was not up, now everything is ok.

Thank you

**Comment by EricWittmann** [comment]
Oh good! :)
