### ISSUE TITLE
the docker image requires root permission

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-studio#170]
when deploying on OpenShift the project needs additional root rights to deploy, ideally this should be avoided

v.0.1.9

**Comment by danmikita** [comment]
@lucamaf I am currently working on converting the app to be 100% Kubernetes and OpenShift compatible. Hopefully this will be finished in the next couple days.

**Comment by EricWittmann** [comment]
I believe this should be addressed by this pull request:

https://github.com/Apicurio/apicurio-studio/pull/201

Official OpenShift support!

**Comment by EricWittmann** [comment]
I believe this has been addressed.  Please re-open if not.
