### ISSUE TITLE
invalid redirect_uri when deployed on OpenShift

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-studio#171]
when deployed on openshift the login page automatically redirects to rhcloud domain which is not considered valid

https://auth-apistudio.rhcloud.com/auth/realms/apicurio-local/protocol/openid-connect/auth?response_type=code&client_id=apicurio-studio&redirect_uri=https%3A%2F%2Fapicurio-studio-api-design.app.test.openshift.es%3A443%2Fstudio%2F&state=f1940802-d943-49d4-9631-21e1ad5e0718&login=true&scope=openid

error:
`Invalid parameter: redirect_uri`

v.0.1.9

**Comment by danmikita** [comment]
@lucamaf As a part of the conversion to a container architecture - I am attempting to run Keycloak locally in a container alongside the front-end, back-end, and the database.

**Comment by lucamaf** [comment]
it would be nice to have it parametric, so that one can re-use the keycloak instance already running in openshift

**Comment by EricWittmann** [comment]
How are you deploying it to OpenShift?  The Keycloak settings are all configurable via standalone-apicurio.xml, so you should be able to use whatever KC instance you want.  I haven't done any specific work on getting it running in OS myself, so am not familiar with the nitty gritty details yet.

Hopefully @danmikita knocks out any remaining configuration bugs. :)

**Comment by EricWittmann** [comment]
Hey @lucamaf - it's been a bit of a long road but I have a PR available that provides Open Shift v3 support.  If you are still interested, I'd love to get your feedback:

https://github.com/Apicurio/apicurio-studio/pull/201

It should make deploying to OpenShift *much* easier, at least as a starting point.  Note that the "Try Live" version of Apicurio will be deployed to a production OSv3 cluster very soon, replacing the old *rhcloud* instance.

**Comment by EricWittmann** [comment]
I think this has been addressed with the recent support for OpenShift v3.  Closing this issue.  Please re-open if you find something doesn't work as expected.
