### ISSUE TITLE
API Editor: allow editing of "Servers" for path items and operations

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#176]
In a 3.0 document, the Path Item and Operation objects both include a "servers" section.  When editing 3.0 docs, show the servers info in the relevant forms and allow users to edit that info.

**Comment by EricWittmann** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathItemObject

**Comment by dcu** [comment]
@EricWittmann would you consider giving this task more priority?

**Comment by EricWittmann** [comment]
Yes. :)  Feedback from the community is one of the primary ways to address priorties!

**Comment by dcu** [comment]
awesome, now that it allows to download it'd be great to import files, not sure if there's a ticket to do that

**Comment by EricWittmann** [comment]
Definitely open a ticket for that.  One workaround right now is that you can check a file into a GitHub repository and import from there.

**Comment by EricWittmann** [comment]
@dcu this is implemented and live.  The only thing missing is the ability to specify enum values for server variables.  I'll get to that at some point, but hopefully what's there is OK for now. :)
