### ISSUE TITLE
Connection refused running docker images locally

### ISSUE THREAD

**Issue by dannybaggett** [Apicurio/apicurio-studio#1769]
I followed the [docker instructions](https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose), but I can't connect to the UI at http://MY_HOST:8093. I can connect to Keycloak just fine at http://MY_HOST:8090.

**Comment by dannybaggett** [comment]
Scanned the docker logs, looks like the UI container is being killed for some reason.

`docker-compose_apicurio-studio-ui_1 exited with code 137`

**Comment by dannybaggett** [comment]
Fired everything up again today and everything works as documented. Not sure what the issue was. Don't recall changing anything specifically. Closing this issue.

**Comment by EricWittmann** [comment]
This is my favorite kind of issue!  :)

Sorry it's taken so long for me to notice this.  My GH email backlog is once again ... daunting.

Glad it worked itself out.
