### ISSUE TITLE
API Editor: manage Examples when editing content (request body, responses)

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#179]
The spec allows a number of examples to be included in each Media Type.  The UI should allow users to add their own examples.

**Comment by dcu** [comment]
@EricWittmann any chance you can give this one more priority? I'm trying to auto generate a mock server from the spec

**Comment by EricWittmann** [comment]
I sure can.  Might be able to put something together this week or next.

**Comment by EricWittmann** [comment]
Examples can be set in a number of different places in the spec - which places in particular are most important for your mocks?

**Comment by dcu** [comment]
requests and responses would be super useful

**Comment by EricWittmann** [comment]
OK yeah - that probably makes the most sense.  I've had some specific requests for that feature from others  as well.  I got a couple of other tasks that became high priority, but I've pushed this up the list and will try to get to it soon.

Thanks for the feedback - it's always helpful.

**Comment by EricWittmann** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#mediaTypeObject
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject

**Comment by EricWittmann** [comment]
Update:  I have completed the commands for this, but am still trying to figure out a good UI solution.
