### ISSUE TITLE
Offline editing mode

### ISSUE THREAD

**Issue by craicoverflow** [Apicurio/apicurio-studio#1793]
I'm not sure how feasible/easy this is - but it would be nice if I could continue being able to edit and view my API document in Studio if my internet goes down.

**Comment by carlesarnal** [comment]
@EricWittmann correct me if I'm wrong, but this is already happening, right?

**Comment by fari-99** [comment]
@craicoverflow , well you can install apicurio studio using docker-compose. so you can do it on your system.

it different matter if you using apicurio-studio online tho.

**Comment by fari-99** [comment]
@craicoverflow , well you can install apicurio studio using docker-compose. so you can do it on your system.

it different matter if you using apicurio-studio online tho.

**Comment by craicoverflow** [comment]
Hey @fari-99 thanks, yes I am asking specifically about the online version. The reason I am asking is because it would be a nice feature to have it it were feasible. I am a Google Docs user and I am still able to edit my documents regardless of my online status. It also helps that I can _continue_ to edit my document if my internet goes down, and will synchronise with the cloud once I go back online.

**Comment by craicoverflow** [comment]
> 

Ah yes so I see that it works for me now if I am on an edit session and when i turn off my internet access i can continue to edit, great!

I guess my original thought for a feature would be one step further. Currently, you need to be in Studio for the offline mode to work. I was thinking that maybe it this would not matter. You could turn on your laptop while disconnected and open Studio on your browser and be able to access all design files. I don't think that is possible and have not checked its feasibility at all, so may be difficult to implement.

**Comment by EricWittmann** [comment]
The editor is resilient to internet failures, as Carles observed.  That's the offline mode we support.  We do not support browsing your API designs in offline mode, since all that stuff is stored in the server's DB.  While it would be possible to allow caching some of that locally, that's a pretty major undertaking.  We would need to discuss exactly how something like that would work.  It's an interesting idea, but strikes me as being quite a large body of work.
