### ISSUE TITLE
Update release workflow to push container images to quay in addition to docker

### ISSUE THREAD

**Issue by wilvdb** [Apicurio/apicurio-studio#1855]
Is it possible to push a new version to quay ?
Only version 0.2.48.Final is available on quay.

**Comment by EricWittmann** [comment]
I have pushed 0.2.49 -> 0.2.52 into quay.  Note:  0.2.52 may have a problem.  I need to test it locally, but it failed when we deployed it to studio.apicur.io - so use caution.

**Comment by EricWittmann** [comment]
I think we've finally hit the limit of Thorntail.  0.2.52 is broken in a way that I think will be hard to track down (problem with Jandex scanning the dependencies).  Since Thorntail isn't being updated anymore, it is time for us to upgrade to Quarkus officially.  @carlesarnal FYI

**Comment by EricWittmann** [comment]
I figured out which dependency was causing the issue.  (graphql-java)

Fixed in https://github.com/Apicurio/apicurio-studio/commit/a9a733ecb22480aa88d361541ee50c05caaa8239

I also updated the release workflow to push to quay.  Will do another release now.
