### ISSUE TITLE
Error 500 when integrating with Microcks

### ISSUE THREAD

**Issue by Renanh** [Apicurio/apicurio-studio#1876]
Below are my settings:

Command: helm install -f values/apicurio-helm-config.yaml apicurio one-acre-fund/apicurio -n apicurio

![image](https://user-images.githubusercontent.com/8283925/162632438-c012c3c2-3206-48fe-84e5-f67de4684876.png)

Error:

![image](https://user-images.githubusercontent.com/8283925/162632541-16d1949b-4f3b-4d89-acc1-0ef4d76d5833.png)

![image](https://user-images.githubusercontent.com/8283925/162632670-be898b59-d6bb-4ba2-81fc-fbeaa4387f2e.png)

**Comment by d0d00n** [comment]
Hi Renanh,

I think you are just missing the protocol for the URL, so http:// or https://

Cheers.

**Comment by EricWittmann** [comment]
Thanks for responding to this @d0d00n !

**Comment by EricWittmann** [comment]
I'm marking as closed because this issue has been answered.  We don't have confirmation that it worked, but @Renanh can re-open the issue if the suggestion didn't work.
