### ISSUE TITLE
Properties Section: Example 

### ISSUE THREAD

**Issue by lerio29** [Apicurio/apicurio-studio#1887]
the generated examples do not respect the rules  like minLength/maxLength

![image](https://user-images.githubusercontent.com/8198968/165116818-a03f3b70-5f82-4de4-bd9f-17ffe8376844.png)

**Comment by EricWittmann** [comment]
Good point, thanks.  I've added it to the editor backlog.

**Comment by pedrogclp** [comment]
I'll be watching this, it's a good point.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-studio/pull/2140
