### ISSUE TITLE
Can we directly add records to 'acl' for sharing, or is it dependent on invitations/etc?

### ISSUE THREAD

**Issue by nneul** [Apicurio/apicurio-studio#1898]
We're wanting to automate having many of our designs "automatically collaborated on". Can we populate our own records into 'acl' Pg table standalone?, or do we need to also have records in 'acl_invites'?

Additionally, will Apicurio have an issue if a "user_id" exists in that table (email addr in our case) that doesn't actually exist as a user yet due to not having logged in?

**Comment by EricWittmann** [comment]
With the caveat that I haven't tried this experimentally, I can say with reasonable confidence that directly populating the `acl` table should be no problem.

And Studio will have absolutely no problem with a `user_id` showing up in the table before that user's first login.
