### ISSUE TITLE
API Details: Action to convert from 2.0 to 3.0

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#190]
We should have an action allowing the user to convert an API Design from OAI 2 (swagger) to OAI 3.  This should be dependent on such a feature existing in one of the oai-ts-* libraries?  A new library for transforming between OAI versions perhaps?

**Comment by aoudiamoncef** [comment]
Hi @EricWittmann,
I think that this amazing feature should be more exposed in the documentation. I could be more visible in the import menu
