### ISSUE TITLE
Question: how to delete a collaborator?

### ISSUE THREAD

**Issue by ignas-sakalauskas-cko** [Apicurio/apicurio-studio#1903]
Hi Team,

Thanks for the amazing tool!

We recently had one collaborator leaving our team, and I wanted to delete that collaborator, however even as an owner I can't find a way to do that on https://studio.apicur.io. 

Can you please help?

Thanks!

**Comment by EricWittmann** [comment]
You should be able to do that via the UI by going here:

![image](https://user-images.githubusercontent.com/1890703/168158157-2661a684-2c2d-4e94-ab65-58f1a3408a5f.png)

From there you will get a collaborator management page:

![image](https://user-images.githubusercontent.com/1890703/168158258-92732d53-10a6-4a74-8b9e-3aad4a3b9e9f.png)

Click the trashcan to remove a collaborator.

**Comment by ignas-sakalauskas-cko** [comment]
Hi @EricWittmann,

Thanks for the quick reply! Yes, this indeed helps to remove Collaborators!

And how about removing some other Owner? 🤔 

Thanks,
Ignas

**Comment by EricWittmann** [comment]
I'm afraid there is no way to remove another Owner.  They can remove themselves but you cannot remove them.  The only workaround would be to copy/clone the API design.

**Comment by ignas-sakalauskas-cko** [comment]
Thanks for the clarification @EricWittmann! 🙇
