### ISSUE TITLE
How to use Apicurio studio open api generator with Quarkus

### ISSUE THREAD

**Issue by renandevenz** [Apicurio/apicurio-studio#1919]
I'm trying to use Apicurio studio to generate API stubs like I did using Spring but I don't know how I do it using Quarkus.
Does anyone know how to configure the plugin for Maven? If you have any sample projects.
Thanks.

**Comment by rafamqrs** [comment]
Hey @renandevenz do you mean openapi generator? If yes, take a look at this https://appdev.consulting.redhat.com/tracks/runtimes/quarkus/bootstrap.html

**Comment by carlesarnal** [comment]
Hi @renandevenz,

We have extracted the codegen feature to a Quarkus [extension](https://github.com/Apicurio/apicurio-codegen/tree/main/quarkus-extension) that one can use to generate his API stub. All the documentation (is very simple) and configuration needed can be found there.
