### ISSUE TITLE
Latest Image Released Jun. 2 breaks syncing with Microcks

### ISSUE THREAD

**Issue by deanpeterson** [Apicurio/apicurio-studio#1927]
Ever since the underlying image in the apicurio image stream updated on June 2, I get the following errors syncing to microcks: https://gist.github.com/deanpeterson/2c4f0ec4ccbad995fe13ff9b37ca431f

**Comment by fbuinosquy1985** [comment]
yes is the same error that i opened a issue here https://github.com/Apicurio/apicurio-studio/issues/1925

**Comment by deanpeterson** [comment]
I spoke with a principal software engineer on the team and they have acknowledged the bug. The fix will be coming very shortly.

**Comment by mhagnumdw** [comment]
Same error here! Any news? Tks!

**Comment by GeneralLuzi** [comment]
hey @EricWittmann any news on that? Thanks!

**Comment by EricWittmann** [comment]
Sorry this is taking so long.  We should have a new release based on Quarkus next week.  We've had some competing priorities and some vacations that have delayed things a bit.

**Comment by EricWittmann** [comment]
BTW I'm going to close this as a duplicate of https://github.com/Apicurio/apicurio-studio/issues/1925
