### ISSUE TITLE
Request body schema is missing "/"

### ISSUE THREAD

**Issue by hguerrero** [Apicurio/apicurio-studio#195]
When adding a request type, there is a missing "/" in the ref path. 

![image](https://user-images.githubusercontent.com/1001939/32248986-a272a8ec-be44-11e7-91b5-a29692fec98f.png)

**Comment by EricWittmann** [comment]
This has been fixed in a "recent" change.  I think it was broken when I added 3.0.0 support, but it has since been fixed.
