### ISSUE TITLE
Change my login on hosted instance https://studio.apicur.io/

### ISSUE THREAD

**Issue by dougbreaux** [Apicurio/apicurio-studio#1961]
I guess when I initially joined, I used an email address as my ID, but I then switched to using my GitHub login. I'd like my Profile and edits to appear as that identity, not as the original email address. And/or I'd like to change the email address.

Can someone please help me do this?

**Comment by dougbreaux** [comment]
Help, please?

**Comment by EricWittmann** [comment]
Hi @dougbreaux - the hosted Apicurio Studio isn't a production environment, so support is on a sort of "best effort" basis.  :)

That said, I'll see what I can do.

**Comment by EricWittmann** [comment]
Hey Doug - ping me directly via email (you can get my email address from GH) on this topic.
