### ISSUE TITLE
"Invalid parameter: redirect_uri" on remote host

### ISSUE THREAD

**Issue by GBR-613** [Apicurio/apicurio-studio#1968]
I never worked with Apicurio before. I installed it now on remote Linux host. With port forwarding local 8443 to remote 8443 I open https:8443//localhost/studio and it works fine.  However when I try to connect the remote IP directly, I get a window saying "Invalid parameter: redirect_uri" and link "Back to an Application" which points to https:8443//localhost/studio.
My attempts to set apicurio-ui.hub-api.url [as described here](https://www.apicur.io/studio/docs/running-on-an-external-server) caused the JBoss not to start.

One idea I have got after looking for similar issues is the following. According to our organization security regulations I am allowed to open the incoming traffic for specific ports and specific IP addresses only. I opened ports 8443 and 80 to my workstation IP address. However if you use cloud based Keycloack server for authentication by default, I guess I also need to permit the traffic from them. Which ports and addresses should I open?  Please suggest.

Any additional considerations about setting up the remote host would be highly appreciated. 
Thanks in advance!

![image](https://user-images.githubusercontent.com/17687869/181307768-fec663d2-6856-45b9-abff-edada6a90000.png)

**Comment by Piscenois** [comment]
Hi !

In Keycloak, is your client (apicurio-studio) access type "public" or "confidential" ? 
WIth my first installation mine was confidential and I had the same error. Switching to public solved the problem.

Regards

**Comment by GBR-613** [comment]
@Piscenois Not sure what do you mean, but anyway it disappeared after workarounding #1969. So I am closing it.
