### ISSUE TITLE
Apicurio integration with Microcks past issue back?

### ISSUE THREAD

**Issue by aaniceto** [Apicurio/apicurio-studio#1987]
Hi

I've installed apicurio 0.2.56-snapshot, which is working, with 2 years old data, integrated with keycloak v14, and installed microcks from git, integrated with Microcks realm in the same keycloak, able to login.

I've followed the integration instructions and when trying to mock I get:

```
10:29:31,810 ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /api-hub/designs/1/mocks: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:82)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:346)
        at org.jboss.resteasy.resteasy-jaxrs@3.7.0.Final//org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:193)
```

I've tried to put a wrong service account password when starting microcks, and I got the same error.

That's how I start apicurio

./distro/quickstart/target/apicurio-studio-*-SNAPSHOT/bin/standalone.sh -c standalone-apicurio.xml -b 0.0.0.0 -Djboss.socket.binding.port-offset=200 \
        -Dapicurio.hub.microcks.api=http://10.101.2.102:8080/api \
        -Dapicurio.hub.microcks.clientId=microcks-serviceaccount \
        -Dapicurio.hub.microcks.clientSecret=XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX \
        -Dapicurio-ui.feature.microcks=true

When I click mock in apicurio the browser does a post request to 
http://10.101.2.102:8280/api-hub/designs/1/mocks which returns 500 Internal Server Error

8080 is the microcks API, 8280 is apicurio.

Thanks

**Comment by EricWittmann** [comment]
Oh interesting!  I haven't tried the quickstart yet with the latest release.  I will need to have a look.  The quickstart is based on Wildfly, which is similar enough to Thorntail that I'm not shocked to hear that it has the same YAML problem.  But I'm guessing it's actually fixable in Wildfly since that is still an actively developed platform.

That said, you'll be better off using the docker images if you can.  And if you cannot, then we can help figure something else out.  The quickstart is more suitable for evaluation purposes.

**Comment by EricWittmann** [comment]
OK I just cut a new release of `0.2.56.Final` that should fix the quickstart.  If you have a chance to give it a try I'd be happy to hear the feedback.  :)

**Comment by aaniceto** [comment]
Hi Eric,

I've pulled the code, run a new mvn clean install.. just updated the configuration-apicurio.xml and moved the 'data' folder to the new 0.2.57-SNAPSHOT folder.

Got the same internal server error.

```
21:26:29,468 ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /api-hub/designs/3/content: org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'
        at org.jboss.resteasy.resteasy-core@4.7.6.Final//org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
```

Doubting me a bit (not much, but some), did you try on your side?

**Comment by EricWittmann** [comment]
Full disclosure - I tested downloading an API as a YAML file which has suffered from the same bug.  That's what I was testing - not specifically the Microcks issue.  It's possible the bug still exists there (I don't have a local config that enables the Microcks integration anymore).  I'll need to try it.

That said, can you try simply downloading your API as YAML and see if that works?

I'll also try the latest release quickstart when it's ready in a few minutes.

**Comment by aaniceto** [comment]
Yes yes, I tried the same. I didn't went for the microcks integration. Just went to apicurio, click download, yaml. That being said it's the same error I have when I try to microcks integration (because in the backend it's trying to generate the yaml for that use case I assume).

**Comment by EricWittmann** [comment]
OK I'm checking the most recent release.  Maybe I messed something up.  I had it working in Wildfly before cutting the release.

**Comment by EricWittmann** [comment]
Yup confirmed.  The bug still exists in the latest quickstart.  :sigh:

I'll try again.

**Comment by EricWittmann** [comment]
OK I think I got it this time.  Can you try building locally (latest from `master`) and try again?

**Comment by aaniceto** [comment]
Hi, i was only able to test it now.. I can confirm the YAML download works and also the microcks integration. Thanks!
