### ISSUE TITLE
Error with isDatabaseInitialized call

### ISSUE THREAD

**Issue by danylaberge** [Apicurio/apicurio-studio#1988]
We are deployed on openshift using the template, I believe we are configured to use latest release. Yesterday, when v0.2.55 was released, APICurio stopped working properly when trying to load api designs.

Here is the error in the log of the API : 
2022-08-23 14:23:09,978 INFO  [io.api.hub.cor.sto.jdb.JdbcStorage] (executor-thread-0) Initializing the Apicurio Hub API database.
2022-08-23 14:23:09,979 INFO  [io.api.hub.cor.sto.jdb.JdbcStorage] (executor-thread-0) 	Database type: h2
2022-08-23 14:23:09,988 ERROR [io.und.req.io] (executor-thread-0) Exception handling request 958fe489-56ac-4943-a276-f9a20b88b75f-8 to /designs: org.jboss.resteasy.spi.UnhandledException: org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: relation "apicurio" already exists [statement:"CREATE TABLE apicurio (prop_name VARCHAR(255) NOT NULL, prop_value VARCHAR(255))", arguments:{positional:{}, named:{}, finder:[]}]

After investigation, we found out that it was trying to check if the database was initialized with the wrong **database type**. We are deploy on **Postgresql 9**, not **h2**. We managed a workaround by creating an upper case API_DESIGNS table in our database so that the isDatabaseInitialized check is successful. Maybe we are missing a new parameter and it defaults to h2?

**Comment by EricWittmann** [comment]
Thanks @danylaberge we are working through some kinks in the system.  :)  We're in the process of migrating from thorntail to quarkus as your runtime platform.  We tried to make sure the new Quarkus version was a drop-in replacement, but we missed an ENV variable or two.  Working on that now.  (note:  our openshift deployment also broke and we rolled it back)

We should have this fixed and a new release cut tomorrow.  If that's not quick enough, you can modify your deployment config to add the following ENV variable:

`APICURIO_HUB_STORAGE_JDBC_TYPE`

Set the value to `postgresql9` and everything should work.  I haven't actually tested this directly, but it *should* work.

That said, if you can wait for a new release tomorrow that might be better.  :)

**Comment by danylaberge** [comment]
Thanks might try it out as I am getting more errors, like unable to save a change.

**Comment by EricWittmann** [comment]
OK I just cut a new release of `0.2.56.Final` that **should** address your issues.  If you can give it a try that would be awesome.

**Comment by danylaberge** [comment]
I have removed the workaround from the DB we did and added the new env variable. Is it required? So far, the issue is fixed for us, let us know if the ENV still need to be there.

**Comment by EricWittmann** [comment]
The ENV variable is now optional, as of the latest release.  You can keep it or remove it at your preference. :)
