### ISSUE TITLE
Generate Vert.x client and server stubs

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#20]
It would be fantastic (if we get that far) to have a way to generate Vert.x client and server stubs from the Swagger doc.

Some Googling reveals some demand for it, and there is no such functionality at the moment.

**Comment by mccrackend** [comment]
It looks like there is a swagger-codegen module that generates vert.x clients already: https://github.com/swagger-api/swagger-codegen#making-your-own-codegen-modules

There is an opportunity to extend codegen to create the server side module.  Either way - this type of stub-gen probably doesn't belong in the apicurio-studio code.  It's not a bad idea to maybe find a way to integrate the swagger-codegen project into studio though..

**Comment by EricWittmann** [comment]
+1 - integration with swagger-codegen is likely the solution.  I haven't really tried using that project yet, but definitely agree that we don't want to be in the business of generating servers and clients if we can avoid it.

**Comment by EricWittmann** [comment]
Duplicated by https://github.com/Apicurio/apicurio-studio/issues/302
