### ISSUE TITLE
Allow users to join without invitation url?

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#2001]
We deployed Apicur.io on our Openshift cluster integrated with GitHub Enterprise - works like a charm. Kudos to the team.

**Question**: Can I configure studio, so users who can authenticate can access any API without needing an invitation link first?

**Comment by EricWittmann** [comment]
Yes there is a feature that you can enable that will allow any authenticated user to see any API created by any other user. The feature is called share for everyone. There is an environment variable. Just set that to true and you should be good to go. I'm on mobile at the moment with limited ability to search the code but hopefully that is enough to get you started.

**Comment by Stwissel** [comment]
We used 
```bash
APICURIO_SHARE_FOR_EVERYONE=true
APICURIO_UI_FEATURE_SHARE_WITH_EVERYONE=true
```

Works like a charm. Thx for the pointer
