### ISSUE TITLE
Import API from File/Clipboard fails with a Java error

### ISSUE THREAD

**Issue by GBR-613** [Apicurio/apicurio-studio#2018]
The following exception occurs when I paste the content and press on "Import API" button:

org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.io.ContentReference com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createContentReference(java.lang.Object)'

See #1969 for more details.

Please notice, #1969 is closed as duplicated #1925 which is said to be fixed, however the problem still exists in  `0.2.58.Final`.
Copying `jackson-core-2.13.3.jar` to `modules/system/layers/base/com/fasterxml/jackson/core/jackson-core/main/`
and editing `module.xml` in that directory to specify the copied jar as the resource to load solves the problem.

In previous build I worked with, that jackson-core version was 2.9.9. 
Now it is 2.12.6 which is closer to the one used in other modules (2.13.3), but still different.

**Comment by EricWittmann** [comment]
Based on the description you've given, I assume you are using the quickstart.  Is that correct?

I fixed the quickstart YAML problem but that fix didn't make it into 0.2.58.Final:

https://github.com/Apicurio/apicurio-studio/commit/e87c7d87c6fe09cb57f5b8abe0d34e652c61c280

The fix will get into the quickstart in the next release.

That said, it's worth noting that the quickstart is not really meant for production use.  It would be better to use the docker images, either directly or by deploying to e.g. kubernetes.  Just my opinion on t hat.  :)
