### ISSUE TITLE
Large changes lead to lost connection

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#2024]
We have large examples in our Schema. When trying to change those, we get "Connection to server lost" errors. On inspection of the console this error is found:

Websocket max frame length of 65536 has been exceeded

A proposed solution can be found here:
https://stackoverflow.com/questions/33233900/websocket-max-frame-length-of-65536-has-been-exceeded

**Comment by EricWittmann** [comment]
Here's the relevant change: https://github.com/Apicurio/apicurio-studio/blob/master/platforms/quarkus/ws/src/main/resources/application.properties#L25

**Comment by EricWittmann** [comment]
Closing as stale.  Please reopen if this is still a problem.
