### ISSUE TITLE
longer session lifetime for studio.apicur.io?

### ISSUE THREAD

**Issue by Glucksistemi** [Apicurio/apicurio-studio#2037]
I use cloud version (https://studio.apicur.io) with authorization by Google account. And I really, really got tired of relogins. It seems that session lives about a hour or so and "remember me" flag does not affect authorization over google. And while I'm writing actual code, I periodically check my API editor with some fixes. Not too often, but many times per day. And almost every time I need to login again. It really makes me angry. I believe a 24h-long session will be secure enough and will not piss off anyone like me

**Comment by EricWittmann** [comment]
That's fair feedback.  I'll see if I can easily change this, as I agree that relogins are annoying.

One thing I would remind everyone though, is that the cloud version of Studio is really intended to be an evaluation version.  Of course you're welcome to use it for "real" work, but we don't have any SLAs or anything associated with it.

**Comment by EricWittmann** [comment]
OK I've made some changes to token timeouts.  I'm not really a Keycloak admin so it might have the effect we want or it might not.  Please update this ticket with your experience. :)

**Comment by Glucksistemi** [comment]
> OK I've made some changes to token timeouts. I'm not really a Keycloak admin so it might have the effect we want or it might not. Please update this ticket with your experience. :)

Thank you!

Sessions now seems to be long enough, so your solution works!
