### ISSUE TITLE
If I want to upgrade my server to Mysql 8 series, are Apicurio Studio, Apicurio Registry and Kyecloak supported?

### ISSUE THREAD

**Issue by Yuutakasan** [Apicurio/apicurio-studio#2041]
I'm thinking of moving from the 5.7 series to mysql 8 series soon. Keycloak recently failed to upgrade and I would like to know about other support.
If you have verified anything, could you please let me know?

I am going to test this week apicurio studio, apicurio registry and microcks also with mysql8 series connected.

**Comment by Yuutakasan** [comment]
Sorry. I may be mistaken here, so I will look into it some more.

**Comment by EricWittmann** [comment]
We don't have anything verified.  I can't say with confidence one way or another if it will work.

**Comment by Yuutakasan** [comment]
Thanks for the reply. I think I need to update the JDBC driver here. If there is an update, I will share it with you as it may be helpful.
