### ISSUE TITLE
Integration: Support local/self-hosted source control (GitHub, etc)

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#206]
Currently we only support the official hosted versions of GitLab, GitHub, and Bitbucket.  It would be nice to be able to support self-hosted versions of those services, for enterprises using them locally.

Assuming these systems use the same API for local versions as for the hosted versions, it should be relatively easy to make the URL to the API configurable.  

However, the challenge is likely Authentication.  Currently Apicurio leverages the Account Linking feature of Keycloak.  So it's Keycloak that handles the OAuth flow to authorize access to the user's content.  Keycloak also manages the OAuth access token created via the flow.  Apicurio simply delegates the OAuth flow to KC and also queries KC for the access token whenever it is needed.

**Comment by The-Alchemist** [comment]
We use a self-hosted Gitlab CE, so this would be very interesting.  If you point us in the right direction, we could probably submit a PR. :)

**Comment by EricWittmann** [comment]
Nice!  All the gitlab code is here:

https://github.com/Apicurio/apicurio-studio/tree/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/gitlab

The shortest path to this is probably to make the gitlab URL customizable via configuration.

**Comment by EricWittmann** [comment]
Having thought about this a bit more, I think there is a larger barrier to this than I originally considered.  The problem isn't so much the Apicurio->GitLab integration as it is the OAuth account linking piece.  The account linking is all handled via Keycloak, which is a separate service/server.  If you were to install your own Keycloak instance, you could probably configure it to perform OAuth against your local GitLab installation, but I have not tested this.

So I think there are two components to this:

1) Install a local Keycloak and configure it with the local GitLab server as an Identity Provider (I could help point you in the direction of how you might do this)
2) Update Apicurio so that the GitLab URL is configurable.  This basically amounts to searching the source code for the GL URL and making it configurable.  There will be a small number of them.

**Comment by BabuGiri** [comment]
We use Self hosted bitbucket working with self host bitbucket would be very helpful, i suppose we can extend above Git lab work ones ready to bitbucket as well.

**Comment by EricWittmann** [comment]
Of course, the workaround right now is to simply download the API and commit it manually.  But it would definitely be nicer to have integration with self hosted git systems.

**Comment by EricWittmann** [comment]
Note to anyone working on this in the future, GitLab community edition can be downloaded and installed for free here:

https://about.gitlab.com/installation/

Bitbucket is an Atlassian product.  There is a free 30 day trial version that can be used here:

https://www.atlassian.com/software/bitbucket/download

**Comment by mpikop** [comment]
> Install a local Keycloak and configure it with the local GitLab server as an Identity Provider (I could help point you in the direction of how you might do this)

@EricWittmann Is there any documentation you have available for doing this? I'm digging through keycloak and not finding what I think I should be looking for

**Comment by EricWittmann** [comment]
Documentation on configuring a GitLab identity provider is here:

https://www.keycloak.org/docs/latest/server_admin/index.html#gitlab

That still won't get us where we want to be though.  That'll enable authenticating using the local GitLab server (and probably linking a GL account in Apicurio), but it won't allow actually publishing an OAI definition to GitLab.  The code in Apicurio that does that uses a non-configurable URL to access the GitLab API.  Some changes in Apicurio are definitely needed to support local GitLab/GitHub/Bitbucket.

**Comment by EricWittmann** [comment]
Progress has been made on this.  Please see:  https://github.com/Apicurio/apicurio-studio/issues/391

**Comment by EricWittmann** [comment]
I have closed this issue because the only required change to **Apicurio** has now been made.  Namely the API URL for GitHub, GitLab, and Bitbucket are now configurable.  So if you're using a local installation of any of these systems, you can point Apicurio to it.  

Actually get everything working together requires configuration in Keycloak and GitLab/GitHub as well.  This may be non-obvious and so should be documented as an article in the list of Apicurio documentation.  That task will be tracked separately here:

https://github.com/Apicurio/apicurio-studio/issues/408
