### ISSUE TITLE
Apicurio docker-compose give me "Invalid parameter: redirect_uri"

### ISSUE THREAD

**Issue by euruba** [Apicurio/apicurio-studio#2094]
Hi, I tried to install Apicurio Studio with the docker-compose file and when I tried to login to http://IP:8093 I have the error "Invalid parameter: redirect_uri".

I detect that the redirect_url at web browser url field is pointing to http**s**://IP:8093, but the configuration for redirect_url on keycloak is fine.

Also if I change this configurations values on keycloack, the url_redirect on web browser field is still poiting to http**s**://IP:8093

Here is an example that my url look after load the http://IP:8093
`http://192.168.50.12:8090/auth/realms/apicurio/protocol/openid-connect/auth?response_type=code&client_id=apicurio-studio&scope=openid&redirect_uri=https%3A%2F%2F192.168.50.12%3A8093%2F&state=**************************`

I don´t change anything on configuration.

I only run:
1. ./setup.sh
2. ./start-mysql-environment.sh

I tried with latest-release and 2.58.Final with the same result.

Best regards

**Comment by euruba** [comment]
Ok, I just checked that is working with this versions, but not with latest one:
#APICURIO VERSION
APICURIO_API_VERSION=0.2.58.Final
APICURIO_WS_VERSION=0.2.58.Final
APICURIO_UI_VERSION=0.2.49.Final

**Comment by carlesarnal** [comment]
I have fixed the docker-compose distribution [here](https://github.com/Apicurio/apicurio-studio/pull/2167). In particular, the issue with the UI is that we were missing a mandatory property to not force https -> https://github.com/Apicurio/apicurio-studio/pull/2167/files#diff-db924a131bf00a5d1b814aba0ef2436a99ccf5c12a40037ff72d735eb69f1163R88.
