### ISSUE TITLE
studio.apicur.io logout does not work

### ISSUE THREAD

**Issue by tombgh** [Apicurio/apicurio-studio#2103]
Steps to reproduce:
1. Sign in to https://studio.apicur.io/ using username and password.
2. Logout.
3. I am redirected back to studio.apicur.io, still as signed in user.

It looks like studio-auth.apicur.io cookies are not cleared on logout from studio.apicur.io.

**Comment by carlesarnal** [comment]
We're aware of this and is already fixed in the linked PR but just not deployed yet.
