### ISSUE TITLE
Lost all my progress because apparently I was logged out but the editor didn't know

### ISSUE THREAD

**Issue by dcu** [Apicurio/apicurio-studio#211]

**Comment by EricWittmann** [comment]
That sucks - sorry for the headache.  Error handling is definitely one of the areas that wasn't ready yet.  I'll bump that up the priority list and get it included in the next release. :(

**Comment by dcu** [comment]
thanks, I'd be great if you could make the input field save when it loses focus

**Comment by dcu** [comment]
apparently it stops saving after getting `WebSocket is already in CLOSING or CLOSED state.`

**Comment by dcu** [comment]
@EricWittmann is there a way to reconnect the socket from the console so I don't lose my progress again?

**Comment by EricWittmann** [comment]
Which input field needs to be saved when focus is lost?

As for the websocket issue - yes if the WS drops then changes from there on will get lost.  I 100% have some work to do to ensure that the editor *at least* tells you when it has lost the connection.  That is step 1.  After that, the WS needs to try reconnecting whenever it gets disconnected.

Neither of these is particularly difficult - they just weren't done yet.  

I think I'm going to be feeling the pain of the accidental deploy for awhile.  :sadface:

**Comment by EricWittmann** [comment]
I'll spend some time today working on these things and hopefully I can get a new version out asap.

Thanks for testing and reporting problems.

**Comment by EricWittmann** [comment]
FYI I have pushed a new snapshot that implements step (1) above:  it will prompt you to reload if the websocket connection is lost for any reason.  This should prevent any loss of data by at least letting you know when the connection is gone.

A more nuanced solution including buffering the changes and attempts to reconnect will have to wait for a future release.

**Comment by dcu** [comment]
Thanks, it's good enough. I'll continue testing

**Comment by EricWittmann** [comment]
Since the editor will now warn you when you've lost the websocket connection (minimum error handling for usability) I'm closing this issue.  Additionally, I have created a new Issue to track a more advanced solution to this problem here:

https://github.com/Apicurio/apicurio-studio/issues/214
