### ISSUE TITLE
Downloaded file is not compatible with io-docs or openapi-viewer

### ISSUE THREAD

**Issue by dcu** [Apicurio/apicurio-studio#212]
I get an error while loading my API in: http://io-docs.herokuapp.com/
and it doesn't show everything when loading in: https://koumoul.com/openapi-viewer/

**Comment by EricWittmann** [comment]
Can you provide more detail?  What error do you see?  Can you share the API you are trying to load?  What's missing from the viewer?  etc.

**Comment by dcu** [comment]
hi, yes I just sent you an email with the file

**Comment by dcu** [comment]
it seems io-docs doesn't support openapi 3. koumoui loaded after adding the `servers` field and completing all descriptions

**Comment by EricWittmann** [comment]
So it sounds like we at least need to be able to edit the servers field.  I think there's an issue already in for that.  I also need to actually implement validation of OAI 3 documents.  Right now I've only implemented the rules for 2.  So many things to do. :)

**Comment by EricWittmann** [comment]
I think we've captured what needs to be improved in other tickets, so I'll close this for now.  If I'm wrong let me know and we can re-open.
