### ISSUE TITLE
postgresql image doesn't deploy correctly

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-studio#213]
Still having the issue described here
https://bugzilla.redhat.com/show_bug.cgi?id=1402257
with OpenShift v3.6.1

**Comment by EricWittmann** [comment]
Are you using the Apicurio openshift template found [HERE](https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-template.yml)?

**Comment by lucamaf** [comment]
yes, I'm also using OpenShift 3.6.1 with NFS

**Comment by EricWittmann** [comment]
So I guess there's a problem with the NFS configuration?  I'm not really an OpenShift expert.  I'm running the Apicurio config in the 3scale openshift staging cluster without issue.  Perhaps @maneta or one of the other ops guys can help?

Alternatively we can try modifying the config to use mysql instead of postgresql ... I can help with that if you want to try it.

**Comment by lucamaf** [comment]
So it runs with system admin privileges but the PGSQL process is killed automatically

**Comment by maneta** [comment]
@lucamaf looks like a openshift bug not a postgres image bug, the patch has been released on:

```
Ben Parees 2017-01-06 09:59:58 EST
Status: VERIFIED → CLOSED
Resolution: --- → CURRENTRELEASE
```

My recommendation would be to  update your cluster to the latest version. 

I will run this template on the `oc cluster up` version to see if I can reproduce it but It seems that this version is already patched.

**Comment by maneta** [comment]
I have tried to reproduce the error using `oc cluster up` versions:

```
OpenShift Master: v3.6.0+c4dd4cf
Kubernetes Master: v1.6.1+5115d708d7
```

The error was not reproducible. And it is working in our staging and production clusters. I will assume that it must be some corner case involving the version/configuration of the cluster used by @lucamaf
