### ISSUE TITLE
Apicurio Studio page loader spinning for-ever after login

### ISSUE THREAD

**Issue by sandeepsuvit** [Apicurio/apicurio-studio#2137]
Hi Team,

From today after i login to the application the application page just shows the loader page and isn't loading the application. Any thoughts around this? This happened multiple times for me.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/4330496/225211366-5d049e12-7c56-4b07-9a90-1e2c0c11a53c.png">

**Screenshot of the console**

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/4330496/225211580-29ac1ebc-2278-4659-9ab4-4aff9565a374.png">

**Comment by romilin** [comment]
Hi @sandeepsuvit 

This will be corrected with the PR #2132 :+1:

**Comment by andapony** [comment]
I've been getting the same problem for a couple of days now.  Same messages in the browser developer console as well.

**Comment by clabonte** [comment]
Same problem for me. I not able to use the online version (https://studio.apicur.io/) for a few days now because of this issue due to CORS errors (as seen in my dev console). Just tested again with v0.2.61.Final and got the same result

**Comment by EricWittmann** [comment]
@clabonte and @andapony is it still not working or is the CORS problem solved?  I cannot reproduce the problem either on studio.apicur.io.

If you're still getting the problem, could you let me know what browser you are using?

Also maybe try clearing your browser cache and reloading.

**Comment by andapony** [comment]
It's been working fine for me over the last several days.  Thanks!

**Comment by clabonte** [comment]
Working for me as well! Thanks for the excellent work on this great solution!

**Comment by berlinger-ciprianpetrisor** [comment]
@EricWittmann I'm hosting ApiCurio Studio in AWS, and upgraded to 0.2.61.Final [as suggested here](https://github.com/Apicurio/apicurio-studio/issues/1992#issuecomment-1485077143) to resolve the max frame size issue in 0.2.59, however now I receive a 403 error for all static resources.
![image](https://user-images.githubusercontent.com/95405175/228260885-4a4373c7-f7a3-488d-a84d-d8d1a5a464ba.png)

No other configuration changes have been made (using the same environment variables as in 0.2.59.Final).

I also tried configuring the CORS_ALLOWED_ORIGINS environment variable in hopes that it would fix the issue, but no success.

What is most odd is that logs do not display anything regarding these failed requests **and the UI works in Firefox.**

Chrome and Edge are both broken, though.

**Comment by EricWittmann** [comment]
Hi @berlinger-ciprianpetrisor - you likely need to set the `QUARKUS_HTTP_CORS_ORIGINS` environment variable to `*` in both the `-api` and **also** the `-ui` pods.  I don't know why it works in Firefox but not in Chrome, but we discovered the same thing and that was the fix.

In future releases this will not be necessary, but it is for 61.

**Comment by berlinger-ciprianpetrisor** [comment]
@EricWittmann 
Thank you very much, that seems to have fixed the problem!
