### ISSUE TITLE
apicurio-studio-api image container respond a 404 not found

### ISSUE THREAD

**Issue by Kignoux** [Apicurio/apicurio-studio#2154]
Hello,

I try to deploy apicurio-studio on a Kubernetes cluster following the documentation and the example provided in the github repository.

All the pods are starting without errors but it seems the apicurio-studio-api container is not accessible from the other components and respond a 404 not found code. Moreover setting the APICURIO_LOGGING_LEVEL variable to the value "debug" does not seem to work :/
For your information, the http requests go through an istio gataway virtualservice.

Would you have any idea what I am doing wrong ? 

Thanks a lot for the help

Here is the apicurio-studio-api deployment:
> apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-studio-api-deployment
  namespace: apicurio-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: apicurio-studio-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: apicurio-studio-api
    spec:
      containers:
      - env:
        - name: APICURIO_LOGGING_LEVEL
          value: "debug"
        - {name: APICURIO_DB_CONNECTION_URL, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: apicurio-db-connection-url}}}
        - {name: APICURIO_MICROCKS_API_URL, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: apicurio-microcks-api-url}}}
        - {name: APICURIO_MICROCKS_CLIENT_ID, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: apicurio-microcks-client-id}}}
        # - {name: APICURIO_MICROCKS_CLIENT_SECRET, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: apicurio-microcks-client-secret}}}
        - {name: APICURIO_KC_AUTH_URL, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: keycloak-url}}}
        - {name: APICURIO_KC_REALM, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: apicurio-kc-realm}}}
        - {name: APICURIO_KC_CLIENT_ID, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: apicurio-kc-client-id}}}
        - {name: APICURIO_SHARE_FOR_EVERYONE, valueFrom: {configMapKeyRef: {name: apicurio-studio-configmap, key: apicurio-ui-feature-share-with-everyone}}}
        - {name: APICURIO_DB_PASSWORD, valueFrom: {secretKeyRef: {name: apicurio-studio-secret, key: db-password}}}
        - {name: APICURIO_DB_USER_NAME, valueFrom: {secretKeyRef: {name: apicurio-studio-secret, key: db-user}}}
        - {name: APICURIO_KC_CLIENT_SECRET, valueFrom: {secretKeyRef: {name: apicurio-studio-secret, key: apicurio-kc-client-secret}}}
        - name: APICURIO_DB_DRIVER_NAME
          value: "postgresql"
        - name: APICURIO_DB_INITIALIZE
          value: "true"
        - name: APICURIO_DB_TYPE
          value: "postgresql9"
        - name: JAVA_TOOL_OPTIONS
          value: "-Djava.net.preferIPv4Stack=true -Djavax.net.ssl.trustStore=/trust/truststore.jks -Djavax.net.ssl.trustStorePassword=pwccasecret"
        image: 'apicurio/apicurio-studio-api:0.2.61.Final'
        name: apicurio-studio-api
        volumeMounts:
        - name: truststore
          readOnly: true
          mountPath: "/trust"
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: apicurio-studio-secret
        secret:
          secretName: apicurio-studio-secret
      - name: apicurio-studio-configmap
        configMap:
          name: apicurio-studio-configmap
      - name: truststore
        secret:
          secretName: apicurio-studio-truststore

The configmap looks like this:
> apiVersion: v1
kind: ConfigMap
metadata:
  name: apicurio-studio-configmap
  namespace: apicurio-studio
data:
  keycloak-url: http://keycloak.mydomain.com
  apicurio-ui-logout-redirect-uri: /
  apicurio-ui-hub-api-url: https://apicurio-studio.mydomain.com/studio-api
  apicurio-ui-editing-url: ws://apicurio-studio.mydomain.com/designs
  apicurio-microcks-api-url:  http://MICROCKS_URL/api
  apicurio-db-connection-url: jdbc:postgresql://apicurio-studio-db-service:5432/apicuriostudiodb
  apicurio-kc-client-id: apicurio-studio
  apicurio-kc-realm: apicurio
  apicurio-microcks-client-id: microcks-serviceaccount
  apicurio-ui-feature-share-with-everyone: "true"
  apicurio-ui-feature-microcks: "false"

Here are the services and virtualservices:
> apiVersion: v1
kind: Service
metadata:
  name: apicurio-studio-api-service
  namespace: apicurio-studio
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8080
  selector:
    app.kubernetes.io/component: apicurio-studio-api
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-studio-ui-service
  namespace: apicurio-studio
spec:
  ports:
  - name: "8093"
    port: 8093
    targetPort: 8080
  selector:
    app.kubernetes.io/component: apicurio-studio-ui
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-studio-ws-service
  namespace: apicurio-studio
spec:
  ports:
  - name: "8092"
    port: 8092
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/component: apicurio-studio-ws
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-studio-db-service
  namespace: apicurio-studio
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/component: apicurio-studio-db
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: apicurio-studio-virtualservice
  namespace: apicurio-studio
spec:
  gateways:
  - istio-system/apicurio-gateway
  hosts:
  - apicurio-studio.mydomain.com
  http:
  - match:
    - uri:
        # prefix: /studio-api
        regex: /studio-api/?(.*)
    route:
    - destination:
        host: apicurio-studio-api-service.apicurio-studio.svc.cluster.local
        port:
          number: 8091
  - match:
    - uri:
        prefix: /designs
    route:
    - destination:
        host: apicurio-studio-ws-service.apicurio-studio.svc.cluster.local
        port:
          number: 8092
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: apicurio-studio-ui-service.apicurio-studio.svc.cluster.local
        port:
          number: 8093

And finaly the errors:
![screen](https://user-images.githubusercontent.com/25176034/232733310-137b14c9-e0dc-4f8e-b9cc-e581654f9457.png)

log from the api container:
> Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/apicurio-studio-ui-runner.jar 
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true -Djavax.net.ssl.trustStore=/trust/truststore.jks -Djavax.net.ssl.trustStorePassword=pwccasecret
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jolokia.util.ClassUtil (file:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar) to constructor sun.security.x509.X500Name(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jolokia.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/deployments/lib/org.jboss.slf4j.slf4j-jboss-logmanager-1.2.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL https://192.168.3.122:8778/jolokia/
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-04-18 08:13:45,741 INFO  [io.qua.oid.com.run.OidcCommonUtils] (main) Connecting to OpenId Connect Provider for up to 30 times every 2 seconds
2023-04-18 08:13:47,091 INFO  [io.quarkus] (main) apicurio-studio-platforms-quarkus-ui 0.2.61.Final on JVM (powered by Quarkus 2.16.4.Final) started in 2.245s. Listening on: http://0.0.0.0:8080
2023-04-18 08:13:47,092 INFO  [io.quarkus] (main) Profile prod activated. 
2023-04-18 08:13:47,092 INFO  [io.quarkus] (main) Installed features: [cdi, oidc, security, servlet, smallrye-context-propagation, vertx]
2023-04-18 08:14:01,438 ERROR [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-12) State verification has failed, completing the code flow with HTTP status 401

**Comment by Kignoux** [comment]
Duplicate

**Comment by AustrofrioIoT** [comment]
Hey Friend how do you solve the problem I have the same  error so sad
