### ISSUE TITLE
Refresh token XHR Request 

### ISSUE THREAD

**Issue by romilin** [Apicurio/apicurio-studio#2188]
Hello @EricWittmann , 

The refresh token request failed with this logs on chrome : 
![token-apicurio-live](https://github.com/Apicurio/apicurio-studio/assets/118544135/cf8be96c-9f0b-4a35-9022-0da9b489802e)

The problem also exist on firefox, here is the logs i get : 
![firefox-token](https://github.com/Apicurio/apicurio-studio/assets/118544135/cf424979-cbac-4c23-b4de-f9dc5c8032cd)

I also have the problem when i use my local apicurio. It appears at the end of the token life. 
I tried to changes some settings on my keycloak but i can't solve the problem. 

Do you have any idea on how to correct that ?

**Comment by romilin** [comment]
Hello, 

I think the solution to this problem is not a keycloak settings. 

The "token" request doesn't have a preflight request such as "designs" request. Maybe adding this preflight for token will correct that bug ? 

What do you think about that ?

**Comment by romilin** [comment]
Hello, 

An update on this subject : 
I changed the token request to POST instead of GET and I got this : 
![image](https://github.com/Apicurio/apicurio-studio/assets/118544135/40982b3f-8bab-45de-9f69-09b0b0aa025e)

As u can see, the "Access-Control-Allow-Origin" is in the response headers. 

If I'm right, Quarkus Code Flow Redirect is use in the next request to keycloak. I tried to change this request to a POST too but still don't know how to do it. 
Here is the response to the preflight request without the headers I need : 
![image](https://github.com/Apicurio/apicurio-studio/assets/118544135/a24f0a30-2d85-4f2a-9339-df69fdac156f)


Any idea on how to make this "quarkus" request to do a POST instead of GET ?

**Comment by romilin** [comment]
Hello @EricWittmann 
Still no idea on how to correct that bug :disappointed: 

@carlesarnal : I saw your work in [QuarkusAuthenticationFilter](https://github.com/Apicurio/apicurio-studio/blob/master/platforms/quarkus/ui/src/main/java/io/apicurio/ui/QuarkusAuthenticationFilter.java) 
The solution might be there ? 

i just tried the live version of Apicurio, the bug is not corrected so users can't work more than 5 minutes (acces token lifespan duration in keycloak) without manual refresh. 

Any ideas ?

**Comment by carlesarnal** [comment]
@EricWittmann we should release a new version of Studio with this fix to the upstream version.
