### ISSUE TITLE
API Editor: Allow to import/upload OpenAPI 3.0 spec files

### ISSUE THREAD

**Issue by dcu** [Apicurio/apicurio-studio#219]
Now that we have the option to download it'd be great to have to option to upload the file.
At the moment, refactoring definition names is really painful and it'd be easier to just download, use a normal editor to update the names and then upload again.

Also, we can use it to share the file with other people until collaborative editing is done.

**Comment by EricWittmann** [comment]
Refactoring definition names is another good feature.  Refactoring in general is an area that is on the roadmap, but I'm not sure if there are any tickets created yet.  I'll create one for renaming definitions.

**Comment by EricWittmann** [comment]
Importing into Apicurio now supports:

* Importing from GitHub/GitLab/Bitbucket
* Importing from arbitrary URL (raw OAI content)
* Importing from copy/paste text or local file

Fixed as of this commit:  https://github.com/Apicurio/apicurio-studio/commit/5f8b64d1236ea45aacebc2640d441c7ce8b1b617

**Comment by EricWittmann** [comment]
Note that import does not allow you to replace the content of an API.  So for the use-case of refactoring definitions names, the workflow is still not ideal.  I don't have any plans to allow the full replacement of an API definition's source (at least not at the moment).

Instead, I would like to actually implement "Rename Definition". :)  I'll open another issue for that.
