### ISSUE TITLE
API Editor: Support pasting Swagger YAML file

### ISSUE THREAD

**Issue by gastaldi** [Apicurio/apicurio-studio#228]
It would be nice if we could just paste a Swagger YAML/JSON file when importing an API

**Comment by EricWittmann** [comment]
Similar to #219 ... perhaps upload/paste/import should all be folded into the same "Import API" functionality - just different options on the Import page.

**Comment by The-Alchemist** [comment]
As a workaround, is there a way to insert the YAML/JSON into the backend, maybe the database?

**Comment by EricWittmann** [comment]
You would need to insert a row in the api_designs table, the acl table, and the content table.  Off the top of my head. :)

**Comment by EricWittmann** [comment]
This has been implemented as of commit https://github.com/Apicurio/apicurio-studio/commit/5f8b64d1236ea45aacebc2640d441c7ce8b1b617

This also means that there is API support for importing/creating a new API - so inserting in the DB directly should not be needed:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/rest/IDesignsResource.java#L57-L60

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/main/java/io/apicurio/hub/api/beans/ImportApiDesign.java

The endpoint is `/designs` with a REST method of `PUT`.  The request body should be something like this:

```json
{
    "data": "<BASE64_DATA>"
}
```

The data sent should be the raw OpenAPI/Swagger document (either JSON or YAML) but base64 encoded.
