### ISSUE TITLE
Incorrect array types in generated swagger file

### ISSUE THREAD

**Issue by noelo** [Apicurio/apicurio-studio#230]
version: 0.2.2.Final
swagger-codegen-maven-plugin:2.2.3

Not sure if this is a apicurio or a swagger-codegen issue 

I created a type and then an api definition which appears in the swagger file as 
  ```
/customers/{custId}/applications/:
    get:
      description: Get applications list
      responses:
        200:
          description: Applications List
          schema:
            type: array
            items:
              type: '#/definitions/ApplicationType'
```

However in swagger-code-gen this gives the following core dump

```
[WARNING] null(array property) does not have a proper inner type defined
[ERROR] unexpected missing property for name response
[WARNING] skipping invalid array property {
 .....SNIP FOR BREVITY....
}
[ERROR] unexpected missing property for name response
[ERROR]
java.lang.RuntimeException: Could not process operation:
  Tag: default
  Operation: null
  Resource: get /customers/{custId}/applications/
  Definitions: {AssessmentType=io.swagger.models.ModelImpl@fc1ee440, CustomerType=io.swagger.models.ModelImpl@e9db3eae, ApplicationType=io.swagger.models.ModelImpl@d07874b7}
  Exception: null
    at io.swagger.codegen.DefaultGenerator.processOperation (DefaultGenerator.java:861)
    at io.swagger.codegen.DefaultGenerator.processPaths (DefaultGenerator.java:761)
    at io.swagger.codegen.DefaultGenerator.generateApis (DefaultGenerator.java:388)
```

Changing the swagger file to use a type reference rather than a type seems fix the issue
```
/customers/{custId}/applications/:
    get:
      description: Get applications list
      responses:
        200:
          description: Applications List
          schema:
            type: array
            items:
              $ref: '#/definitions/ApplicationType'
```

**Comment by EricWittmann** [comment]
How did this line get created?  

```
type: '#/definitions/ApplicationType'
```

Was it apicurio that created that?  If so, I think that's likely to be the bug.

**Comment by noelo** [comment]
Yes everything was generated via the UI. The types were selected via the types dropdown element

**Comment by EricWittmann** [comment]
OK in that case there is a bug in Apicurio - the reference to `ApplicationType` should definitely be a `$ref` rather than a `type`.  I'll have a look asap - likely to be a very simple fix.

**Comment by noelo** [comment]
Cheers thanks, great app BTW.

**Comment by EricWittmann** [comment]
OK good news is that I've reproduced the error.  Definitely an editor bug.  Interestingly it's isolated to Swagger/OpenAPI 2.0.  When using OpenAPI 3.0 it works.

**Comment by EricWittmann** [comment]
Fixed:  https://github.com/Apicurio/oai-ts-commands/commit/e121b464539686e2db4c9c6204de9db76378c6e4

**Comment by EricWittmann** [comment]
Fix for this will be included in the next release.
