### ISSUE TITLE
API Editor: Support for Security Schemes & Security Requirements

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#244]

**Comment by Nessworthy** [comment]
I think this is the closest related issue I can tag on to here! A fantastic bit of software, by the way!

Exporting shows the added security schemes in the shared components, but there's nowhere these can be applied. Although defined, [they currently do nothing mechanically][3]:
> All objects defined within the components object will have no effect on the API unless they are explicitly referenced from properties outside the components object.

Security schemes can be applied to the [global][1] and [operational][2] level, but the app doesn't support either at the moment. It would be useful to add this functionality in, particularly for schemes which provide scopes to indicate what scopes are required for specific operations.

[1]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#openapi-object
[2]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operation-object
[3]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#components-object

**Comment by EricWittmann** [comment]
Good progress on this.  Will be done and released this week.  FYI.

**Comment by EricWittmann** [comment]
Done and released. :)
