### ISSUE TITLE
Design window not rendering properly after API import

### ISSUE THREAD

**Issue by ashish-bhatt** [Apicurio/apicurio-studio#259]
After successful API import, design window doesn't render properly and make it unusable for the user. Please find the screenshot attached. 
![screen shot 2018-03-07 at 11 41 16 am](https://user-images.githubusercontent.com/6506028/37088128-99bb3a2c-21fc-11e8-8f5e-003f44fe5d0e.png)

**Comment by EricWittmann** [comment]
Well it's clear that we know what's wrong!  Sadly that information is not bubbled up to the UI.

Note that you can work around this issue (for this particular API) by changing the OAI version from `2` to `2.0`.  I'm guessing you already figured that out, but just in case. :)

Thanks for the report!
