### ISSUE TITLE
Response is shown prior to Request in PUT action

### ISSUE THREAD

**Issue by kkk-f17** [Apicurio/apicurio-studio#263]
Hi, in the 'PUT' action, response body is shown prior to request body in the source. Help us to fix this issue. Below is the sample code.
-------------------------------------------
```
put:
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: string
                    examples:
                        updateResponse:
                            value:
                                success: 'true'
                                message: 'Account updated Successfully'
    requestBody:
        content:
            application/json:
                examples:
                    'Update account':
                        value:
                            id: '12345'
                            accountName: 'Always welcome'
                            accountBranch: HYD
        required: true
```

**Comment by EricWittmann** [comment]
Hm.  You are right.  That's a problem with the data model serializer.  I thought I had them all in specification order but not for this one.  I'll need to go back and verify all of them.

I'll get this fixed soon.

Note, however, that the order doesn't matter from a tooling or documentation generation perspective.  It only matters when you look at/edit the source directly.  

That said, it should still get fixed.

Thanks for the report.

**Comment by EricWittmann** [comment]
OK I've fixed this problem in the data model serializer and have gone through the spec to make sure there weren't any other similar property-ordering problems.  I found a couple of other trivial ones and fixed those as well.

You'll see this fix in the next version of Apicurio.

**Comment by EricWittmann** [comment]
Fixed by this commit: https://github.com/Apicurio/oai-ts-core/commit/4fa286f9499da8186c28365a5ae10a2c968da081
