### ISSUE TITLE
Having funny UI behavior when using Grammarly extension in the browser 

### ISSUE THREAD

**Issue by AuroraBrignola** [Apicurio/apicurio-studio#266]
I've noticed that when using the Live Version of the Studio in a browser that has got the Grammarly extension active, the small buttons for saving and canceling a description disappear (see picture below).

![image](https://user-images.githubusercontent.com/11420967/37654429-ee527ba8-2c39-11e8-8c0c-8ecc3264cbaf.png)

And here's a picture of this working fine when Grammarly is not active: 
![image](https://user-images.githubusercontent.com/11420967/37654412-dc25db46-2c39-11e8-8387-5c0f5af09276.png)

Not a big deal, I know, just wanted to make you guys aware of this :) I've just started using the Studio and looks great, very promising. I will introduce it to my team and we will most likely start using it for designing our APIs.

**Comment by EricWittmann** [comment]
Thanks for the report.  I'll have a look at some point and see if there's an easy fix for this.

Looks like you need to add some descriptions to your API!  ;)
