### ISSUE TITLE
OpenShift: Internal / External URLs

### ISSUE THREAD

**Issue by pixie79** [Apicurio/apicurio-studio#277]
Hi,

I have been looking at the OpenShift configuration template and attempted to load it into my Minishift cluster. Everything went well until I attempted to login.

It appears that all the external redirects work ok, the UI bounces me to Keycloak where i can register and then get bounced back to the UI. That is where the problems start.

Using the standard template I get blocked at that point as the UI can not internally reach keycloak and verify the token. If i switch the endpoint from example.com to namespace.svc.cluster.local with the port of 8080, then with a bit of fiddling i can get Keycloak to create the account and the UI can talk to keycloak. But the Return URL is incorrect.

[org.keycloak.adapters.OAuthRequestAuthenticator] (default task-29) failed verification of token: Invalid token issuer. Expected 'http://apicurio-studio-auth:8080/auth/realms/apicurio' , but was 'https://apicurio-studio-auth.dev-system.svc.cluster.local/auth/realms/apicurio' 

Some how we need the UI to redirect using the external domain URL's so that calls from the browser work but internally inside the cluster we either need the external URL to resolv (which it currently does not) or we need to be able to reference the internal URL / port??

I guess the best option would be if the routers were also resolvable internally.

Mark

**Comment by EricWittmann** [comment]
As this issue is over a year old, I'm going to close it.  If anyone is still having issues with OpenShift, please feel free to re-open this.
