### ISSUE TITLE
API Editor: support body for Patch method

### ISSUE THREAD

**Issue by fponticelli** [Apicurio/apicurio-studio#285]
According to (MDN)[https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH] the PATCH method should support a body, instead, the editor signals an error `OP-3-003`:

```
The "requestBody" property is only supported for POST, PUT, and OPTIONS operations.
```

**Comment by EricWittmann** [comment]
You are correct.  :)  I will fix it asap.

**Comment by EricWittmann** [comment]
Fixed in:  https://github.com/Apicurio/oai-ts-core/commit/bedc2a9380eb60b26bde79a479f52ba2d0fedde2
