### ISSUE TITLE
UX: Update Rename Definition dialog with dialog treatment

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#299]
See the Rename Definition treatment and make appropriate changes to impl.

**Comment by EricWittmann** [comment]
@Mgranfie do you have a link to the treatment you did for Rename Definition?

**Comment by Mgranfie** [comment]
Sure thing, here you go:

https://redhat.invisionapp.com/share/AGLG0C2PM5B#/298104291_B_Create_Definition_Intro
