### ISSUE TITLE
KeyCloak for use with Apicurio

### ISSUE THREAD

**Issue by EmanShaaban** [Apicurio/apicurio-studio#305]
I tried to set Keycloak to be used with Apicurio
I followed the instruction in https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio
First I configured KeyCloack  with URL ---> http://localhost:8180
![screenshot from 2018-05-05 22 23 41](https://user-images.githubusercontent.com/2835223/39667290-122293f4-50b3-11e8-847b-b472e3f96568.png)
and then configured Apicurio  with this settings
 <property name="apicurio.kc.auth.rootUrl" value="http://localhost:8080/auth"/>
 when running Apicurio with the command 
 ./bin/standalone.sh -c standalone-apicurio.xml -Djboss.socket.binding.port-offset=100

The Apicurio URL is not working
![screenshot from 2018-05-05 22 30 21](https://user-images.githubusercontent.com/2835223/39667353-215e654a-50b4-11e8-865d-b6a436753ccb.png)

**Comment by EricWittmann** [comment]
Running Apicurio with that command will start it up running on port 8180, so to access Apicurio you would need to go here:

http://localhost:8180/studio

From there it should redirect you to Keycloak for authentication.  Once authenticated you should get redirected back to Apicurio.

At what point in this process are you seeing the failure?

**Comment by EmanShaaban** [comment]
when I went to 
http://localhost:8180/studio
I get redirected to
http://localhost:8080/auth/realms/apicurio/protocol/openid-connect/auth?response_type=code&client_id=apicurio-studio&redirect_uri=http%3A%2F%2Flocalhost%3A8180%2Fstudio%2F&state=1a655b91-e148-4593-b9b5-752449b5596c&login=true&scope=openid
which does not open
![screenshot from 2018-05-05 22_30_21](https://user-images.githubusercontent.com/2835223/39671724-4b30207e-511e-11e8-9635-9e42b9cb9fa8.png)

**Comment by EricWittmann** [comment]
Do you have Keycloak running on localhost on port 8080?

**Comment by EmanShaaban** [comment]
I was running Keycloak on different port
I changed keycloack to same ports as Apicurio and no 
http://localhost:8180/studio
redirect to
![screenshot from 2018-05-06 17 02 16](https://user-images.githubusercontent.com/2835223/39675120-f0aa1eb4-5156-11e8-882d-acd130dab135.png)

**Comment by EricWittmann** [comment]
OK this indicates that Apicurio is trying to authenticate using a Client ID that has not been added to Keycloak.  The actual client-id it's trying to use can be found in the URL, but the window was too small to see it.  You could copy/paste that URL here so we can double-check.

Did you import the Realm settings as the instructions indicate?  If so, you can log into Keycloak and make sure that there is a `apicurio-studio` client defined in the `apicurio` realm.

**Comment by eman-shaaban-akad** [comment]
Here is the URL
http://localhost:8080/auth/realms/apicurio/protocol/openid-connect/auth?response_type=code&client_id=apicurio-studio&redirect_uri=http%3A%2F%2Flocalhost%3A8180%2Fstudio%2F&state=1edb2d03-e3a5-4f97-af53-2c949b6cd263&login=true&scope=openid
I noticed that I can not import the Realm file 
![screenshot from 2018-05-07 15 35 46](https://user-images.githubusercontent.com/5568887/39704881-11ac58a0-520d-11e8-9223-ff8ca89a34ef.png)

**Comment by EricWittmann** [comment]
Ah ok - so if you don't import the realm file then you won't have any of the appropriate settings in the realm (like the required clients).  

Why are you unable to import the realm file?  What version of Keycloak are you using?

**Comment by EricWittmann** [comment]
Did you follow these instructions regarding the realm.json from the article?

> After downloading that file, click the Select file button on the Add realm page in Keycloak, then choose the realm.json file you just downloaded. After selecting the realm.json file, you should be able to click the Create button.

If so, was there an error of some sort?  I'll try downloading KC again and trying it myself to make sure.

**Comment by eman-shaaban-akad** [comment]
yes i follow ale the instructions regarding the realm.json, but I'm unable to import the file.

**Comment by EricWittmann** [comment]
I just tried this - downloaded the latest keycloak and ran through the instructions.  The realm.json file import worked just fine.  Here is a video of me doing that:

![ezgif-4-58c25334c7](https://user-images.githubusercontent.com/1890703/39729964-a2a30c54-522c-11e8-8f7d-d4f6c764e64a.gif)

**Comment by eman-shaaban-akad** [comment]
I tried to import the realm.json file with the following versions with no success:
keycloak-3.3.0.Final.zip  
keycloak-4.0.0.Beta2.zip
keycloak-3.4.3.Final.zip
I guess the issue in the json file.
I searched for a replacement but I id not find

**Comment by EricWittmann** [comment]
can you post the exact json file you have been trying to import?

Also what precisely happens when you try the import?
