### ISSUE TITLE
Unable to save API

### ISSUE THREAD

**Issue by upolymorph** [Apicurio/apicurio-studio#307]
I have created an account and linked this account with a bitbucket account however when I create an API I am not asked where to save the API and thus not able to save changes.
Please see the attached screenshot
<img width="1241" alt="screen shot 2018-05-23 at 19 22 49" src="https://user-images.githubusercontent.com/21140558/40440651-edccd2d4-5ebe-11e8-956e-7fabd82de68c.png">
Thanks to advise.

**Comment by EricWittmann** [comment]
Sorry for the confusion.  The current version of Apicurio no longer REQUIRES a linked Git account.  We now store the API in the Apicurio database.  So any changes you make are automatically saved as you work.  At any time you can choose to "Publish" the API into Bitbucket.  This can be done from the API Details page (not from the editor) using the drop-down menu.

![image](https://user-images.githubusercontent.com/1890703/40445863-65816b92-5e9b-11e8-911e-f5b1c237ad12.png)
