### ISSUE TITLE
Update to OpenUnirest (or remove Unirest entirely)

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#309]
We use the unirest http client in some places (from mashape).  Upgrade to the new open version:

https://github.com/OpenUnirest/unirest-java

**Comment by EricWittmann** [comment]
Related to: https://github.com/Apicurio/apicurio-studio/issues/741

**Comment by tarabost** [comment]
I guess this can be closed now, as the unirest version was bumped to 3.14.1.
