### ISSUE TITLE
Cannot publish to Gitlab project that is not inside a group

### ISSUE THREAD

**Issue by patrickceg** [Apicurio/apicurio-studio#311]
<h2>Environment:</h2>
Edge browser on Windows 10 Version 1803

<h2>Prerequisites:</h2>

<ul>
<li>You have a "personal project" in GitLab that has not been added to any group</li>
<li>You have some API that you can test publishing with</li>
</ul>

<h2>Steps to reproduce:</h2>

<ol>
<li>Link a GitLab account to Apicurio Studio through Settings -> Linked Accounts</li>
<li>Create a project in GitLab (not sure if it matters but I made it public - the one I created for this is https://gitlab.com/patrickceg/apicurio-test-project)</li>
<li>Return to the Apicurio Studio tab or window, and select the API that you created.</li>
<li>Click on the "..." beside the API and select "Publish"</li>
<li>On the <em>Publish API "myapi"?</em> prompt, select the GitLab icon under "Publish To*"</li>
<li>Attempt to select your project that isn't part of a group</li>
</ol>

<ul>
<li>Expected results: You should be able to select the project and upload the API to the GitLab repository</li>
<li>Actual results: The "Group" is an empty prompt, and the projects are also an empty prompt. You cannot proceed in the UI.</li>
</ul>

<img alt="Screenshot with empty Group and Project prompts" src="https://github.com/patrickceg/issues-assets/raw/master/apicurio_nogroup_gitlab.png"/>
<br/>
(EDIT: Switched the whole thing to HTML tags because markdown wasn't working...)<br/>

**Comment by EricWittmann** [comment]
Thanks for the report.  I assume that `patrickceg` is **not** an option in the **Group** drop-down?  Functionally that should be an option and then you should be able to pick `apicurio-test-project` after that.

**Comment by patrickceg** [comment]
I just tried this today and the group drop down is a blank stub - the 'menu' is the white rectangle in this screenshot:

<img alt="Group menu is blank" src="https://github.com/patrickceg/issues-assets/raw/master/apicurio_publish_nogroup_groupui.png"/>

Last time, I also tried making a group, which did show up (so the workaround currently seems to be making everything as a group), however I still can't select projects that are not part of any group.

**Comment by EricWittmann** [comment]
OK then this is definitely a bug.  Thanks for the report - will get to it asap.

**Comment by EricWittmann** [comment]
In the next version of Apicurio this will be fixed/working.  The version will be Beta 2.13 (**0.2.13.Final**).
