### ISSUE TITLE
User Interface Development

### ISSUE THREAD

**Issue by ManpreetGulati** [Apicurio/apicurio-studio#312]
Under the documentation(https://apicurio-studio.readme.io/v0.1.10/docs/setting-up-a-development-environment) to set up the development environment, The instructions to setup UI development environment has the following step:  Within APICURIO_STUDIO_SRC/front-end/app run yarn install.  
No app folder is present in the source code under the front-end folder.

**Comment by EricWittmann** [comment]
Ah thanks!  The docs got a bit stale.  I'll update them.

**Comment by EricWittmann** [comment]
I've updated the docs.  I think the rest of the info is still up to date.  The only issue was that the "app" folder was basically renamed "studio".  (In reality the entire UI was re-initialized using the latest angular version, hence the change of folder name)

Thanks again!
