### ISSUE TITLE
Linked Account : Provision for linking a github enterprise product

### ISSUE THREAD

**Issue by rohitdev** [Apicurio/apicurio-studio#313]
We have an on premise github enterprise product and dont use cloud based.
It would be great if their is a provision to provide integration with such products as it will allow such editions of git to work seamlessly without casuing friction in the existing ecosystem and also help in apicur adoption.

**Comment by EricWittmann** [comment]
Yes this would be a great improvement.  Information about this enhancement request is already being tracked here:  https://github.com/Apicurio/apicurio-studio/issues/206

Closing this issue as a duplicate, please track #206 instead. :)
