### ISSUE TITLE
API Editor: Allow rename path

### ISSUE THREAD

**Issue by ceefour** [Apicurio/apicurio-studio#315]
Currently I have to clone the path then delete the former.

Related to #220.

**Comment by EricWittmann** [comment]
Yeah that's a pretty stunning omission isn't it?  I'll add that action asap.

**Comment by ceefour** [comment]
Thank you @EricWittmann ! 👍

**Comment by EricWittmann** [comment]
This will be available in the next release of Apicurio.  In addition to renaming the path itself, all sub-paths will (optionally) be renamed.  Also if there are changes to the path parameters, those will be renamed as well.

So for example, let's say your API has the following paths:

- /resources
- /resources/{resourceId}
- /resources/{resourceId}/widgets
- /resources/{resourceId}/widgets/{widgetId}

If you rename `/resources` to `/capabilities`, and you choose to **also rename sub-paths**, then the result will be:

- /capabilities
- /capabilities/{resourceId}
- /capabilities/{resourceId}/widgets
- /capabilities/{resourceId}/widgets/{widgetId}

Then, you could rename `/capabilities/{resourceId}` to `/capabilities/{capabilityId}` and get this:

- /capabilities
- /capabilities/{capabilityId}
- /capabilities/{capabilityId}/widgets
- /capabilities/{capabilityId}/widgets/{widgetId}

Additionally, if the `resourceId` path parameter was defined in any of those last three paths, they will be renamed to `capabilityId` automatically.

**Comment by EricWittmann** [comment]
Sorry it took so long to get around to this. :)

**Comment by ceefour** [comment]
Wow that is so much more than what I could have asked for! 😎
