### ISSUE TITLE
Charset issue while importing api design from url

### ISSUE THREAD

**Issue by allanic79** [Apicurio/apicurio-studio#325]
Some texts become messy when an API design is imported from URL. It seems that URL stream is not encoded by utf-8.

**Comment by EricWittmann** [comment]
Thanks for the report.

Any chance you have a sample URL that reproduces the problem?

**Comment by allanic79** [comment]
I attached the spec file for I have no Internet URL for it. The file contains some Chinese characters encoded by UTF-8.


[jp_openapi.yaml.txt](https://github.com/Apicurio/apicurio-studio/files/2161692/jp_openapi.yaml.txt)

**Comment by EricWittmann** [comment]
OK great thanks.  I'll give it a look soon.

**Comment by EricWittmann** [comment]
Thanks for the bug report, @allanic79 - this will be fixed in the next release.
