### ISSUE TITLE
buttons are covered by the table design

### ISSUE THREAD

**Issue by hguerrero** [Apicurio/apicurio-studio#332]
When adding examples summary and description, the tick and cross buttons are covered by the table. 
![image](https://user-images.githubusercontent.com/1001939/42249894-5c3ffd5a-7ef3-11e8-8fb1-dd515a4aa6be.png)

**Comment by EricWittmann** [comment]
What browser is this?

**Comment by hguerrero** [comment]
Chrome for Mac OS in incognito mode

![image](https://user-images.githubusercontent.com/1001939/42459897-496bed10-8362-11e8-8e01-265080291495.png)

**Comment by EricWittmann** [comment]
This should be fixed in the next release, for all description fields (I think). :)
