### ISSUE TITLE
Downloading designs get a 500 error - Openshift

### ISSUE THREAD

**Issue by pszuster** [Apicurio/apicurio-studio#334]
When trying to download an API as JSON/YAML/Project in an Openshift deployment, I get a 500 error. I believe it is related to the fact that routes are created using HTTPS with self-signed certificates, and DownloadServlet fails to invoke the HubApiUrl because they are not trusted.

**Comment by EricWittmann** [comment]
Yes you nailed the reason I think.  For now the only workaround is to
either fox the SSL certs or use HTTP routes instead.  Next week I'll add a
fix for this.

**Comment by pszuster** [comment]
Yes, it works using http routes for all the containers (except keycloak)
