### ISSUE TITLE
Behind reverse proxy /api-hub/designs returns 403

### ISSUE THREAD

**Issue by gigaga** [Apicurio/apicurio-studio#339]
Hi,

Currently, if I work directly on Apicurio instance, I am able to create a new API. The request http://localhost:8080/api-hub/designs returns 200.

If I try to work on the same Apicurio instance but by using a reverse proxy (apache), I am not able to create a new API. The request http://localhost:8080/api-hub/designs returns 403.

Thanks

**Comment by gigaga** [comment]
By reexecuting the same request from curl I get the same 403 error.
If I remove "Origin" header of request, It's work!

**Comment by EricWittmann** [comment]
This is my favorite kind of issue!  :)

**Comment by gigaga** [comment]
:)
