### ISSUE TITLE
Issue - Forbidden

### ISSUE THREAD

**Issue by gigaga** [Apicurio/apicurio-studio#356]
Hi,

From my fork I built a 0.2.13-SNAPSHOT release. Started in localhost, there is no problem.
Started in my cluster, I able to authenticated my-self but after redirections (openId connect standard), I arrive to a Forbidden page in Apicurio (see my screenshot)
![capture](https://user-images.githubusercontent.com/6095992/43141877-5531d924-8f57-11e8-8ed8-5f648d502633.PNG)
.

Can you explain how fix it? I don't understand because from your 0.2.12-Final release, with the same configuration, there is no problem.

**Comment by gigaga** [comment]
In Apicurio logs, we can see a "redirect_uri" problem but nothing was changed in my configuration between my 0.2.13-SNAPSHOT and your 0.2.12-Final. Furethermore, I am able to be authenticated (so, redirect_uri is valid)...
![capture](https://user-images.githubusercontent.com/6095992/43142560-fd701e7e-8f58-11e8-97e2-af785136c7e1.PNG)

**Comment by EricWittmann** [comment]
So it's failing trying while trying to invoke the Keycloak token endpoint to convert the auth code into a JWT (if I understand correctly).  The error is being generated in Keycloak here:

https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L328-L331

I'm sorry but without more details about your configuring I'm not sure what the specific problem might be.  You could export your `realm.json` settings from Keycloak and post them along with your `standalone-apicurio.xml`.  Can't promise anything but would be happy to have a look.

**Comment by gigaga** [comment]
Ugh!. In fact, between 0.2.12 and 0.2.13 (master), modules/add-ons/keycloak was changed from 3.2.1 to 4.1.0.
If I downgrade in my quickstart to go back to 3.2.1 release, it's work...

**Comment by EricWittmann** [comment]
Ah yes - sorry about that - I've upgraded Keycloak to 4.1.0.  What version of Keycloak were you using when you encountered the Forbidden error?

**Comment by EricWittmann** [comment]
I'll try this on another operating system just to be sure.

In the meantime, can you guys (@gigaga and @SarvaniVarma) try again but with a different browser, or perhaps your existing browser in Private/Incognito mode.  I want to rule out the possibility that there is a cached token or something.

**Comment by gigaga** [comment]
No, in fact, you have to try to access to Apicuio through a reserve proxy. Without reverse proxy, it's work.

With the following configuration (where toto is declared in hosts file and corresponds to 127.0.0.1)
```
<VirtualHost toto:80>
    ProxyPreserveHost On
    RemoteIPHeader X-Forwarded-For
    ProxyPass "/"  "http://localhost:8080/"
    ProxyPassReverse "/"  "http://localhost:8080/"
</VirtualHost>
```

With add-on keycloak 4.1.0-Final --> Forbidden page (after authentication successful. when Keycloak try to get token from code, OAuthRequestAuthenticator class, resolveCode method,  invokeAccessCodeToToken call)
With add-on keycloak 3.2.1-Final --> It's work like a charm :)

**Comment by EricWittmann** [comment]
OK so the problem is with the combination of reverse proxy *and* Keycloak version 4.1.0.Final - correct?

If that's correct, would you be willing to try Keycloak 3.4.0.Final?  If that works then perhaps we can (temporarily) revert to that version (the last 3.x release).

**Comment by EricWittmann** [comment]
@SarvaniVarma - are you also using a reverse proxy?

**Comment by gigaga** [comment]
Ok, I'm going to try :)

**Comment by SarvaniVarma** [comment]
No, we are not using reverse proxy.

**Comment by gigaga** [comment]
Below, my tests with several releases of Keycloak.

- 3.2.1 --> OK
- 3.4.0 --> OK
- 3.4.1 --> OK
- 3.4.2 --> KO
- 3.4.3 --> KO
- 4.1.0 --> KO

**Comment by EricWittmann** [comment]
Wow that's very interesting!  Thanks for doing that legwork.

@SarvaniVarma - can you try doing a local build of Apicurio using Version 3.4.1.Final of Keycloak and trying out the resulting Quickstart?  Instructions for doing that:

1. Change this line to be version `3.4.1.Final` : https://github.com/Apicurio/apicurio-studio/blob/master/pom.xml#L118
2. Do a `mvn clean install` in the root of the **apicurio-studio** project
3. A new quickstart ZIP will be built and you can find it in `apicurio-studio/distro/quickstart/target`
4. Copy to a temp location and unzip the newly built quickstart and give it a try!

**Comment by SarvaniVarma** [comment]
Okay, will try it now.

**Comment by SarvaniVarma** [comment]
I changed the version to 3.4.3.Final in pom.xml and followed the process, Application is working now.

**Comment by EricWittmann** [comment]
You used 3.4.3.Final ?  That adds to my confusion. :(

**Comment by EricWittmann** [comment]
I guess we can revert to 3.4.1.Final until we sort out the root cause.

**Comment by gigaga** [comment]
I found!
In standalone-apicurio.xml, for http-listener node, if I change proxy-address-forwarding="true" to false, it's work...!

**Comment by EricWittmann** [comment]
Excellent!  So now you're working OK with 4.1.0.Final?

If so I wonder why @SarvaniVarma couldn't get that version working w/out a proxy in place. :(
