### ISSUE TITLE
Feature: Provide a way to quickly create a CRUD resource

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#368]
This would be something that would let users specify a data type (schema) and would then automatically generate all of the standard REST/CRUD operations and whatnot for that type.

For example, the user could specify the name of the resource **Foo** and the editor would automatically add the following:

* "Foo" schema definition
* /foos GET, POST
* /foos/{fooId} GET, PUT, DELETE

**Comment by Mgranfie** [comment]
UI Requirements
Provide Name and the resources are generated based on this.
Ability to create one at at time.
If a mistake is made, manual editing will be used. Undo would reverse any entries made and user can restart.
