### ISSUE TITLE
Is there a way to add reusabel headers, responses, ... ?

### ISSUE THREAD

**Issue by vnalla** [Apicurio/apicurio-studio#390]
Is there a way to define reusable components like headers, requestBody, responses, links, ...

**Comment by EricWittmann** [comment]
Not yet.  The editor does not yet have full spec coverage - and that is one of the areas where it is weak.  Right now there is only support for re-usable schema definitions.

**Comment by EricWittmann** [comment]
There are individual GitHub issues for each of these things:

#240 #241 #242 #243 #245 #246
