### ISSUE TITLE
issues with deployment of template in OpenShift 3.9.31

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-studio#393]
Everything seems to be going fine when applying the template until I received an error from the apicurio-studio-api pod:
```
2018-08-08 20:59:42,598 ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0403: Unexpected failure during execution of the following operation(s): [{
    "operation" => "add",
    "address" => ("deployment" => "apicurio-studio-api.war"),
    "runtime-name" => "apicurio-studio-api.war",
    "enabled" => true,
    "persistent" => true,
    "content" => [{"hash" => bytes {
        0x03, 0x64, 0x08, 0xf3, 0x5f, 0x0b, 0x74, 0x50,
        0x13, 0x8d, 0x20, 0x71, 0x16, 0x9c, 0xfe, 0xcd,
        0x68, 0x68, 0xd7, 0xf7
    }}],
    "operation-headers" => {"blocking-timeout" => 300}
}]: java.util.concurrent.RejectedExecutionException: Task org.jboss.as.controller.notification.NotificationSupports$NonBlockingNotificationSupport$1@56263945 rejected from java.util.concurrent.ThreadPoolExecutor@6ca99353[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 54]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
```

Not sure what could cause this...

**Comment by EricWittmann** [comment]
Any chance you can post the full server log?

**Comment by lucamaf** [comment]
attached
[apicurio-studio-api-2-6t2l6.log](https://github.com/Apicurio/apicurio-studio/files/2273498/apicurio-studio-api-2-6t2l6.log)

**Comment by lucamaf** [comment]
Thank you Eric, the environment is it under my control so I didn’t know about this limit.

**Comment by EricWittmann** [comment]
The Apicurio openshift template has some limits it imposes on the various pods.  For example:

https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-template.yml#L884-L888

However, we weren't actually putting any -Xmx limits on the java process itself.  The result is that the amount of memory that the apicurio java processes were actually taking up was highly variable based on the OpenShift environment/configuration.  So we added -Xms and -Xmx settings for all Apicurio java processes.  In the next release, both the Openshift memory limits **and** the java limits can be configured when using the template to install Apicurio.  And the default values for all these limits are sensible. :)

Until the next release is done, you can work around this issue either by increasing the Openshift memory limits or by using unreleased (snapshot) Apicurio docker images.

By the way - this all assumes that I've successfully guessed your problem, but I think it's likely.  We just ran into this same problem in another OS environment.

**Comment by EricWittmann** [comment]
I'm going to assume we're all set on this issue, so will close it.  If I'm wrong please go ahead and re-open it!  :)
