### ISSUE TITLE
Examples should always be stored as strings?

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#399]
I think when adding examples, Apicurio is storing the value as an object if the data provided is in JSON format, and otherwise stores it as a string.

Perhaps we should always store it as a string to avoid confusion.

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-studio/commit/055cf689dbd0f3e57bb31d9d0ab84bde03dd4f11

**Comment by null-dev** [comment]
I've noticed that examples are showing up quoted in the "Live Documentation" ReDoc. A ReDoc user encountered a similar issue here: https://github.com/Rebilly/ReDoc/issues/205 . The solution is to store the example as an object.

The OpenAPI 3 specification also backs this up: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject

Thus, I believe this fix may have actually been a regression, can we revert it?

**Comment by EricWittmann** [comment]
Yes I've had some feedback recently from users that storing the examples as strings is not working out well.  I honestly can't remember what **problem** this particular issue was trying to solve.  So I'll try to take another swing at examples, storing them as objects when possible and strings only if not.

**Comment by EricWittmann** [comment]
It would be great if @null-dev you could open a new issue for this?
