### ISSUE TITLE
Linking External Documents

### ISSUE THREAD

**Issue by kevin-thompson** [Apicurio/apicurio-studio#401]
There should be a way to link documents together. OpenAPI provides for external references (even to documents that are not themselves OAS).

**Comment by EricWittmann** [comment]
Agreed - this is an important feature long term.  In particular I'd like to have another "file type" that Apicurio manages that just contains e.g. re-usable definitions.  So you could manage all your data types within one file and then reference them from multiple API designs.

**Comment by EricWittmann** [comment]
I thought there was already an issue for this but I couldn't find it quickly.

**Comment by EricWittmann** [comment]
I realize this has taken a little while, but external references will be officially supported as of Beta 2.46, which is the next release (will hopefully be done tomorrow).  There is a new UI to import Data Types and Responses from other Apicurio Studio documents into the current one.  In addition, validation has been updated to support resolving external http/s as well as Apicurio-internal references.  This should be a good first step towards mature support for references across documents.

**Comment by Brijesh-briju** [comment]
how can we implement external reference to a file  Beta 2.46

**Comment by EricWittmann** [comment]
Just to be clear - do you want to link to an external URL not within Apicurio Studio?  Or do you want to reference something within another document inside Apicurio Studio?  The latter you can do today, the former you will need to do manually via the **Source** tab in the editor.

**Comment by Brijesh-briju** [comment]
> Just to be clear - do you want to link to an external URL not within Apicurio Studio? Or do you want to reference something within another document inside Apicurio Studio? The latter you can do today, the former you will need to do manually via the **Source** tab in the editor.

consider i need to import multiple data type which is written in a separate file xyz.yaml or xyz.jason
into my apis ...how can i do it and what is the detail procedure

**Comment by EricWittmann** [comment]
If you are managing the shared data types in an API Design within Apicurio Studio, then you can use the "Import Data Types" wizard in the editor.  First, you would create the design that will hold the shared types.  Then you would edit the design that will import those types.  Click on the "Import Data Type" icon in the editor:

![image](https://user-images.githubusercontent.com/1890703/79143055-86dfe380-7d8a-11ea-8137-b9f3b97e9097.png)

That wizard will walk you through the process of importing the data types.  Including choosing the resource(s) from which to import the data types and then which data types to import.  

![image](https://user-images.githubusercontent.com/1890703/79143189-ca3a5200-7d8a-11ea-8678-bd4ce018ed27.png)

Once imported they can be used as normal in your API design.  

This support is somewhat preliminary, and we would love feedback on whether it works for your use-case or not, and what else you would like to see available.

**Comment by Brijesh-briju** [comment]
> If you are managing the shared data types in an API Design within Apicurio Studio, then you can use the "Import Data Types" wizard in the editor. First, you would create the design that will hold the shared types. Then you would edit the design that will import those types. Click on the "Import Data Type" icon in the editor:
> 
> ![image](https://user-images.githubusercontent.com/1890703/79143055-86dfe380-7d8a-11ea-8137-b9f3b97e9097.png)
> 
> That wizard will walk you through the process of importing the data types. Including choosing the resource(s) from which to import the data types and then which data types to import.
> 
> ![image](https://user-images.githubusercontent.com/1890703/79143189-ca3a5200-7d8a-11ea-8678-bd4ce018ed27.png)
> 
> Once imported they can be used as normal in your API design.
> 
> This support is somewhat preliminary, and we would love feedback on whether it works for your use-case or not, and what else you would like to see available.

im getting error when i click on preview document

**Comment by EricWittmann** [comment]
Yes, unfortunately that is a bug in the preview right now.  I'll do my best to get a fix for that asap.
