### ISSUE TITLE
Usability: "Media Type" should be a drop-down-list with pre-defined media types

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#417]
I'd like to throw following suggestion into space for further improvement:

Media Type should be e.g. a drop down box where I can select well defined values more easily. I do not expect the suggestions to be complete and the box should still be editable manually, but it would make work much easier.

Even better would be to have one-click links for the most commonly used ones (json, text and xml, maybe others and the maserati solution would be to learn the users most often used media types).

**Comment by EricWittmann** [comment]
Yes, I definitely agree with this improvement.  Will give some thought to the best UI for this...

**Comment by EricWittmann** [comment]
The Maserati Solution (copyright 2018, @0815fox) has been implemented.  Improvements can still definitely be made, but it now offers the standard three mime types (json, xml, form-data) and also remembers "custom" mime types by storing them in browser local storage.
