### ISSUE TITLE
Publish Action: Easier publish to the same repository

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#418]
Scenario: We work in bitbucket, but the scenario applies to other external versioning systems as well. We'd like to have version control of our projects in one place. I'd like to be able to set my API up in a way, that I can easily click a publish button and commit and push the latest version without having to enter all those information from the publish view again and again and again.
I'd like to click the publish button and see a popup view where I can enter the commit message and after confirmation my API is published to override the previous version. Maybe I just did not find that feature?

**Comment by EricWittmann** [comment]
Yep!  This is actually already on my to-do list and I'll try to get it pushed up in priority a bit.  It was always intended to work the way you describe, and I believe the back-end work to support this (storing the publish destination info in the DB) is already done.

**Comment by 0815fox** [comment]
Amazing!
I am just writing those issues, because knowing how a user uses the software you make is a valuable feedback for a developer.
No need to push up priority, there is a working solution, it's just not comfortable.

**Comment by EricWittmann** [comment]
For sure - feedback from users is vital.  And most users don't provide it (which is OK too). :)

**Comment by EricWittmann** [comment]
I've fixed this for the next version of Apicurio (0.2.17.Final).  However, note that there was a back-end bug that was saving the publication information incorrectly.  So things are going to act a little weird if you published an API using a previous version of Apicurio and then re-publish that same API using version 0.2.17.Final.  It will still work, but the wrong info will show up in the Publish API form.  But then all publish actions thereafter should work well.  The only thing not pre-populated should be the commit message.

**Comment by EricWittmann** [comment]
Also @0815fox - I'd be interested in your feedback on this:  https://github.com/Apicurio/apicurio-studio/issues/462
