### ISSUE TITLE
Editor: It should be possible to delete a description (aka make empty and click OK button)

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#420]
When I make the Description box of an operation empty the OK button is disabled. This makes it impossible to delete the description, even though it is optional.

![grafik](https://user-images.githubusercontent.com/8955528/45411931-ceb1fc80-b675-11e8-8b53-09153b7101c7.png)

I think there are more cases where an optional value cannot be removed by clearing the input box. Please let me know if I shall add those boxes here when I see one.

**Comment by EricWittmann** [comment]
I've replaced all (I believe) of the description editors with a brand new version that not only supports empty values (just delete all the content and click OK) but it also finally supports Markdown.  Big win!

The relevant commit is:  https://github.com/Apicurio/apicurio-studio/commit/51315e0005461e239c0143c8efc4ef909fcaca01
