### ISSUE TITLE
Editor: Box for entering / editing description is missing in path info

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#422]
![grafik](https://user-images.githubusercontent.com/8955528/45415052-05d7dc00-b67d-11e8-8303-969a7309017f.png)

The box is not there at all, when I hover the target area with the mouse it does not appear.
The corresponding code contains a simple \n. That is probably a result of me trying to remove the description (see #420 )

```
summary: 'Get the list of device groups on this device.'
description: "\n"
responses:
    '200':
        content:
            application/json:
                schema:
                    type: array
                    items:
                        type: string
```

**Comment by 0815fox** [comment]
I did not check, whether the box is there and just only 0px wide.

**Comment by EricWittmann** [comment]
OK that's a clear bug!  You can workaround it using the source tab for now.

Another workaround for removing a description (which I just discovered) is to:

1) edit the description
2) remove the text (this will disable the OK button)
3) hit "Ctrl-Enter" on your keyboard

**Comment by EricWittmann** [comment]
By the way - this was fixed in a recent commit.  All of the description fields have been updated to support Markdown.  As part of that change, I also addressed the issue of poor UX when the value of the description is all whitespace.
