### ISSUE TITLE
Editor: Cancel in "Add property"-Popup works only on second click when the Name box is empty

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#423]
The reason is, that clicking cancel takes focus from the Name edit box. Then the error annotation ("Name must not be empty") appears, which consumes space and moves the cancel button down, such that the mouse pointer is no longer over the cancel button and the mouse up event is not triggered.

**Comment by EricWittmann** [comment]
Yeah that's annoying, isn't it?  I'm going to leave this open for now, but FYI the Add Property dialog will be rewritten shortly as part of a new [CRUD enhancement](https://github.com/Apicurio/apicurio-studio/issues/368).  Once that's done, this may or may not still be relevant...
