### ISSUE TITLE
Editor: feature request: generate examples based on the datatype definition

### ISSUE THREAD

**Issue by anatoli26** [Apicurio/apicurio-studio#438]
It would be great for the editor to generate the examples based on the associated datatype, i.e. when the user opens the window to add an example, it would be handy to populate it with an example.

In it's simplest form it could be the datatype as-is for the requests and replies examples. Where the result is a collection of items, 2 copies of the datatype could be joined together in an array.

The rationale is that users spend a considerable amount of time just populating the examples with the structure of the datatype.

**Comment by EricWittmann** [comment]
This is a great idea.
