### ISSUE TITLE
Editor: Request Body always open in POST/PUT methods, overlaps with other elements

### ISSUE THREAD

**Issue by anatoli26** [Apicurio/apicurio-studio#439]
POST/PUT methods always have Request Body section unfolded/expanded. If I keep it expanded, then switch to another method and return back to POST/PUT, the section appears open. If I close/collapse it, then switch to another method, then back to POST/PUT, the section appears as collapsed, but its content is visible as if it was expanded and it overlaps other sections.

![request_body](https://user-images.githubusercontent.com/22968420/45913310-77ebb600-be1f-11e8-8836-37be5f668965.png)

The desired behavior would be to respect the collapsed state, i.e. if I explicitly collapse it, it should stay this way.

**Comment by EricWittmann** [comment]
Closing as a duplicate of:  https://github.com/Apicurio/apicurio-studio/issues/416
