### ISSUE TITLE
Editor: source edit is not reflected in the Design view

### ISSUE THREAD

**Issue by anatoli26** [Apicurio/apicurio-studio#440]
When editing something in the Source tab, then switching back to Design tab, the UI doesn't incorporate the source changes. I have to switch to another path, then back for the UI to re-read the source.

On switching from Source to Design, the UI should be refreshed with the modified source.

**Comment by anatoli26** [comment]
Eric, thanks for checking this. My environment is Firefox 62 on Ubuntu 16.04.

The steps to reproduce:
1. Install and run an instance locally, following the instructions from here: https://www.apicur.io/download/
2. Open https://localhost:8443/studio/, create an API, open it (https://localhost:8443/studio/apis/1/editor) and create some paths
3. Open the Source tab, make some change that should be visible in the Design view without switching the views, open the Design tab.
![1](https://user-images.githubusercontent.com/22968420/46124288-ba900280-c212-11e8-9e21-1f5ee8de678c.png)
4. Observe that the change was not applied.
![2](https://user-images.githubusercontent.com/22968420/46124289-bb289900-c212-11e8-89f4-eca68eb1981c.png)
5. Switch the view to another element (e.g. to some method), then return back to the initial view. Observe the change applied.
![3](https://user-images.githubusercontent.com/22968420/46124290-bb289900-c212-11e8-8cc1-7f80380ae04f.png)

**Comment by EricWittmann** [comment]
Well that's very odd.  I tested in a couple different browsers (I don't have Ubuntu but I do have Firefox 62) and everything works as expected for me.  Here's a quick video:

![ezgif-1-dbdd220933](https://user-images.githubusercontent.com/1890703/46147589-e5d71980-c233-11e8-8ee6-887ed986d214.gif)

Can you check your browser console to see if there are any errors?

**Comment by anatoli26** [comment]
Yepp, I see... Any idea on how this could be debugged?

**Comment by EricWittmann** [comment]
Let me think about it and get back to you on Monday. :)

**Comment by EricWittmann** [comment]
OK so the key moment is when you click the blue "save" button after making changes in the source.  When you click that, the following method is called:

https://github.com/Apicurio/apicurio-studio/blob/master/front-end/studio/src/app/pages/apis/%7BapiId%7D/editor/_components/forms/source-form.base.ts#L154-L161

That method creates a command and executes it, resulting in the data model being changed.  So I'd start by making sure that is getting called.

Next, you'd be clicking on the *Design* tab to switch back to Design mode.  Doing that will cause the entire `Path` form (in the case of your example) to be recreated.  When that happens, all of the various components displayed in the path form will be created and shown.  In your example, you changed the summary of the `GET` operation.  The data for that comes from a call to `getSummary()` found here:

https://github.com/Apicurio/apicurio-studio/blob/master/front-end/studio/src/app/pages/apis/%7BapiId%7D/editor/_components/forms/path-form.component.ts#L127-L129

You'd need to see what the state of the data model is at that point - perhaps with some outputs to the console?

**Comment by EricWittmann** [comment]
By the way - if coding in typescript and running Apicurio in DEV mode is not within your skillset, let me know and I'll create a special build for you with extra debugging output and we can figure it out that way. :)

**Comment by anatoli26** [comment]
@EricWittmann, sorry for such a long delay. Just tested this issue on 0.2.22 and everything works perfectly now. Also, the interface got so many improvements comparing with the 0.2.15, just amazing! Thanks a lot for your hard work!

**Comment by EricWittmann** [comment]
Great news, thanks for following up!
