### ISSUE TITLE
Editor: Additional Fields in Definition (Enum, Examples, Minimum, Maximum, Default)

### ISSUE THREAD

**Issue by raghurakesh** [Apicurio/apicurio-studio#458]
Hi,

Thanks for this great project, and thanks to all working on this.

Suggestion to add few fields in the Definition.
- Enum (noticed that there is another ticket opened for this)
- Examples (in 2.15 there is an option to add examples for the whole definition while creating the definition, it would be good if there is an option to edit the example value after creation)
- Minimum
- Maximum
- Default

It would also be great, we can add in support for Swagger extensions (x-*). 

Regards

**Comment by EricWittmann** [comment]
Yeah enum support is needed - and as you say there's already a ticket for that.

I've already implemented support for definition example - will be available in the next release. :)

+1 to min/max and default

Not sure about extensions - those can be added in the source tab of course (like anything).  What sort of UI would you like to see for those?

**Comment by raghurakesh** [comment]
Thank you for the feedback.

About extensions, I agree with you that this can be added in the Source tab, especially since the Swagger extensions takes in custom values and could be literally anything.

One suggestion is to enable a key-value pair field exposed in the UI, which can capture the extension name and the extension value. 
It also would be useful if we can define the Swagger extensions which are supported for a specific Swagger file. For example, we can mention somewhere in the settings that "PetStore Swagger" should have "x-example" at the Operation/Method level. And when the Swagger code is generated, the x-example value pops up as a field to be filled in (in UI as well Source code). This will ensure that the person documenting the Swagger using the UI/Source tab ensures that the x-example tag is documented and not missed out.

**Comment by EricWittmann** [comment]
Good ideas - I've pulled this out into a separate issue:  https://github.com/Apicurio/apicurio-studio/issues/459

**Comment by EricWittmann** [comment]
In regards to your other bullet points, just for tracking purposes:

* Support for enums in definitions:  https://github.com/Apicurio/apicurio-studio/issues/140
* Support for examples:  https://github.com/Apicurio/apicurio-studio/issues/437
* Support for min/max/default:  https://github.com/Apicurio/apicurio-studio/issues/460

**Comment by EricWittmann** [comment]
I'm going to close this issue as we now have tracking for each individual suggestion.  Please use those referenced issues to track them individually.
