### ISSUE TITLE
Location of APICURIO_UI_URL when configuring keycloak for Apicurio?

### ISSUE THREAD

**Issue by tiagosiebler** [Apicurio/apicurio-studio#472]
I'm following this and I'm stuck in step 4. I've created a new realm by importing the file. The steps say:
>>> To do this, click on Clients in the right side of the Keycloak Admin Console. From the resulting list of clients, click on apicurio-studio.

While I'm in the realm, I don't see this in the list of clients:
<img width="1167" alt="screenshot 2018-10-06 at 23 23 50" src="https://user-images.githubusercontent.com/14090872/46576328-e6ec1180-c9be-11e8-9dc7-0542d4602029.png">

If I go to the master realm, I do see something for apicurio:
<img width="1195" alt="screenshot 2018-10-06 at 23 24 20" src="https://user-images.githubusercontent.com/14090872/46576330-fa977800-c9be-11e8-8a37-d879c0e3171b.png">

But I don't see anything matching APICURIO_UI_URL or return_url or anything like the screenshots, this is what I see:
<img width="1195" alt="screenshot 2018-10-06 at 23 24 20" src="https://user-images.githubusercontent.com/14090872/46576334-1569ec80-c9bf-11e8-8ba3-662feabd1fb8.png">

What am I missing?

Thanks for the help!

**Comment by EricWittmann** [comment]
Hoo boy, I do not know how you got into that state.  :)

As soon as I get a chance, I'll record a quick video of me configuring Keycloak for Apicurio.  Maybe that will help.

**Comment by EricWittmann** [comment]
What version of Keycloak did you download?

**Comment by tiagosiebler** [comment]
@EricWittmann the one linked to here: https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio

I've been tinkering more, no idea why it wasn't shown by default but I managed to add it manually - wasn't too many settings to guess 😄 I'm up and running! 

Still a question though, should I be using a different keycloak version?

**Comment by EricWittmann** [comment]
![configuring-keycloak](https://user-images.githubusercontent.com/1890703/46577011-7934eb00-c9a8-11e8-8ecb-503b0444776c.gif)

This video doesn't show it, but when I'm adding the new realm, I click the **Select File** button and choose the `realm.json` file that I downloaded.

**Comment by EricWittmann** [comment]
I used Keycloak version 4.5.0, which is the latest version...

**Comment by EricWittmann** [comment]
Glad it's working.  Although if the import of `realm.json` didn't work, then you might have some problems down the road.  Specifically when it comes to Account Linking with GitHub/GitLab etc.  Check this setting, for example:

![image](https://user-images.githubusercontent.com/1890703/46577090-43ddcc80-c9ab-11e8-833c-a12e0cbebf2c.png)

Under **Client Default Roles** for the broker.  The 'read-token' role is important. :)

**Comment by EricWittmann** [comment]
Oh, and generally speaking newer versions of Keycloak are better.  But anything in the 4's should be good.

**Comment by tiagosiebler** [comment]
Ah that explains why the github link wasn't working :) from the docs it sounded like I must use that version, I recommend revising that! I'll try the latest version as soon as I can. Thanks as always, Eric!

**Comment by EricWittmann** [comment]
Hey @tiagosiebler did you ever get this working?

**Comment by tiagosiebler** [comment]
Ended up using the latest version, I think... nothing needed from your side. Thanks!
