### ISSUE TITLE
OpenShift:  Split the template into two (separate the auth component from everything else)

### ISSUE THREAD

**Issue by odra** [Apicurio/apicurio-studio#485]
Hello,

I am currently developing an apicurio openshift operator using [this repo's template](https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-template.yml) it will use an existing keycloak instance rather than deploying a new one.

- I would to prefer to use the upstream template as it is without any modifications, would it be possible to provide a template in the future which does not deploy an auth server so it will just use an existing keycloak instance by providing its auth url?
-  What happens if I try to use an existing keycloak instance which already contains the realm to be used by apicurio? Would it use the existing realm?

 cc @david-martin

**Comment by EricWittmann** [comment]
Sure - we can just split the existing template into two.  That's no problem.

And yes - it's easy enough to configure Apicurio to use an existing Keycloak.  However, Apicurio does require some specific configuration within the Keycloak realm in order for all Apicurio features to work.

**Comment by EricWittmann** [comment]
If interested, more information about configuring Keycloak to work with Apicurio can be found here:

https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio

**Comment by odra** [comment]
Ah, thanks for the doc link :)

Another question, I downloaded the source code from the latest release link (0.2.18-final) and most images in the template are using the "latest-release" tag, should the template be using the "0.2.18.Final" one for all related apicurio container images instead?

**Comment by EricWittmann** [comment]
Hm.  The openshift template was originally created for https://studio.apicur.io/ - which auto-updates to the latest version whenever I do a release.  In that context, `latest-release` is obviously the right tag.  In another context it might not be.  I guess I'm not sure - it probably depends on the use-case.

**Comment by odra** [comment]
Basically what I was looking for is to lock a specific version in the template, it could happen that a deployment is using the template file from 0.2.18-final but ends up pulling the image of an earlier release (let's say 0.2.19) since it is always using the latest-release tag (I know I can change it myself, but I am trying to not change anything in the template).

Around splitting the template into two, do you manually do it or is there some kind of script that generates the template? Happy to send a pr around that :)

**Comment by EricWittmann** [comment]
The template is maintained manually - so a PR would be most welcome. :)

As for the version issue.  I think it seems reasonable to leave the `master` version of the template set to `latest-release` but update the Apicurio release script to change to the release version.  So if you grab the template from a release tag, the template would be pinned to that release.  But if you grab the `master` version, you'd get one set to `latest-release`.  Seem like a decent compromise?

**Comment by odra** [comment]
Yep, sounds reasonable!

**Comment by EricWittmann** [comment]
The only two lines in that log file that are helpful are these (trimmed for readability):

```
11:15:42 INFO  [org.wildfly.swarm] WFSWARM0027: Shutdown requested
11:15:42 INFO  [org.jboss.as.server] WFLYSRV0220: Server shutdown has been requested via an OS signal
```

The only time I've seen something like this happen is when we didn't have JVM memory settings configured.  Without the JVM memory settings, the amount of memory allocated to the app is set based on the total amount of memory the JVM **thinks** is available on the host machine.  And in an OpenShift environment that can be weird.

But the latest version of the template sets the JVM memory limits e.g. here:

https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-template.yml#L879-L881

That setting propagates down through the docker image into the app here:

https://github.com/Apicurio/apicurio-studio/blob/master/platforms/swarm/api/Dockerfile#L44-L45

So if you're using the latest template and have those settings set to reasonable values, this shouldn't be a problem.  

That said, it's definitely getting a signal from the OS to shut down.  And other than running out of memory I don't know what can cause that.

**Comment by odra** [comment]
ah you were right, the cluster I was using ran out of resources :)

thanks

**Comment by odra** [comment]
@EricWittmann actually it was still failing but it works with an older version of the api image: 0.2.4.Final but it fails with the above error if  I use a image version >= "0.2.5.Final"

**Comment by odra** [comment]
I get the same error if I use the tag "0.2.4.Final " for the ui image but latest works fine.

**Comment by EricWittmann** [comment]
The memory settings weren't introduced until I think version **0.2.14.Final** - anything before that the JVM apps would be at the mercy of the OpenShift environment configuration.

https://github.com/Apicurio/apicurio-studio/commit/9f00547121abd6315b4d45ad58970e84da1da6a8

Why are you using such an older version?  0.2.4.Final was from March...

**Comment by odra** [comment]
I was trying to make it work so I  started trying to use older version than the latest one (I didn't change any memory/jvm values from what is being used as the default values)

**Comment by EricWittmann** [comment]
Depending on your OS environment, perhaps you'll need different memory settings.  I don't know much about managing OpenShift, so I don't know what the options are for pod creation.  How are resources allotted to pods?  How much memory is available to each one?

**Comment by EricWittmann** [comment]
This separation has been completed.  We now have multiple template files that can be chosen.
