### ISSUE TITLE
Required property should not be flagged as invalid when using inside allOf

### ISSUE THREAD

**Issue by slinkydeveloper** [Apicurio/apicurio-studio#488]
Issue inspector finds that a property inside `required` don't exists, but it's false. In particular: `Schema lists property "from" as required, but it does not exist. No additional information found.`

In fact it exists in another schema merged using `allOf`:

```yaml
components:
    schemas:
        Username:
            minLength: 5
            type: string
        NewTransaction:
            allOf:
                -
                    required:
                        - from
                        - to
                        - description
                        - value
                    type: object
                -
                    $ref: '#/components/schemas/UpdateTransaction'
        UpdateTransaction:
            type: object
            properties:
                from:
                    $ref: '#/components/schemas/Username'
                to:
                    $ref: '#/components/schemas/Username'
                value:
                    type: number
                description:
                    minLength: 1
                    type: string
        Transaction:
            allOf:
                - $ref: '#/components/schemas/UpdateTransaction'
                -
                    required:
                        - from
                        - to
                        - id
                        - description
                        - value
                        - at
                    type: object
                    properties:
                        id:
                            type: string
                        at:
                            format: date-time
                            type: string
```

**Comment by EricWittmann** [comment]
Tracked in the `oai-ts-core` library where the validation rules are maintained:

https://github.com/Apicurio/oai-ts-core/issues/29

**Comment by EricWittmann** [comment]
OK - so after doing a little bit of digging into this, are you sure that your use-case is supposed to work?  From the documentation I can find regarding JSON Schema, it seems very clear that the peer schemas inside `allOf` do not know anything about each other.

Some references:

* https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.22
> Elements of the array MUST be objects.  Each object MUST be a valid JSON Schema.
* https://stackoverflow.com/questions/22689900/json-schema-allof-with-additionalproperties#23001194
> In your scenario, which many, many people encounter, you expect that properties defined in schema1 will be known to schema2; but this is not the case and will never be.

It **seems** like Apicurio is doing the right thing based on the above references, but I'm more than happy to be wrong on this.

**Comment by slinkydeveloper** [comment]
@EricWittmann the `required` keyword is indipendent from `properties` keyword. In fact all keywords in json schema are indipendent each other (except some things like `properties`-`additionalProperties`, `exclusiveMinimum`-`minimum` and similar). So you can define for example a property as `required` without defining it. This schema is valid (test it with https://www.jsonschemavalidator.net/ ):

```json
{
  "required": [
     "prop1"  
  ]
}
``

**Comment by slinkydeveloper** [comment]
@EricWittmann the hidden trick of json schemas are: _keywords are indipendent_ :smile:

**Comment by EricWittmann** [comment]
Closing this since I have disabled the offending validation rule.
