### ISSUE TITLE
Publish to GitHub fails fetching the organizations

### ISSUE THREAD

**Issue by SJWooten** [Apicurio/apicurio-studio#494]
Have a GitHub account with an organization and repo with a single .yaml OpenAPI file created with Apicurio. I have linked my Apicurio to GitHub and imported a new API from the GitHub account using the .yaml file. I make some edits and try to publish the file back to the GitHub account and the organization menu doesn't contain any match entries. I see this error in Chrome:

[GitHubResourceComponent] ngOnInit()
main.a89b113eff0fc21de5ae.bundle.js:1 [HubLinkedAccountsService] Getting organizations: http://localhost:8180/api-hub/accounts/GitHub/organizations
:8180/api-hub/accounts/GitHub/organizations:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.a89b113eff0fc21de5ae.bundle.js:1 t
(anonymous) @ main.a89b113eff0fc21de5ae.bundle.js:1
main.a89b113eff0fc21de5ae.bundle.js:1 [TokenAuthenticationService] Refreshing auth token: http://localhost:8180/studio/token
main.a89b113eff0fc21de5ae.bundle.js:1 [TokenAuthenticationService] Will refresh auth token in 300 seconds.

**Comment by SJWooten** [comment]
Yes, downloaded Apicurio, Keycloak and setup according to the instructions.

Yes, breaks every time after logging out, linking, unlinking and went through from scratch setting things up a couple of times. I set it up with just my personal account first, then added an organization and added a oauth app to it with changes to Keycloak to use the new client/secret.

SJWooten

Steve
________________________________

**Comment by EricWittmann** [comment]
I just realized that asking you for your GitHub username is perhaps the dumbest thing I've ever done....as we are conversing ON GITHUB.  Sigh.

Anyway - there are other ways we can go about trying to diagnose this issue, but the easiest is if I get you a new build with some additional logging of GitHub related errors.

I'll have something available for you to download and try (if you're willing!) in a few minutes.

**Comment by EricWittmann** [comment]
OK @SJWooten - can you give this new build a try?

https://www.dropbox.com/s/nbq7oonri167jv2/apicurio-studio-0.2.19-SNAPSHOT-quickstart.zip?dl=0

When you get to the point of trying to publish your API, any error encountered by the server should be logged to the server console and log file.  That stack trace should tell us what's going wrong.

**Comment by SJWooten** [comment]
Yep, I'll give it shot when I get into work this morning.

Steve
________________________________

**Comment by SJWooten** [comment]
I can tell you what it said when I clicked on the error link in Chrome, Unauthorized.

Steve
________________________________

**Comment by EricWittmann** [comment]
With that new snapshot build, did you get any errors in the Apicurio server console?

Note: clicking that URL you found in the console will definitely result in an unauthorized response because in order to access the Apicurio back-end REST API you would need to provide a bearer token from keycloak as part of the request.  But it would just tell you the same info as what I'm hoping will be printed out to the console using that new build. :)

**Comment by SJWooten** [comment]
Hmm, made some other responses that didn't make it into this thread. Oh well. Yes your build was helpful in showing where the problems was. I apparently didn't add the Default Scopes in Keycloak. Unfortunately that just lead to another Keycloak/GitHub access error that I could not get around. Short answer is there seems to be something out of whack with my GitHub account. Could just be all I have is the free one since I very seldom use it. Our organization uses a private Bitbucket server. We did, however, get it working with a coworkers GitHub account. He forked a branch from the new organization I had created, set everything up according to the documentation and it all worked fine in time for our hackathon demo. I appreciate your help. We will eventually want to link to our private Bitbucket server. What's your schedule looking like for the next beta and eventual release.

**Comment by EricWittmann** [comment]
I'd love some help getting any kinks worked out running against a private Bitbucket server.  That's a permutation I haven't been able to test due to lacking a private Bitbucket server. :)

Releases are done every two to three weeks typically, but is more driven by the state of the codebase than any strict release schedule.  I'd expect another release in a couple of weeks.

The final 1.0 release doesn't have a firm schedule yet.  There is still a lot of functionality that I would like to include in 1.0, but we strive for the beta releases to all be quite stable.

**Comment by EricWittmann** [comment]
Always interested!  There are definitely still a few issues with examples in Apicurio.

It also sounds like you would benefit from some sort of customized workflow to get data from Apicurio into Confluence.  Perhaps a web hook or plugin system of some kind... there is an issue open for that.

All of that said, it sounds like we can close this issue and any additional problems you have or features you would like to see can be added as new issues.
