### ISSUE TITLE
Path Parameters Can't Parse Extensions

### ISSUE THREAD

**Issue by drwelby** [Apicurio/apicurio-studio#505]
Making a path like:

`/attachments/{attachmentID}/image.{mimetype}`

results in only `attachmentID` being found. The `mimetype` does not parse out so it isn't detected.

**Comment by EricWittmann** [comment]
Sounds like **someone** messed up a regular expression!

(spoiler: that someone would be me)

Thanks for the report - I'll have a look asap.

**Comment by EricWittmann** [comment]
This will be fixed in the next release.  Pretty sure I got all aspects of this issue - including validation.  But please re-open this issue if you find any problems in the new version (which will hopefully be released this week).
