### ISSUE TITLE
Signpost whitespace in error-prone locations

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#52]
In various input areas you can add whitespace, and it can be non-obvious - seems like a possible hard-to-find user-error location (e.g. path, query params, etc). “/foo “ or “/ foo” etc. Might be able to signpost that whitespace in a useful way, for example by highlighting it in a different colour or outline it as a cell, for instance.

**Comment by EricWittmann** [comment]
Will need to add validation rules based on the OpenAPI spec requirements for all such form locations (adding paths, responses, definitions, etc).

**Comment by msavy** [comment]
I was actually thinking that we could use symbols (as you would see in IDEs etc) to show where a whitespace/non-printable character is present.
