### ISSUE TITLE
Generating thorntail stubs fails on this openapi spec

### ISSUE THREAD

**Issue by thesteve0** [Apicurio/apicurio-studio#527]
```json
{
    "openapi": "3.0.2",
    "info": {
        "title": "rda template metadata service",
        "description": "An interface for CRUD and search of RDA templates metadata. It should help you publish and search the template metadata, thereby allowing you to find a template that suits your image processing needs",
        "version": "1.0.0"
    },
    "paths": {
        "v1/templates/metadata": {
            "get": {
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/templateMetadata"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Publish a new metadata document for a template",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/templateMetadata"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            }
        },
        "v1/templates/metadata/search": {
            "get": {
                "summary": "This is the search endpoint. Use a GET request along with parameters to search for metadata on templates.",
                "description": "Search template metadata and return a list of matching template metadata",
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/templateMetadata"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "parameters": [
                {
                    "name": "tag",
                    "in": "query",
                    "description": "search specifically against the tags",
                    "required": false,
                    "schema": {
                        "type": "string"
                    }
                },
                {
                    "name": "free-text",
                    "in": "query",
                    "description": "Words to search for in a free text search against all text fields",
                    "required": false,
                    "schema": {
                        "type": "string"
                    }
                },
                {
                    "name": "author",
                    "in": "query",
                    "description": "Search against the author field",
                    "schema": {
                        "type": "string"
                    }
                }
            ]
        },
        "v1/templates/metadata/{id}": {
            "get": {
                "description": "Get the metadata for a single template by id",
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/templateMetadata"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update the metadata for a single template by id",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/templateMetadata"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            },
            "delete": {
                "description": "Delete the metadata for a single template by id",
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            }
        },
        "v1/templates/metadata/keywords": {
            "summary": "Returns all the keywords currently in entire collection template metadata ???? Should probably implement paging on this",
            "get": {
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "v1/templates/metadata/keywords/hints": {
            "summary": "Returns possible suggestions as you type in letters for a possible keyword",
            "get": {
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "keywords": {
                "description": "Keywords that apply to the template",
                "required": [
                    "keywordArray"
                ],
                "properties": {
                    "keywordArray": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "author": {
                "description": "The author of the metadata ",
                "required": [
                    "familyName",
                    "email"
                ],
                "properties": {
                    "firstName": {
                        "type": "string"
                    },
                    "familyName": {
                        "type": "string"
                    },
                    "email": {
                        "description": "email for the author",
                        "type": "string"
                    }
                }
            },
            "templateMetadata": {
                "description": "The complete metadata for a template as a JSON document",
                "required": [
                    "keywords",
                    "metadataAuthor",
                    "datePublished",
                    "templatId",
                    "id",
                    "isPublic"
                ],
                "properties": {
                    "keywords": {
                        "$ref": "#/components/schemas/keywords",
                        "description": "The keywords for the template"
                    },
                    "description": {
                        "description": "Free text description of the template",
                        "type": "string"
                    },
                    "metadataAuthor": {
                        "$ref": "#/components/schemas/author",
                        "description": "The person authoring the metadata"
                    },
                    "templateAuthor": {
                        "$ref": "#/components/schemas/author",
                        "description": "The person who authored the actual template"
                    },
                    "datePublished": {
                        "description": "The date the metadata was published. By default this will be autogenerated to be the date the metadata was submitted to the API but you can also provide a date if desired",
                        "type": "string"
                    },
                    "name": {
                        "description": "the name for the template",
                        "type": "string"
                    },
                    "templateId": {
                        "description": "ID for the template",
                        "type": "string"
                    },
                    "id": {
                        "description": "id for the metadata record. This will be autogenerated",
                        "type": "string"
                    },
                    "isPublic": {
                        "description": "Is this metadata public. By default this will be autogenerated to true",
                        "type": "boolean"
                    }
                }
            }
        }
    }
}
```

**Comment by EricWittmann** [comment]
Awesome, thanks for the report.  We'll have a look at what is going wrong (and also try to communicate the problem better in the UI).

**Comment by thesteve0** [comment]
Looks like it might have been due to the missing / as the beginning of the URLs. This JSON generates without an error now but the zip file is incorrect.

`
{
    "openapi": "3.0.2",
    "info": {
        "title": "rda template metadata service",
        "description": "An interface for CRUD and search of RDA templates metadata. It should help you publish and search the template metadata, thereby allowing you to find a template that suits your image processing needs",
        "version": "1.0.0"
    },
    "paths": {
        "/v1/templates/metadata": {
            "get": {
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/templateMetadata"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Publish a new metadata document for a template",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/templateMetadata"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            }
        },
        "/v1/templates/metadata/search": {
            "get": {
                "summary": "This is the search endpoint. Use a GET request along with parameters to search for metadata on templates.",
                "description": "Search template metadata and return a list of matching template metadata",
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/templateMetadata"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "parameters": [
                {
                    "name": "tag",
                    "in": "query",
                    "description": "search specifically against the tags",
                    "required": false,
                    "schema": {
                        "type": "string"
                    }
                },
                {
                    "name": "free-text",
                    "in": "query",
                    "description": "Words to search for in a free text search against all text fields",
                    "required": false,
                    "schema": {
                        "type": "string"
                    }
                },
                {
                    "name": "author",
                    "in": "query",
                    "description": "Search against the author field",
                    "schema": {
                        "type": "string"
                    }
                }
            ]
        },
        "/v1/templates/metadata/{id}": {
            "get": {
                "description": "Get the metadata for a single template by id",
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/templateMetadata"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update the metadata for a single template by id",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/templateMetadata"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            },
            "delete": {
                "description": "Delete the metadata for a single template by id",
                "responses": {
                    "200": {
                        "description": "success"
                    }
                }
            },
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "description": "the id of the metadata you want to retrieve",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                }
            ]
        },
        "/v1/templates/metadata/keywords": {
            "summary": "Returns all the keywords currently in entire collection template metadata ???? Should probably implement paging on this",
            "get": {
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/templates/metadata/keywords/hints": {
            "summary": "Returns possible suggestions as you type in letters for a possible keyword",
            "get": {
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "keywords": {
                "description": "Keywords that apply to the template",
                "required": [
                    "keywordArray"
                ],
                "properties": {
                    "keywordArray": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "author": {
                "description": "The author of the metadata ",
                "required": [
                    "familyName",
                    "email"
                ],
                "properties": {
                    "firstName": {
                        "type": "string"
                    },
                    "familyName": {
                        "type": "string"
                    },
                    "email": {
                        "description": "email for the author",
                        "type": "string"
                    }
                }
            },
            "templateMetadata": {
                "description": "The complete metadata for a template as a JSON document",
                "required": [
                    "keywords",
                    "metadataAuthor",
                    "datePublished",
                    "templatId",
                    "id",
                    "isPublic"
                ],
                "properties": {
                    "keywords": {
                        "$ref": "#/components/schemas/keywords",
                        "description": "The keywords for the template"
                    },
                    "description": {
                        "description": "Free text description of the template",
                        "type": "string"
                    },
                    "metadataAuthor": {
                        "$ref": "#/components/schemas/author",
                        "description": "The person authoring the metadata"
                    },
                    "templateAuthor": {
                        "$ref": "#/components/schemas/author",
                        "description": "The person who authored the actual template"
                    },
                    "datePublished": {
                        "description": "The date the metadata was published. By default this will be autogenerated to be the date the metadata was submitted to the API but you can also provide a date if desired",
                        "type": "string"
                    },
                    "name": {
                        "description": "the name for the template",
                        "type": "string"
                    },
                    "templateId": {
                        "description": "ID for the template",
                        "type": "string"
                    },
                    "id": {
                        "description": "id for the metadata record. This will be autogenerated",
                        "type": "string"
                    },
                    "isPublic": {
                        "description": "Is this metadata public. By default this will be autogenerated to true",
                        "type": "boolean"
                    }
                }
            }
        }
    }
}
`

**Comment by EricWittmann** [comment]
The problem was the "free-text" parameter.  That is not a valid java argument name obviously, and we didn't have any code that converted characters allowed in parameter names but disallowed in java.  So I've added that and a unit test using your OpenAPI doc.  Should be fixed in the next release.

**Comment by EricWittmann** [comment]
Note:  I've tried your latest API spec with my updated version of Apicurio (locally on my dev machine) and was able to successfully generate a project.  It even builds without error right off the bat!  `mvn clean package` is all green.

There are still plenty of holes in this process I'm certain, but hopefully it will be useful for you.  Let us know whenever you run into issues, as this is still an experimental feature and will need plenty of iterating to make robust.

**Comment by thesteve0** [comment]
The issue is that the zip file is not valid when I try to download the
generated stubs. Can you test the download feature locally. I am using FF
on windows

**Comment by EricWittmann** [comment]
Update: I just did a quick commit to improve the error handling.  Now instead of blowing up the download and producing an HTML file masquerading as a ZIP file, any errors encountered while generating the zip will be written INTO the zip as a separate file called `PROJECT_GENERATION_FAILED.txt`.  That file will contain a simple log of the progress of generating the project as well as the stack trace of the server error.

**Comment by thesteve0** [comment]
Nice!
How often do you folks deploy to the service? Is there a way to be notified
of new deployments?

**Comment by EricWittmann** [comment]
Releases are automatically deployed to the online version (which is intended only as a Demo/Eval server, not as a full production system).  Releases are announced on ye olde twitter.  So next time you see an announcement on twitter, https://studio.apicur.io/ should already have been updated.
