### ISSUE TITLE
Validation Rule: Check for missing parameter definition for {} in path template

### ISSUE THREAD

**Issue by thesteve0** [Apicurio/apicurio-studio#528]
I had a path defined as /v1/path/{id}

Per the OpenApi Spec if I put in a {id} I should have a parameter entry under the path.

Swagger editor caught it.

**Comment by thesteve0** [comment]
Lack of validation issues and no exclamation mark in the URL ui like you do when the response is missing

**Comment by EricWittmann** [comment]
OK great thanks.  There is actually no requirement in the OpenAPI specification (that I can find) that mandates the existence of defined path parameters (in the list of params) for every path parameter defined in the path template.

That's not to say I disagree with the need for this to be validated.  It's just not a violation of the spec (as far as I can tell).  If I'm wrong please let me know and we can get a validation rule implemented for it.

However, until we can get to the point where validation rules can be enabled/disabled, I have decided not to implement any "optional" rules.  The future definitely includes the ability for users to enable additional rules (like this one) via the UI.

**Comment by EricWittmann** [comment]
Oh - so as a result I'm marking this as an **enhancement** (and a good one) that will be addressed once the enable/disable feature has been implemented.

**Comment by EricWittmann** [comment]
This has actually been recently implemented.  If this still doesn't work please re-open this issue!
