### ISSUE TITLE
Publishing to a branch in Bitbucket is not working

### ISSUE THREAD

**Issue by luciano-jr** [Apicurio/apicurio-studio#530]
Using the bitbucket the branch selected is not used to commit the update, the changes are applied on the master branch into a folder with the same name of the selected branch before.

**Comment by EricWittmann** [comment]
Looking over the Bitbucket connector code now and.......yep it's a mess.  Sorry about that, will spend some time making it better.

**Comment by EricWittmann** [comment]
This should be fixed in the next release (0.2.20.Final aka Beta 2.20).  Thanks for the bug report!
