### ISSUE TITLE
Text with Chinese characters

### ISSUE THREAD

**Issue by kliyes** [Apicurio/apicurio-studio#532]
Thanks for the wonderful apicurio-studio! It saved my time with original swagger editor. 
But I found that if text contains Chinese characters (such as path summary), the result file comes with "??"
Encountered this issue in latest release v0.2.19.Final

**Comment by EricWittmann** [comment]
OK thanks for the bug report.  I'll have a look.

**Comment by kliyes** [comment]
@EricWittmann oh……I'm sorry, but it may be a misunderstanding……I've deployed apicurio again on my local machine with the same release as I deployed on my server before, the Chinese characters display as expected. Maybe I had something wrong with my server's environment or configuration, I'll check it out.
This issue can be closed, I'm so sorry for wasting your time……

**Comment by EricWittmann** [comment]
No problem!  Please let me know if you can reproduce the problem.  I would not be at all surprised if there are still some lingering character encoding problems in Apicurio.

If you are able to reproduce, just go ahead and re-open this issue! :)

**Comment by EricWittmann** [comment]
Ah OK that makes sense!  Thanks for letting me know.
