### ISSUE TITLE
Microcks:  Hide the "Mock with Microcks" action for OAS 2.0 APIs

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#542]
Note: this requires that we pull the spec version information out of the content and into a column for each API (like we do for title and description).  This is something that should be done anyway as it is broadly useful.  Once done, the spec version can be displayed in e.g. the API list page.  We should include "OAS" plus the version # in the column, so that in the future we can support other file types.

**Comment by lbroudoux** [comment]
Another condition for not displaying the "Mock with Microcks" action is also the absence of a Microcks server configuration (e.g. no `apicurio.hub.microcks.api` in `HubConfiguration)

**Comment by EricWittmann** [comment]
I've fixed both of these conditions.  

https://github.com/Apicurio/apicurio-studio/commit/bf86b77578d33369b2ffc8e505bc5171ba518c9d

Note that there is a separate UI-only configuration option that controls whether microcks integration is enabled in the UI:

`apicurio-ui.feature.microcks` must be set to `true` for the action to appear (only on 3.0 apis)
