### ISSUE TITLE
Editor: Adjustable Property label size in Design mode

### ISSUE THREAD

**Issue by ablaas-ald** [Apicurio/apicurio-studio#546]
Hi,
The new `Design Editor` view is better as it lists all properties in a compact way, but the `Property Name` has relative small space when compared to the `Description`. It is impossible to distinguish same root properties when long names, as they all are under the elipsis "...".

Maybe it would be best to reduce the `Description` size in favor of the `Property Name`, or make it resizable in the grid.

I've attached an example image.

BTW: We love Apicur.io!

![image](https://user-images.githubusercontent.com/46496046/50918138-b2657700-143f-11e9-9ab7-ca7a9c7a5fe7.png)

**Comment by ablaas-ald** [comment]
Thanks Eric! I must tell you that finding APICUR.IO was a game changer in my team. We were struggling with swagger trying to write down API specs, but it was very difficult to put everybody in the "same page". 
When I found your platform, and saw your video... it was an "Aha!" moment, as it gave me the tools to design a REST API, and for the FIRST TIME, I was able to explain my dev team where we are heading :)

So a big THANK YOU for your work... apicur.io is now indispensable in our api design development pipeline.
Can't wait for it to come out of BETA ;)

**Comment by EricWittmann** [comment]
Hey that's great - very glad that it's useful for you!  Please don't hesitate to suggest features that would make it more productive for your team.  We've got quite a pipeline before Apicurio comes out of beta, which should hopefully result in a very nice feature set for the 1.0 release!

**Comment by ablaas-ald** [comment]
Works great! Thanks 👍
