### ISSUE TITLE
API Editor: Signpost details section after verb create operation.

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#56]
After  you click “create operation”  it’s not immediately obvious that you need to click the verb name (e.g. GET)  to enter into the API details section. There should be a flow to automatically takes you there [e.g. forces you to enter name/description, then after you click accept takes you to the detail page] or an obvious visual prompt [e.g. .

**Comment by EricWittmann** [comment]
This issue is no longer valid after a redesign of the editor UX.
