### ISSUE TITLE
Editor: When inserting <HTML> code block, the editor will interpret it and behave incorrectly

### ISSUE THREAD

**Issue by ablaas-ald** [Apicurio/apicurio-studio#565]
When inserting an HTML code block in the description, the title will not colapse.
The expanded section will show it in a `code block`, but the collapsed one "interprets" the HTML and shows it anyway:

### Expanded view

<img width="703" alt="imagen" src="https://user-images.githubusercontent.com/46496046/51075915-4cbcf900-1692-11e9-94bf-65363cbd8269.png">

### Collapsed view

<img width="610" alt="imagen" src="https://user-images.githubusercontent.com/46496046/51075921-5d6d6f00-1692-11e9-9173-58cb8193282e.png">

**Comment by EricWittmann** [comment]
Interesting - I had not tried this because the OpenAPI spec doesn't allow HTML descriptions (preferring Markdown/CommonMark for rich descriptions).  However, the editor should still do the right thing in this case and I'm a bit surprised about what it's doing. :)

**Comment by ablaas-ald** [comment]
Thanks! This is an old feature we've not yet moved to Markdown -work in progress!
But I felt it was good to mention to avoid 'injections' ;)

**Comment by EricWittmann** [comment]
Yes indeed - injection was my first thought as well.

**Comment by EricWittmann** [comment]
Better late than never on this.  Sorry for the delay.  Especially for such an easy fix!
