### ISSUE TITLE
Documentation: start new documentation using GitBook

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#60]
https://www.gitbook.com

**Comment by msavy** [comment]
As I suggested in channel, I think we should use the Asciidoc(tor) toolchain they have available. It has better features for the broader requirements in full docs.

**Comment by msavy** [comment]
Related but interesting, there's a theme for publishing API documentation in GitBook. Possibilities! https://plugins.gitbook.com/plugin/theme-api

**Comment by msavy** [comment]
It also does FAQ, cool! https://help.gitbook.com/basics/for-faq-documentation.html

**Comment by EricWittmann** [comment]
Using readme.io for this.
