### ISSUE TITLE
Editor: When editing a "summary" of an operation, the edit control doesn't close when selecting a different operation

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#606]
Steps to reproduce:

1. Click on a path with at least 2 operations.
2. Click the **summary** of an operation to start editing it
3. Click a different operation

Note that the summary control inline editor remains (with the old value!).  The inline editor should close on a selection event.  All inline editors should close whenever a selection event is fired.

**Comment by JulienGoldman** [comment]
Hello Eric,

Same issue on every inline editors I think.
I reproduce this issue with data type example.

![image](https://user-images.githubusercontent.com/39827356/53644196-4c72c000-3c36-11e9-99b5-f4b69b6be2a9.png)

**Comment by EricWittmann** [comment]
Thanks for the update @JulienGoldman - this is not surprising but very good to know!  I think it should be an easy fix and I have a couple of ideas...just need to decide on the best approach.  I think there are three (at least) possible solutions:

1) watch for click events outside the editor
2) close the editor if the @input changes
3) close when the user changes their selection (there is an application event for this)

None of the solutions are hard to implement.

**Comment by EricWittmann** [comment]
Note: I'm just in the middle of upgrading from angular 5 to angular 7, and I'm out on vacation all next week.  But after that I should be getting back to some bug fixes, this included.

**Comment by EricWittmann** [comment]
I think option (2) above is the easiest to implement and the most correct.  So am going to try doing that now. :)
