### ISSUE TITLE
Openshift: Template refers to non-existing Docker image tags

### ISSUE THREAD

**Issue by erikgb** [Apicurio/apicurio-studio#635]
It seems like the [Openshift template](https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-template.yml) refers to non-existing Docker image tags (latest-version). The [standalone Openshift template](https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-standalone-template.yml) is using latest-release image tags, which seems to be correct according to the discussion in #485.

**Comment by EricWittmann** [comment]
Yep - this is my screwup in the script I use to release Apicurio.  I've fixed the script already (thanks to your bug report) and I will go fix the template as well.

Thanks for finding this!
