### ISSUE TITLE
Unable to publish on gitlab

### ISSUE THREAD

**Issue by rfussien** [Apicurio/apicurio-studio#638]
Hi,

Since the Beta 2.21, I'm not able to publish on gitlab anymore.

I can list my groups and select one, I can list my projects and select one, it doesn't return any branch.
(_It seems https://studio-api.apicur.io/accounts/GitLab/groups/{myGroup}/projects/{myProject}/branches is returning an empty array_).

I'm using studio.apicur.io and I tried the following actions without success:
- logout and empty all my browser data
- unlink the gitlab account, remove the token from gitlab and link it again
- create another branch on gitlab
- unprotect all the branches on gitlab

I tried with github and everything works fine.

**Comment by EricWittmann** [comment]
OK thanks for the report.  I'll check this out today.

**Comment by rfussien** [comment]
Great,
Thanks for your time and for this very nice app.

**Comment by EricWittmann** [comment]
Thanks!  :)

FYI this bug should be fixed on https://studio.apicur.io now.  Let me know if you have any other issues.
