### ISSUE TITLE
Convert Apicurio masthead to PatternFly 4

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#649]
As phase 1 of the conversion from PF3 to PF4, let's start with the masthead.  Hopefully we can quickly and easily replace the masthead to be PF4 without affecting much else.

**Comment by catrobson** [comment]
Here's some hopefully helpful links:
https://pf4.patternfly.org/
https://github.com/patternfly/patternfly-next
https://pf4.patternfly.org/upgrade-guide
