### ISSUE TITLE
automatic example generation - fix \n

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-studio#668]
at the moment the generator introduces \n for new line, but this makes the example representation in other platform wrong. So suggest removing \n

**Comment by EricWittmann** [comment]
Can you provide some additional information about this problem?  I'm looking at the example generation code now and it doesn't explicitly use `\n`.  Rather it is creating a javascript object and then using `JSON.stringify()` to turn it into a string for display in the UI control.  Here is the code:

The example editor:  https://github.com/Apicurio/apicurio-studio/blob/master/front-end/studio/src/app/pages/apis/{apiId}/editor/_components/common/inline-example-editor.component.ts#L61-L65

The example generator:  https://github.com/Apicurio/apicurio-studio/blob/master/front-end/studio/src/app/pages/apis/{apiId}/editor/_util/model.util.ts#L131-L147

So, can you provide additional details about what exactly you are seeing?  Including what browser and operating system you are using, and perhaps a screenshot of the problem?

**Comment by EricWittmann** [comment]
@lucamaf Any chance you have more details about this issue?

**Comment by EricWittmann** [comment]
Closing as invalid for now - please re-open with additional context/information if necessary!  I'm happy to work on/fix this but I don't currently have enough context.
