### ISSUE TITLE
Store examples as strings only for types not representable in JSON/YAML

### ISSUE THREAD

**Issue by null-dev** [Apicurio/apicurio-studio#671]
A regression was introduced while fixing this issue: https://github.com/Apicurio/apicurio-studio/issues/399 causing examples to always be stored as strings.

Instead, examples should only be stored as strings when they cannot be represented in JSON/YAML.

Relevant OpenAPI specification: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject

**Comment by Nicnl** [comment]
Sorry to be a bother, but is there any news concerning this issue?

I'm trying to create a json example

![image](https://user-images.githubusercontent.com/1387951/54123894-34066080-4401-11e9-80d7-e8ee514cf1e6.png)

But it's getting stored as a string

![image](https://user-images.githubusercontent.com/1387951/54123925-4a142100-4401-11e9-816f-1316f8fa8b95.png)

And the finished result is quoted

![image](https://user-images.githubusercontent.com/1387951/54123947-5bf5c400-4401-11e9-8890-d0559b33b43e.png)

Right now it's the only issue that makes it difficult to use

**Comment by EricWittmann** [comment]
No bother at all - the more noise that an issue receives in the community, the more likely it is to be prioritized.  :)  I was out on vacation last week, but am back now and ready to squash some bugs.  I'll see if I can carve out some time today for this.

**Comment by EricWittmann** [comment]
This will be fixed in the next release of Apicurio (which should be done today or tomorrow).  I'm very interested to see if the changes work well for you, so if it's possible to provide some feedback here once you've had a chance to try it that'd be awesome!

**Comment by Nicnl** [comment]
With pleasure

**Comment by null-dev** [comment]
Seems to work perfectly for me, thanks @EricWittmann for creating the best free OpenAPI editor out there!

**Comment by EricWittmann** [comment]
Great thanks for the feedback.  FYI, watch out for this bug (a use-case I missed when addressing #671):

https://github.com/Apicurio/apicurio-studio/issues/693

**Comment by Nicnl** [comment]
Sorry for the delay

It's working great on my end too

Thank you!
