### ISSUE TITLE
Modifications are not saved

### ISSUE THREAD

**Issue by ysnoussi** [Apicurio/apicurio-studio#675]
Using the online version, I can't save anything on my modification.  If I refresh the page I loose my modification, also nothing is logged in the activity logs.

please help

**Comment by EricWittmann** [comment]
Hi @ysnoussi - I believe there was an intermittent database connectivity issue experienced by the "Try Live" version of Apicurio last week.  It seemed to be limited in scope to a relatively short amount of time last Monday.  Please re-open this issue if you are **still** experiencing problems.
