### ISSUE TITLE
External references for common definitions?

### ISSUE THREAD

**Issue by FrozenKiwi** [Apicurio/apicurio-studio#681]
This may be a niche case, but would it be possible to support multiple API's with shared definition files?  The yaml syntax supports this via the $ref token.

This is very useful when setting up systems with multiple parties instead of the simple server/client mode.  In my system I have 3-way communication, and it helps to share definitions that multiple parties need to reference.

**Comment by EricWittmann** [comment]
This is definitely on the roadmap and I think there is another GH issue already open...I'll try to find it later. 😀

**Comment by EricWittmann** [comment]
I realize this has taken a little while, but external references will be officially supported as of Beta 2.46, which is the next release (will hopefully be done tomorrow).  There is a new UI to import Data Types and Responses from other Apicurio Studio documents into the current one.  In addition, validation has been updated to support resolving external http/s as well as Apicurio-internal references.  This should be a good first step towards mature support for references across documents.
