### ISSUE TITLE
Error on query parameter for OData api that starts with $ sign

### ISSUE THREAD

**Issue by pblommendaal** [Apicurio/apicurio-studio#684]
Hi,

I was trying out Apicurio studio for moving over our existing api's. Most of them worked via the import except for one OData api. This api uses $ sign prefixes for query parameter like $filter, $top etc. This is common for OData api's. 

But when entering the name for a query parameter that starts with a dollar sign I cannot save it and get the error:  **Enter a valid name (only alpha-numeric characters are allowed - no whitespace).**

If I save it without $ sign prefix, for example "filter" I can rename it to $filter afterwards and then no issues are found. Editing the parameter then results in the same error of course.

Regards,
Peter

**Comment by EricWittmann** [comment]
Thanks @pblommendaal - I'll adjust the regexp to fix this problem.

**Comment by pblommendaal** [comment]
Great @EricWittmann, thanks for the quick response.
