### ISSUE TITLE
Integration with Microcks template

### ISSUE THREAD

**Issue by sleevezip** [Apicurio/apicurio-studio#704]
We are running Apicurio studio (latest) on OpenShift (v3.11). 

Installation has been executed using https://github.com/Apicurio/apicurio-studio/blob/master/distro/openshift/apicurio-template.yml
and we want to integrate our Apicurio with Microcks also running on the same OpenShift.
However, if we follow instructions from the page https://apicurio-studio.readme.io/docs/integrate-microcks-for-mocking-your-api
adding environment variable APICURIO_UI_FEATURE_MICROCKS=true to the apicurio-studio-ui deployment is not resulting with availability of API Mocking panel on Apicurio GUI.

How do we resolve this issue? 

Or is there already a template which already included this integration?

Thanks!

**Comment by EricWittmann** [comment]
One thing to note is that API mocking is only available for OpenAPI 3.0 definitions.  Is it possible that you are using OpenAPI 2.0?  That would explain why that panel is not appearing.

**Comment by sleevezip** [comment]
Hi @EricWittmann thanks for you suggestion.

The panel is not appearing for both OpenAPI 3.0 and OpenAPI 2.0 definitions.

**Comment by mhassan-786** [comment]
just need to know that only environment variable APICURIO_UI_FEATURE_MICROCKS=true need to add in the UI deployment or the whole 

$ export APICURIO_MICROCKS_API_URL=http://microcks.example.com/api
$ export APICURIO_MICROCKS_CLIENT_ID=microcks-serviceaccount
$ export APICURIO_MICROCKS_CLIENT_SECRET=7deb71e8-8c80-4376-95ad-00a399ee3ca1
