### ISSUE TITLE
Where is the data stored?

### ISSUE THREAD

**Issue by kino90** [Apicurio/apicurio-studio#705]
Hello, just a quick question

Where is the data about the saved API stored?
Is it in a database or just stored locally and shared with others with sockets or something like that?

**Comment by EricWittmann** [comment]
All data is stored in a database.  Supported DBs are:
* h2
* mysql
* postgresql

Each individual change made by each user is stored there.  Even when a change is "undone" it remains in the database.  The database is queried for changes and the result is the "Activity" information that you can see in both the main dashboard and the api details pages.

**Comment by kino90** [comment]
Thanks Eric

**Comment by SusilRamarao** [comment]
Hi @EricWittmann one doubt. I have changed the source db to Postgresql by changing config in datasource and the system-properties part and also initialized with DDL and set "apicurio.hub.storage.jdbc.init" to false. Everything is running fine and apis created are stored and retrieved. But I have a doubt, when I queried the database tables it always shows "0 rows" like data is empty. I thought it is not fetching correctly so i intentionally put the wrong password in xml. I got an error while "Init".

Looks like everything is fine.. but how to check if it is correctly using the database. Thanks.

**Comment by EricWittmann** [comment]
Which database tables did you try to query?  Each time you create a new API in Apicurio, a new row will be created in this table:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-core/src/main/resources/io/apicurio/hub/core/storage/jdbc/hub_postgresql9.ddl#L13

If you are querying that table and it's returning 0 rows, then something is wrong somewhere.  :)  If that's happening I can't guess what might be happening, but we can narrow it down.  I would need to know how you're running it - is it the quickstart, docker, kubernetes, openshift?  Any configuration details you can provide (or attach to this issue) would help.

(Note: if you attach any config files please make sure you redact any passwords in them!)
