### ISSUE TITLE
Add PostgreSQL and password generation to docker-compose distro

### ISSUE THREAD

**Issue by chriske** [Apicurio/apicurio-studio#724]
As we talked in #707 , I'm going to do the next steps:

- add support for both MySQL and PostgreSQL
- generate passwords and the Microcks api key at the setup process (maybe do the whole setup in a dedicated container (we can remove the PowerShell script with this approach))

If there is anything I missed, please correct me!

**Comment by EricWittmann** [comment]
Hey @chriske - any updates on this?

**Comment by chriske** [comment]
Hey @EricWittmann !

So sorry for the delay... I didn't had free time to be able to made the improvements, but now they're done. Please check it! And sorry again.

**Comment by EricWittmann** [comment]
No problem - I just reviewed the changes and they look great!  I had one inline comment about the reset script and one future enhancement suggestion.

**Comment by EricWittmann** [comment]
Thanks @chriske !  PR #868 has addressed this issue.
