### ISSUE TITLE
Allow data types to be other than objects

### ISSUE THREAD

**Issue by kino90** [Apicurio/apicurio-studio#726]
Hello, 
I wanted to create a data type as "enum" but I couldn't using the UI (even if AFAIK is a correct OpenApi)

Using the Source panel I was able to do this, but I fear it's going to break something sooner or later, so I reverted for the moment.

**Comment by EricWittmann** [comment]
You can set a parameter (of an operation) or property (of a data type) as an enum.  For example:

![image](https://user-images.githubusercontent.com/1890703/55960177-3e06c380-5c3a-11e9-9733-bd5a0bd71840.png)

What specifically were you trying to accomplish that is not allowed?  (feel free to attach the desired OpenAPI snippet)

**Comment by EricWittmann** [comment]
Also what version of OpenAPI are you using?  My example was from an OpenAPI 3.0 document.

**Comment by EricWittmann** [comment]
@kino90 Can you provide additional context for this?
