### ISSUE TITLE
Not seeing an option to push to Bitbucket 

### ISSUE THREAD

**Issue by shivinm** [Apicurio/apicurio-studio#760]
I was able to link to my Bitbucket account, and import petstore.yaml. However I am not seeing an option to push the changes to the BB repo. After watching the tutorial video, I was expecting to find a blue button to save/publish the changes in the top right corner. Am I missing something? Screenshot attached. Using the live version at https://studio.apicur.io. 
![studio apicur io](https://user-images.githubusercontent.com/5727055/57577202-1ec4a700-742f-11e9-983c-7ca2a0767b57.png)

**Comment by EricWittmann** [comment]
You cannot currently publish/push an API to Bitbucket while editing it, but rather you can do that from the API Details page.  For example:

![image](https://user-images.githubusercontent.com/1890703/57619026-eae2a200-7552-11e9-9cc4-97eebf8a2f16.png)

That should take you where you want to go. :)
