### ISSUE TITLE
Changes to API not saving

### ISSUE THREAD

**Issue by ErikHumphrey** [Apicurio/apicurio-studio#766]
Just started using Apicurio Studio, but new paths and data types are lost upon refreshing the page or going to another one.

**Edit:** From the web client. It worked in the offline version.

**Comment by BenjaminPelletier** [comment]
+1.  This happens even after logging out and logging back in.  Example console output:
```
[OperationsSectionComponent] No operations selected, setting tab to:  get
main.158fe188b58aba91d268.js:1 [OperationsSectionComponent] Setting operation tab from selection:  /paths[/dss/subscriptions/{subscription_id}]
main.158fe188b58aba91d268.js:1 [OperationsSectionComponent] No operations selected, setting tab to:  get
main.158fe188b58aba91d268.js:1 [ApiEditorComponent] Node selection detected (from the selection service)
main.158fe188b58aba91d268.js:1 [ApiEditorComponent] Selection changed to path: /paths[/dss/subscriptions/{subscription_id}]/put
main.158fe188b58aba91d268.js:1 WebSocket is already in CLOSING or CLOSED state.
e.sendSelection @ main.158fe188b58aba91d268.js:1
main.158fe188b58aba91d268.js:1 [OperationsSectionComponent] Setting operation tab from selection:  /paths[/dss/subscriptions/{subscription_id}]/put
main.158fe188b58aba91d268.js:1 [ApiEditorComponent] Node selection detected (from the selection service)
main.158fe188b58aba91d268.js:1 [ApiEditorComponent] Selection changed to path: /paths[/dss/subscriptions/{subscription_id}]/get
main.158fe188b58aba91d268.js:1 WebSocket is already in CLOSING or CLOSED state.
e.sendSelection @ main.158fe188b58aba91d268.js:1
main.158fe188b58aba91d268.js:1 [OperationsSectionComponent] Setting operation tab from selection:  /paths[/dss/subscriptions/{subscription_id}]/get
```

**Comment by EricWittmann** [comment]
It seems we have an issue with the connection to postgresql.  Hey @maneta can you have a look?  We're getting a lot of this in the logs:

```
org.postgresql.util.PSQLException: This connection has been closed.
--
  | at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:803)
  | at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1621)
```

I'm guessing that a pod restart will do the trick.  I don't have permissions to do that.  If that works, then we should make some improvements to prevent this issue in the future.

**Comment by maneta** [comment]
@EricWittmann I have done the pod restart. Let me know if it has done the trick.

Also, I would like to comment that we ain't had any events on the DB. Everything was on the infra side.

If the restart helped, maybe we could try to enhance a little bit the App HealthChecks, so Openshift could take care of the restart.

**Comment by EricWittmann** [comment]
Thanks @maneta - I believe that has taken care of the problem.  Also +1 to improving the health checks.  I can do that.  I also have some new community-contributed app configuration that will check for this problem (DB connection closed).  So the next release of Apicurio will include those config changes, and we can update the OpenShift config to enable it.

I'm going to close this issue. 

@ErikHumphrey or @BenjaminPelletier - if you continue to have problems please re-open this issue!  (or open a new one)
