### ISSUE TITLE
API spec include Korean not transfer microcks

### ISSUE THREAD

**Issue by kichigai** [Apicurio/apicurio-studio#779]
I try Microcks with Apicurio.

But create mock is fail.

I guess it was a problem that was Korean marked `???`.

when I change Korean to English. `create mock` is succeed.

please check that transfer file is utf-8 encoding.

**Comment by kichigai** [comment]
I resolve this issue.
Set Apicurio API Docker Env with `JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8` and Microcks integration success.

**Comment by EricWittmann** [comment]
Thanks @kichigai for the report and the followup.  I'm actually going to re-open this to see if we can get this working without setting the file.encoding.

**Comment by kichigai** [comment]
I use apicurio/apicurio-studio-api:0.2.26 docker image

**Comment by askfor** [comment]
We also encountered this problem, we have to add  JAVA_OPTIONS=-Dfile.encoding=UTF-8 on the microcks side.
And when integrated with gitlab, the commit message is also "????" , while the committed file is correct, we are still trying to figure this out.

**Comment by EricWittmann** [comment]
OK thanks for the feedback.  We can file all of this under "UTF-8 Problems" probably.
