### ISSUE TITLE
Self-hosted gitlab publish occur script error.

### ISSUE THREAD

**Issue by kichigai** [Apicurio/apicurio-studio#783]
I try publish with self-hosted gitlab.

Account integration is ok (ref https://apicurio-studio.readme.io/docs/using-a-local-installation-of-gitlab)

When I publish to gitlab, script error occur like below (browser console).
`ERROR TypeError: Cannot read property 'group' of undefined`

And, Infinite Group Loading...

How to fix it?

I use latest chrome browser.

**Comment by EricWittmann** [comment]
How are you able to publish at all if the groups do not load?

I wonder if the problems are, again, UTF8 issues...

**Comment by kichigai** [comment]
I review source code and find below state.

`publish.page.ts - 105 line` `this.apis.getPublications(apiId, 0, 1)` return empty array (`[]`)
so browser console log `[PublishPageComponent] No prior publications found.`

After that I click GitLab Button.

1. `publish.page.html - 56 line` `setPublishTo('GitLab')` execute
    * `_selectedType` variable value is changed.
2. `gitlab-resource.component.ts` `ngOnInit` execute
    * from `publish.page.html - 73 line` - `<gitlab-resource *ngIf="isSelected('GitLab')"`
3. `gitlab-resource.component.ts - 69 line` `this.preloadValue.group = this.value.group;` throw exception
    * because `publish.page.ts` `model` variable is not initialized.

I try first publishing. `api_content` table `type = 2` is not exist.

**Comment by EricWittmann** [comment]
Oh that's interesting - your (3) above is a problem.  Thanks for the info - I think it should help.  Would it be possible to attach the full stack trace/exception you get for that?
