### ISSUE TITLE
Chinese character is not supported in name when creating non-blank API through UI

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#789]
Chinese character is not supported in name when creating non-blank API through UI, the status is creating. Screenshot is as follows:
![ChineseCharacter](https://user-images.githubusercontent.com/16347556/58545564-198c9800-8236-11e9-80b2-eaadf7c025d3.png)

**Comment by EricWittmann** [comment]
I believe this has been fixed in https://github.com/Apicurio/apicurio-studio/commit/16fb496cd623046a4212622e6ebcfff7758c38d8
