### ISSUE TITLE
Existing Security Schema of an operation cannot be updated when updating its security

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#792]
Repro steps are as follows:
1. Define two SecuritySchema in components as follows:
~~~
    securitySchemes:
        petstore_auth:
            type: oauth2
            flows:
                implicit:
                    authorizationUrl: 'https://petstore.swagger.io/oauth/authorize'
                    scopes:
                        'write:pets': modify pets in your account
                        'read:pets': read your pets
        api_key:
            type: apiKey
            name: api_key
            in: header
~~~
2. Set one operation's security as petstore_auth through UI as follows:
![petstore_auth](https://user-images.githubusercontent.com/16347556/58548920-f7e2df00-823c-11e9-92c6-db7aa1856a39.png)

3. Remove petstore_auth through source
4. Edit the operation's security and change it to apiKey through UI, and save the change.
![apiKey](https://user-images.githubusercontent.com/16347556/58549248-adae2d80-823d-11e9-80e5-d1f5d719b034.png)

It is expected that the operation's security is changed to apiKey, but actually it is petstore_auth and apiKey, the original one petstore_auth is still there as follows:
![afterChange](https://user-images.githubusercontent.com/16347556/58549340-d9311800-823d-11e9-9e3a-618cf2ef5694.png)

**Comment by EricWittmann** [comment]
Thanks.

I also just want to say that all these bug reports are fantastic and very thorough.  Thank you for taking the time to submit them.

**Comment by yuanhuiliu** [comment]
This tool really helps us a lot, so we take some time to use it seriously. Thank you for your efforts for such a perfect project :)

**Comment by EricWittmann** [comment]
I have been unable to reproduce this. :(

It's possible that recent changes have fixed it, but it's also possible that there is something about the API design you're using, or perhaps there is a missing step to reproduce it.

Would it be possible for you to make a screencast of how you reproduce the problem?

**Comment by yuanhuiliu** [comment]
Sorry I also cannot repro it now. Seems that I mixed up the global security and path security.

**Comment by EricWittmann** [comment]
Should we close this and re-open it if you encounter it again?

**Comment by yuanhuiliu** [comment]
I think we can close it now :)

**Comment by EricWittmann** [comment]
Please definitely re-open if this pops up again though!
