### ISSUE TITLE
How to create cookie parameters for openapi 3.0.2?

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#793]
There are four possible parameter locations specified by the `in` field according to [OAS3.0.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject), and apicurio supports creating the first three types of parameter through UI which helps us a lot, now may I know how to create cookie paremeter through UI?

**Comment by EricWittmann** [comment]
We haven't yet added cookie parameters.  It would not be difficult, however, so I will see if I can add that soon.
