### ISSUE TITLE
Cannot publish and collaborate when share for everyone mode is active

### ISSUE THREAD

**Issue by rizoom** [Apicurio/apicurio-studio#796]
Hello,

**Context**:
- v0.2.26.Final
- _apicurio.share.for.everyone_ is enabled. 
- connected to a bitbucket account.

**Description**
In this mode, everyone can edit all API by default, but publish and other features do not work.

![image](https://user-images.githubusercontent.com/1694104/58879890-fb5fe580-86d6-11e9-9af8-570a81a5dd00.png)
In this screenshot, I am not the owner or a collaborator on the project, yet I can click on publish or collaborate for a project.
But when I do this (red rectangles on the screenshot), I always get a "Page not found" error.

![image](https://user-images.githubusercontent.com/1694104/58880056-4e399d00-86d7-11e9-96d3-ee2e97cef6df.png)

**Questions**
While waiting for a fix or a future change regarding the upcoming "team and collaboration" feature, do you think there is a simple workaround (even if it is manual, or dirty) so that anyone can work and publish on all APIs. Like manual endpoint calls with postman for example?

Is it possible to have several owners for the same project? Or to set ownership to someone, when the owner account is not accessible anymore (not existing in our keycloak anymore).

Thanks for your feedback.

**Comment by EricWittmann** [comment]
I think the only thing here is to create a fix in code.  I don't think there is a workaround, because I think what's happening (guessing without actually digging into the code) is that the Apicurio REST layer is responding with a 404 on some API call needed by that page.

**Comment by EricWittmann** [comment]
Collaboration features simply don't work when "share with everyone" is enabled.  I will add an option to disable these features in the UI.

**Comment by EricWittmann** [comment]
Done:  https://github.com/Apicurio/apicurio-studio/commit/6ad90ebc4e66ece94b3307ac2a15f4fbfc3bec6e

An additional system property should be set, which will disable/hide the collaboration features in the UI (since they don't work when "Share With Eveyone" is enabled):

`apicurio-ui.feature.shareWithEveryone`

Set that to `true`.

Other problems with Share With Everyone have actually been fixed and should work now - including publishing.
