### ISSUE TITLE
GitHub linking error

### ISSUE THREAD

**Issue by 0x218** [Apicurio/apicurio-studio#797]
Issue: Link to GitHub returns back to KeyCloak with "_Unexpected error when authenticating with identity provider_"

Attempting to install ApiCurio in employer's environment and the steps we followed is below:-
Note:- Creating new Realms is not permitted as KeyCloak is Corporate's IDP.  Hence installed ApiCurio (0.2.26Final) and created new client in Organization's KeyCloak (v 3.4.3Final), under existing Realm (named internal).

_**KeyCloak Client configuration -**_ 
![image](https://user-images.githubusercontent.com/38358669/58916051-27d02d80-86e8-11e9-8465-1aedc4825a42.png)

_**New OAuth client app in GitHub -**_ 
![image](https://user-images.githubusercontent.com/38358669/58916358-1e939080-86e9-11e9-82ee-9f9c0f1299f9.png)

_**IDP for GitHub in KeyCloak -**_
![image](https://user-images.githubusercontent.com/38358669/58917549-99aa7600-86ec-11e9-9785-be434e2cda01.png)

**_KC details in standalone-apicurio.xml -_**
![image](https://user-images.githubusercontent.com/38358669/58917685-0f164680-86ed-11e9-8833-f2cbdc3e1ddd.png)

### Start ApiCurio:  ./bin/standalone.sh -c standalone-apicurio.xml

- Login using KeyClock: Success.

- ApiCurio -> Settings -> Linked Accounts -> GitHub -> Link.  GitHub login credentials are accepted.  

- Then it returns back to KeyCloak with error "Unexpected error when authenticating with identity provider"
![image](https://user-images.githubusercontent.com/38358669/58917631-d70f0380-86ec-11e9-8377-506ed50bde4a.png)

**_Additional information from logs -_**

- audit.log or server.log has not logged anything specific to this error.

- The error logs from KeyCloak says -
2019-06-04 12:18:22,803 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-24) Failed to make identity provider oauth callback: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 

Please advice what is wrong in this setup.  Thanks much.

**Comment by EricWittmann** [comment]
The error message from the log indicates that the SSL handshake failed when Keycloak was trying to invoke the oauth callback.  Usually this refers to a missing certificate.  It's going to be pretty dependent on your KC server config.  I'm not a Keycloak expert so that's the best I can give you.  I did find these, which may be relevant:

http://lists.jboss.org/pipermail/keycloak-user/2016-July/006925.html
http://lists.jboss.org/pipermail/keycloak-user/2016-February/004839.html

**Comment by 0x218** [comment]
Thank you for the quick update.  Will check with infra team and proceed.  Closing this ticket now.
