### ISSUE TITLE
JSON formatting changes

### ISSUE THREAD

**Issue by lightcap** [Apicurio/apicurio-studio#802]
In version 0.2.27.Final:

JSON formatting isn't consistent between the code editor and the published version.

In code editor:
```json
"total_itemized_taxes": {
  "excise_taxes": [
    {
      "name": "Tax 1",
      "rate": 0.15,
      "collectable": 1500,
      "tax_basis": 10000,
      "jurisdiction_type": "state",
      "customer_reimbursable": true
    }
  ]
}
```

In export when publishing:
```json                
"total_itemized_taxes" : {
  "excise_taxes" : [ {
    "name" : "Tax 1",
    "rate" : 0.15,
    "collectable" : 1500,
    "tax_basis" : 10000,
    "jurisdiction_type" : "state",
    "customer_reimbursable" : true
  } ]
}
```

Formatting between the two views should be consistent, with a preference to the first format.

**Comment by EricWittmann** [comment]
OK that's fair.  The reason is that the source view is generated by `JSON.stringify` in the browser, and the download/publish content is generated on the server using Jackson.  I'm sure it's possible to customize the jackson serializer...

**Comment by EricWittmann** [comment]
Note that results of this will likely depend on what browser is being used.  So it may be impossible to ever get these 100% compatible, but we can do a better job.
