### ISSUE TITLE
How do set redirect_uri to match the DNS of hosted setup?

### ISSUE THREAD

**Issue by robertboxall** [Apicurio/apicurio-studio#807]
Can't seem to figure this out and already put hours into this.

The redirect to keycloak needs my server uri into - its seems locked to localhost.

&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fstudio%2F

How can we set this param to be the actual server name I am using? 

Tried to debug this but it seems to be automagical with jboss - how I love java at times :)

My setup I feel is pretty typical - I have nginx in front of jboss with a cert on it yet I see no way for me to setup this for anything but a localhost setup. 

For example say my server is setup as  https://api.acme.com

I'd like the message to keycloak to be:

&redirect_uri=https%3A%2F%2Fapi.acme.com%2Fstudio%2F

**Comment by robertboxall** [comment]
Ok, after reading more I figured out that with the proxy I have to set host header on nginx

location / {
            proxy_pass http://127.0.0.1:8080/;
            proxy_set_header Host  www.example.org;
            proxy_set_header X-Forwarded-For $remote_addr;
        }

So close this time but.. 

&redirect_uri=http%3A%2F%2Fwww.example.org%3A8080%2Fstudio%2F

It's http not https...

**Comment by robertboxall** [comment]
So I set keycloak to allow http . -> http://www.example.com/* for redirect...

Now website loads ... but ....

All API calls are trying to go to http not https even with the website being https

For example:
http://www.example.com/api-hub/validationProfiles

Has anyone got this working on a real cert with non localhost - what am I missing?

**Comment by robertboxall** [comment]
ok, if you are fronting this with nginx with certbot add:

proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

To your service json - this will pass the values you need to inform JBOSS of the server name and https 

Hopefully this helps someone else.

**Comment by robertboxall** [comment]
One more and hopefully this is all - after it started to work I then found websockets are not working.

   location /api-editing/ {
            proxy_pass http://127.0.0.1:8080/api-editing/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            reset_timedout_connection on;
        }

Fixed it. 

With the above you can get instance working on AWS without ELB, with HTTPS using Nginx and Certbox.

**Comment by EricWittmann** [comment]
This issue took me on a real journey! :)  Sorry you had to work this all through on your own.  But nice job figuring it out.  Any chance you'd want to write up a short article on this for the official Apicurio documentation?

**Comment by robertboxall** [comment]
Sure, I'm still figuring things out but would be happy too put something together.

**Comment by EricWittmann** [comment]
That'd be awesome!  Maybe post it here and I'll copy/paste it into readme.io where the Apicurio docs are hosted.
