### ISSUE TITLE
Edit API throws Editor Disconnected... Lost Connection.

### ISSUE THREAD

**Issue by 0x218** [Apicurio/apicurio-studio#813]
Any attempt to edit API is throwing error.

Steps I follow :-
APIs -> Create New API -> 
>     Name: Seed.Api
>     Type: Open API 3.0.2 
>      ##Note: Same issue happens with other types as well.
>     Template: Blank API
>      ##Note: Same issue happen with other default templates as well.
Click **Create API**.  Works as expected.  Log is below - 
```
	2019-06-20 18:41:37,128 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-10) Creating an API Design: Seed.Api
	2019-06-20 18:41:37,128 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-10) Inserting an API Design: Seed.Api
	2019-06-20 18:41:37,166 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-10) Getting an API design with ID 7
	2019-06-20 18:41:37,167 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-10) Selecting a single API Design: 7
	2019-06-20 18:41:37,174 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-10) Retrieving contributors list for design with ID: 7
	2019-06-20 18:41:37,174 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-10) Selecting all contributors for API Design: 7
	2019-06-20 18:41:37,174 DEBUG [io.apicurio.studio.shared.config.Configuration] (default task-7) Config Property: APICURIO_SHARE_FOR_EVERYONE/apicurio.share.for.everyone = false
	2019-06-20 18:41:37,177 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-7) Selecting activity for API Design: 7 from 0 to 10
	2019-06-20 18:41:37,179 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-11) Retrieving all collaborators for API: 7
	2019-06-20 18:41:37,181 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-11) Getting a list of all permissions (collaborators) for API: 7.
	2019-06-20 18:41:37,196 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-7) Selecting mock activity for API Design: 7 from 0 to 20
	2019-06-20 18:41:40,465 DEBUG [io.apicurio.studio.fe.servlet.servlets.TokenRefreshServlet] (default task-7) Refreshing authentication token.
```
Select the API name just created.  Click **Edit API** and I get this error - 
![image](https://user-images.githubusercontent.com/38358669/59888397-15631e80-938d-11e9-8fc6-e2921c546808.png)
Log:- 

> 	2019-06-20 18:42:37,678 DEBUG [io.apicurio.hub.api.rest.impl.ValidationProfilesResource] (default task-10) Listing Validation Profiles for 0x218
> 	2019-06-20 18:42:37,678 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-10) Getting a list of all validation profiles for 0x218.
> 	2019-06-20 18:42:37,680 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-13) Getting an API design with ID 7
> 	2019-06-20 18:42:37,681 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-13) Selecting a single API Design: 7
> 	2019-06-20 18:42:37,694 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-13) Editing an API Design with ID 7
> 	2019-06-20 18:42:37,694 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-13)         USER: 0x218
> 	2019-06-20 18:42:37,694 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-13) Selecting the most recent api_content row of type 'document' for: 7
> 	2019-06-20 18:42:37,698 DEBUG [io.apicurio.hub.core.storage.jdbc.JdbcStorage] (default task-13) Inserting an Editing Session UUID row: de8aa310-a00d-40d3-8395-a333b20a82d2
> 	2019-06-20 18:42:37,703 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-13)         Created Session ID: ee8aa310-a00d-40d3-8395-a333b20a82d2
> 	2019-06-20 18:42:37,703 DEBUG [io.apicurio.hub.api.rest.impl.DesignsResource] (default task-13)                     Secret: eyJhbHciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJtakc4RFNrT0FM
> 	2019-06-20 18:42:39,363 DEBUG [io.apicurio.studio.fe.servlet.servlets.TokenRefreshServlet] (default task-13) Refreshing authentication token.

What is triggering this issue?  Any help is appreciated.  Please let me know if any additional information is needed.

**Comment by EricWittmann** [comment]
This is likely a problem with the browser being unable to make a websocket connection to the server.  It is probably dependent on your setup.  Can you post the contents of the browser's dev console when the error occurs?  That should confirm what's going on I hope.

**Comment by 0x218** [comment]
This is what we are seeing in browser - 
![image](https://user-images.githubusercontent.com/38358669/59945672-eb156d80-942d-11e9-811d-6717789c0da3.png)

**Comment by EricWittmann** [comment]
If the browser were able to connect to the back-end via websocket, you should see some output in your server's log that looks something like this:

> 2019-06-20 18:42:37,678 DEBUG [io.apicurio.hub.editing.EditApiDesignEndpoint] (default task-10) WebSocket opened: 12345

Where `12345` is the ID of the web socket session (some unique identifier).  Since I don't see that in the output, I'm assuming the problem is that the browser can't connect to the server via websocket.  Perhaps you have something sitting in between the browser and the Apicurio back-end?  A proxy or load balancer of some sort?

I can't be sure without know more about your setup.  (and even then...)

**Comment by EricWittmann** [comment]
Since your getting a 404 in the browser rather than a "cannot connect" error of some kind, it suggests that the browser is connecting to **something** but not what it is expecting.

**Comment by 0x218** [comment]
That helped.  Thank you.  I add Version, Upgrade and Connection headers in the Nginx configuration to resolved the issue.

                location / {
                        proxy_http_version 1.1;
                        proxy_set_header Host $host;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_pass http://localhost:8080/;
                        proxy_redirect off;                        
                }

**Comment by cemnura** [comment]
Hello, I am having similar difficulties when trying to run on Kubernetes exposing the WS via Ingress.

```
WebSocket connection to 'ws://apicurio-ws.192.168.1.5.nip.io/ws/designs/2?uuid=68064b1e-f839-4973-b65e-89660d4a07d9&user=admin&secret=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxRV9
COWQ4NFZS' failed: Error during WebSocket handshake: Unexpected response code: 404
```

I am using the kubernetes manifest files in the `distro/kubernetes`. I am only changing the host for every service.

**Comment by harshayerasi** [comment]
Hello,
I am facing similar issue and I am using Apache HTTPD.
Can you help with the proper configuration for httpd?

**Comment by EricWittmann** [comment]
I'm afraid I don't have any insight into proper httpd configuration, not having done that.  :(
