### ISSUE TITLE
Live Apicurio: (https://studio.apicur.io/) Download JSON: Internal Server Error

### ISSUE THREAD

**Issue by bpeterm** [Apicurio/apicurio-studio#820]
Live Apicurio: (https://studio.apicur.io/)
Download JSON: (https://studio.apicur.io/download?type=api&format=json&id=XXXX, https://studio.apicur.io/download?type=api&format=yaml&id=XXXX)
Internal Server Error

**Comment by EricWittmann** [comment]
Can you include the stack trace?

**Comment by EricWittmann** [comment]
Also if you're willing to share the API that is causing this problem with me that'd be very helpful.  But I understand if you can't.

**Comment by bpeterm** [comment]
There's no stack trace on download link, only error message.

**Comment by bpeterm** [comment]
> Also if you're willing to share the API that is causing this problem with me that'd be very helpful. But I understand if you can't.

I send an email with collaboration link.

**Comment by bpeterm** [comment]
> Live Apicurio: (https://studio.apicur.io/)
> Download JSON: (https://studio.apicur.io/download?type=api&format=json&id=XXXX, https://studio.apicur.io/download?type=api&format=yaml&id=XXXX)
> Internal Server Error

On Windows local install:

**Comment by EricWittmann** [comment]
Thank you for the stack trace!  That's super helpful.
