### ISSUE TITLE
Unable to publish into GitLab that is inside multi level group

### ISSUE THREAD

**Issue by 0x218** [Apicurio/apicurio-studio#825]
Every time I select a subgroup (except the root group) in GitLab, ApiCurio fails with error "Page Not Found"

**_GitLab project hierarchy is -_** 
![image](https://user-images.githubusercontent.com/38358669/60222511-3f13be00-9843-11e9-985f-88da61c8003a.png)

ApiCurio lists entire groups.  I can publish into the root group (ex: mygrp_dev1).  How ever I cannot publish inside inner groups (ex mysubgrp_1, my_sub_suybgroup_1).

This scenario is working flawlessly in https://studio-auth.apicur.io.  My development server is running ApiCurio 0.2.29.Final (quickstart zip).

Nothing is written in server.log during this error.  **_Browser log_**- 
![image](https://user-images.githubusercontent.com/38358669/60222824-674fec80-9844-11e9-92a2-0b47cbaaa804.png)

**_GitLab OAuth configuration:-_** 
![image](https://user-images.githubusercontent.com/38358669/60222905-b5fd8680-9844-11e9-90e9-f516a4a32002.png)

I couldn't trace what is missing -
>     <system-properties>
>         <property name="apicurio.kc.auth.rootUrl" value="https://corproate-keycloak-srv.com/auth/"/>
>         <property name="apicurio.kc.auth.realm" value="internal"/>
>         <property name="apicurio.hub.storage.jdbc.type" value="postgresql9"/>
>         <property name="apicurio.hub.storage.jdbc.init" value="true"/>
>         <property name="apicurio-ui.hub-api.url" value="https://f5-vip-name/api-hub"/>
>         <property name="apicurio-ui.editing.url" value="wss://f5-vip-name/api-editing"/>
>     </system-properties>

Please advise.

**Comment by EricWittmann** [comment]
This is odd since the exact same code would be running on `studio.apicur.io` and your local installation.  So I'm not sure why that would work in one place but not the other.

**Comment by 0x218** [comment]
If I directly access the ApiCurio with below configuration, it works well.
> <system-properties>
>     <property name="apicurio.kc.auth.rootUrl" value="https://corproate-keycloak-srv.com/auth/"/>
>     <property name="apicurio.kc.auth.realm" value="internal"/>
>     <property name="apicurio.hub.storage.jdbc.type" value="postgresql9"/>
>     <property name="apicurio.hub.storage.jdbc.init" value="true"/>
>     <property name="apicurio-ui.hub-api.url" value="**/api-hub"/**>
>     <property name="apicurio-ui.editing.url" value="wss://f5-vip-name/api-editing"/>
> </system-properties>

Problem arise when  F5 -> Nginx -> ApiCurio.

**Comment by EricWittmann** [comment]
OK well in that case I'm guessing that either the F5 or nginx is messing up the encoding of the URL when it proxies it to Apicurio.  The URL includes the ID/name of the group, which in this case seems to be `mygrp_dev1/mysubgrp_1`.  But the `/` character is encoded as `%2F`.  That bit is likely being messed up somewhere along the way (e.g. perhaps by nginx).  Check the Apicurio logs to see if we print out the incoming URL somewhere or perhaps we print out the group name when trying to publish...

**Comment by 0x218** [comment]
Looks like it is working without issues after we removed Nginx from the picture.

**Comment by EricWittmann** [comment]
Should this be closed?
