### ISSUE TITLE
Upgrade to Keycloak 7

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#833]
We are now two major versions behind.  We should upgrade to Keycloak 6.  What needs to be done to accomplish this:

* Upgrade the keycloak version in the parent `pom.xml`
* Upgrade the `apicurio-studio-auth` docker image to use KC 6
* Make sure the Apicurio login theme works with KC 6 and update accordingly
* Make sure that https://github.com/Apicurio/apicurio-keycloak-extensions works with KC 6
* TEST TEST TEST - especially identity providers (github, gitlab, bbucket)

**Comment by asheliahut** [comment]
I have been running keycloak 6 with docker and able to run fine with the apicurio theme. Just wanted to add that to maybe bump the work being done to just knock this out.

**Comment by asheliahut** [comment]
@EricWittmann Just to note keycloak 7 is out now.

**Comment by EricWittmann** [comment]
My clever plan of being too busy to deal with Keycloak 6 has finally paid off!  Waa ha ha ha!

OK seriously though - I did see this and I do need to get Apicurio upgraded to KC 7.  I very much hope to find bandwidth for this soon.

**Comment by Criptos** [comment]
New to apicuro, new to keycloak, but really stubborn, any quick go to or doc you would recommend to get up to speed? @asheliahut  ? @EricWittmann  ?  I used the real.json from ./distro/openshift/auth/realm.json but no luck...

**Comment by EricWittmann** [comment]
There is some documentation here:  https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio

That might be a decent thing to get started.  It won't require openshift or k8s or anything like that.  If that's not what you're looking for, let me know. :)

**Comment by Criptos** [comment]
@EricWittmann  I come from that documentation... I actually setup KeyCloak 7, 4 is too old and documentaion doesn't seems to apply. 
 
I got the apicuro downloaded and the stand alone doesn't work because the dependancy of keycloak is missing, so I went out and added keycloak just to find that documentation about keycloak is to old, so I went  read here and there but then... you must know the architectural aspects of apicuro, and haven't found how exactly the relation between apicuro and keycloak is... to know what to configure at keycloak...  I would love a more up to date keycloak-apicuro documentation...

**Comment by EricWittmann** [comment]
OK thanks for the feedback.  I'll have to spend some time with Keycloak 7 to make sure I can get everything working.  Once I've done that I'll need to update the documentation and the assets (such as `realm.json`) along with the openshift templates.

Again, this is on my list of things to-do, but it's a long list. :)

However, since multiple community members are asking for this - I'll bump it up the priority list! :)

**Comment by Criptos** [comment]
How can I help? What do you need?

**Comment by EricWittmann** [comment]
That's the thing - I'm not really sure what tasks are needed.  I would start by installing Keycloak 7 and then trying to configure it based on Apicurio's needs.  To figure out what the Keycloak settings are I would probably do this:

* Download, install and run Keycloak 7
* Download, install and run Keycloak 4 (on a different port or server)
* Import the `realm.json` file into Keycloak 4
* Use the Keycloak 7 UI to create the Apicurio realm and configure it so it looks like the realm imported into Keycloak 4
* Export the resulting Keycloak 7 config to a new `realm.json` file

That would get me the KC7 configuration (hopefully).  Then I would probably just try the Apicurio quickstart to see if it worked (it might not, since the Keycloak *client* support would be old).

So to test the *client* (Apicurio app) I would clone the Apicurio Studio repository, then change the Keycloak version here:

https://github.com/Apicurio/apicurio-studio/blob/master/pom.xml#L126

Then I would build from source and, if the build worked, I would try the quickstart again (this time it should have the KC7 client included rather than the KC4 one).  Note that when you build from source, the quickstart will be a **zip** file in the **distro/quickstart/target** directory.  You will see a folder in there as well that looks like it should work, but it won't - that is a temporary directory only.  You MUST use the "-quickstart" zip file.

**Comment by Criptos** [comment]
Ok... Will do. Already have keycloack7 I will install keycloack4 and compare. I DO imported the real.json to keycloack7 but being inexperienced with keycloack didn't know what was missing or not...

**Comment by SydneyChadwick** [comment]
Just a heads up, might make the testing steps a bit easier on you.  
I'm currently running Apicurio in a Docker cluster using Keycloak 7.0. The current realm template file works and imports without issue. Integration with a local Gitlab instance also works following the instructions in the docs.  
Only major change was the ENV variables for keycloak itself to reach it's DB. The Keycloak settings look a bit different (there are more of them), but the important ones are present and the same.  
I'm not using the Apicurio themed Keycloak, so can't speak for that.

**Comment by EricWittmann** [comment]
Thank you very much for the update!  Much appreciated.

**Comment by EricWittmann** [comment]
I have fixed this:  https://github.com/Apicurio/apicurio-studio/pull/950

**Comment by EricWittmann** [comment]
I'll try to get studio.apicur.io updated to use KC 7 asap, but I'm guessing no one really cares. :)
