### ISSUE TITLE
Microcks Integration

### ISSUE THREAD

**Issue by AguRyan** [Apicurio/apicurio-studio#835]
Hi! this is my first time reporting a bug.

I was integrating Microcks to Apicurio. 

Everything goes well, till i try to import my Open API v 3.0 from Apicurio to Microcks.
I'm working with the last realese **v2.29**. 

I found the error, and realice that, between v 2.27 and v2.28, in the file "_apicurio-studio/front-end/studio/src/app/pages/apis/{apiId}/mock/mock.page.ts_" were a change in the method "_loadAsyncPageData_" when you have to create a Document.

**v. 2.29**
_this.document = <OasDocument> Library.createDocument(this.api.spec);_ 

**v. 2.27**
_this.document = new OasLibraryUtils().createDocument(this.api.spec);_

The problem is that the method "_Library.createDocument(this.api.spec);_" it's specting a _DocumentType_, and the value of "_this.api.spec_"it's a Json Object.(in the v 2.27 goes right).
So, because of that, in the console i recive the error: "_Unknown document type: [object Object]_"

in the file "_apicurio-data-models/src/main/java/io/apicurio/datamodels/Library.java_": 

```
public static Document createDocument(DocumentType type) {
        switch (type) {
            case asyncapi2:
                return new Aai20Document();
            case openapi2:
                return new Oas20Document();
            case openapi3:
                return new Oas30Document();
            default:
                **throw new RuntimeException("Unknown document type: " + type);**
        }
    }
```

I hope that this comment be helpful.

**Comment by EricWittmann** [comment]
Nice job on your first bug report.  Great summary - very thorough.  Thanks!

**Comment by EricWittmann** [comment]
Sorry for the delay in fixing this.  Fixed now - let me know if you have any additional issues!
