### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by kalinwilson** [Apicurio/apicurio-studio#837]
I have an installation question. Is this the correct venue?
I've created a user in the apicurio and microcks realms in keycloak. I can log into microcks but I get a 'forbidden' response from apicurio-studio. Impersonating from keycloak results in the same response. 
I was able to successfully install and run the studio in a local ubuntu VM. I'm having trouble in a remote centos VM that is probably configured differently. Are there ports for the communication between servers, or something else I need to look at? I can hit all of the main URLs.

**Comment by EricWittmann** [comment]
Yes, this is a perfectly fine place to ask questions!  :)

Unfortunately there isn't enough information here for me to make a guess about what's going wrong.  Is the Keycloak configuration the same in both places?  You could get a "forbidden" login response for a number of different reasons, so it's hard to guess what it might be in this case.  Is there anything in the Keycloak or Apicurio server logs?

Also what is your setup?  Are you using the Apicurio quickstart, or docker compose?

Any additional details you can provide would be great.

**Comment by kalinwilson** [comment]
I am using the docker-compose installation.
I removed all images and rebuilt the keycloak image.
I ensured that the same user, with the same credentials, was created in both apicurio and microcks realms.
I have not been able to look at the logs within the keycloak or apicurio-studio containers.
Authentication with microcks is working. It is not with apicurio.

**Comment by EricWittmann** [comment]
If microcks and apicurio are configured to user different realms, then I don't think it matters whether the user is the same in both.  But I'm not sure.

Can you log into Apicurio with some OTHER user credentials?  Or does registration work with Apicurio?  Or is it simply that logging in and user registration are both broken?

Depending on whether we make any progress on this issue, we might have better luck engaging with the keycloak community...

**Comment by EricWittmann** [comment]
Any progress on this, @kalinwilson ?

**Comment by tselepakis** [comment]
Hello, I think I have the same problem. From the logs I see the following:

> ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-1) failed to turn code into token: java.net.ConnectException: Connection refused (Connection refused)

Any thoughts?

**Comment by EricWittmann** [comment]
Is that the only relevant portion of the logs?  Are you trying it with Docker Compose?  Any additional information would be helpful!

Assuming you are using docker compose, perhaps @chriske has some ideas/thoughts... ? :)

**Comment by chriske** [comment]
Hey,

I've only tested the compose stack with Ubuntu, and on that system there is no firewall at all by default. I think there is a firewalld issue with CentOS, maybe the containers can't communicate with each other. Please try to disable the firewall for a test, and let us know the result!

**Comment by tselepakis** [comment]
Thanks for the hint. The problem was with this part:

> ./setup.sh {IP_OF_YOUR_HOST} {DATABASE_TYPE}

As IP_OF_YOUR_HOST I used `localhost`, this is not working with docker because the containers are trying to access their internal localhost. My bad. Perhaps you could add an external network or a comment there.

**Comment by EricWittmann** [comment]
Thanks for getting back to us about what the problem turned out to be!  I'll add something to the readme about that.

Also, @chriske - I've tested the docker compose on a centos 7 box with no problems.  However, I do have some ports open in firewalld already, so my success may not be representative.

**Comment by EricWittmann** [comment]
Also @chriske - I think I'm legally obligated to suggest you switch from Ubuntu to either Centos or (better yet) RHEL!  ;-)

**Comment by chriske** [comment]
Thanks for the answer!

@EricWittmann, I think an explicite comment would be enough, like please do not use localhost.

Last time when I configured docker on CentOS, I think I had some issues with the firewall, but I'm not sure. I will test it when I have some time. 

And yes... You are absolutely right about the distribution, I'm considering it a long time.
