### ISSUE TITLE
Support creating new APIs without tying to github projects

### ISSUE THREAD

**Issue by christian-posta** [Apicurio/apicurio-studio#85]
For getting started purposes, it would be nice to alleviate the dependency on Github projects for creating new APIs.

A lot of times when starting a project, we want to put a shape to the API without committing anything to any github repo. We may want to model a few API endpoints, maybe generate some stub code, maybe use something like hoverfly to give it some life, then poke at it a bit.. and then rinse and repeat. We may not intend on checking any of this into github/project until we get a pre-MVP of the API.

**Comment by EricWittmann** [comment]
This has been implemented when moving the content of record from GitHub into Apicurio's database.
