### ISSUE TITLE
Add modal for deletion

### ISSUE THREAD

**Issue by kywan** [Apicurio/apicurio-studio#858]
It would be necessary to add a modal when one clicks on the small trash to validate the deletion.

it's so frustrating to lose everything just for a miss click

**Comment by EricWittmann** [comment]
Apicurio has full undo/redo support - so if you accidentally delete something you can simply undo that action.  There are undo/redo buttons near the top-right of the editor.  Also keyboard shortcuts should work (should hopefully match your platform keyboard shortcuts e.g. Ctrl-Z in Windows).

This was a specific design decision to eliminate the need for tons of confirmation dialogs.  If undo/redo does not work, or you think it's not a sufficient solution to this problem, I would be interested in hearing that perspective from a real user!

**Comment by EricWittmann** [comment]
Any thoughts, @kywan ?

**Comment by kywan** [comment]
sorry for the lack of response, it's ok for us, thanks

**Comment by EricWittmann** [comment]
No problem!  Thanks for the response.  If you ever find that the undo/redo functionality is not sufficient/functionally then please re-open and we can discuss. :)

**Comment by kywan** [comment]
since I gave the tip to my team I have not had a return on it. I would re-open if the need arises :)
