### ISSUE TITLE
Documentation for generator workflow

### ISSUE THREAD

**Issue by wtrocki** [Apicurio/apicurio-studio#866]
I think it will be beneficial to add documentation for using https://github.com/OpenAPITools/openapi-generator with Apicurio. 

Apicurio studio together with openapi-generator can provide very powerful prototyping capabilities.

**Comment by EricWittmann** [comment]
Yeah, it's been on my list for awhile now to integrate openapi-generator into Apicurio.  There is even a cloud version of openapi-generator that could be used pretty easily.  It's still on the to-do list but not yet implemented.

**Comment by wtrocki** [comment]
Do you accept community contributions?

**Comment by EricWittmann** [comment]
Of course!  Always happy to have contributions.

**Comment by EricWittmann** [comment]
Also, @wtrocki - all of the Apicurio documentation is in readme.io here:

https://apicurio-studio.readme.io/docs

I can probably grant you access easily enough if you'd like to write an article on this topic as step 1 to further integration.

**Comment by wtrocki** [comment]
I will work away here and gist for the moment and we can later check how we integrate it. No worries. Thank you so much for creating Apicurio!

**Comment by wtrocki** [comment]
Closing as we agreed to not follow up this inside docs.
