### ISSUE TITLE
Changes cannot be saved

### ISSUE THREAD

**Issue by BenjaminPelletier** [Apicurio/apicurio-studio#878]
As of today (yesterday still worked), it seems impossible to save changes in Apicurio studio.

**Reproduction steps**:
1) Click on a Data Type in an existing API
1) Click on the Source tab of the right editing pane
1) Make a change in the Source tab
1) Click the blue Save button just above the right editing pane on the right side (it then turns gray)
1) Click on the name of the API in the "API > (name of API) > Editor" breadcrumb trail near the top of the UI

**Expected behavior**:
At this point, I would be taken immediately to the API overview screen.

**Actual behavior**:
I am shown a new dialog that says, "You have 1 unsaved changes.  Are you sure to close the page?"  Clicking Ok discards the changes that I had already saved in the Source tab.

**Alternate repro steps**:
This problem seems to happen with any change.  If, for instance, I click on a path, then click on the description of one of the query parameters, update it, and click the blue checkbox, I will now get the same dialog mentioned in actual behavior.

**Initial diagnosis**:
Looks like `api-editor.page.ts`, in which the distinctively-typoed dialog message originates, hasn't been edited since June so it seems like a change elsewhere must be triggering the problem.

**Comment by EricWittmann** [comment]
You are right - there is something going on server-side.  I'm looking into it now.

**Comment by EricWittmann** [comment]
It seems to be a new problem with Jackson's JSON parser.  The root error is:

```
Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (1565117390586) out of range of long (-9223372036854775808 - 9223372036854775807)
```

Which is obviously not true...

**Comment by EricWittmann** [comment]
I'm going to revert to an older version of Jackson and push a new release.  And I'll report this in Jackson Core.

**Comment by EricWittmann** [comment]
I believe this is now fixed.  Thank you for reporting it quickly.

**Comment by EricWittmann** [comment]
Also for reference:  https://github.com/FasterXML/jackson-core/issues/550
