### ISSUE TITLE
Unable to add a Path Parameter Example via the UI

### ISSUE THREAD

**Issue by mhockelberg** [Apicurio/apicurio-studio#883]
There is no facility in the UI to add an example value for a path parameter.  If you are using Apicurio in conjunction with Microcks to generate a mock, it requires an example of the path parameter to generate the mock.  The workaround is to add this directly to the source.

**Comment by EricWittmann** [comment]
The latest version of Apicurio Studio has this capability.  It was recently contributed by @lbroudoux as  a matter of fact!  

![image](https://user-images.githubusercontent.com/1890703/62767679-38dc4880-ba63-11e9-9f72-c6adc61c0cba.png)

**Comment by mhockelberg** [comment]
@EricWittmann okay, thank you - I will pull the latest.  Thank you @lbroudoux!

**Comment by EricWittmann** [comment]
If it doesn't work for you, please report back!
