### ISSUE TITLE
Chinese characters are not readable in auto-generated code

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#884]
We tried to use an API design which includes Chinese characters to generate a project and found that all Chinese characters are not readable in auto-generated code, the screenshot is as follows:
![unreadableCharacters](https://user-images.githubusercontent.com/16347556/62750503-fcc0dc00-ba92-11e9-89c3-323e09a89a15.png)
API design used to generated code is (please rename it to xxxx.yaml first):
[Chinese Character.txt](https://github.com/Apicurio/apicurio-studio/files/3484524/Chinese.Character.txt)

**Comment by EricWittmann** [comment]
Thank you for the bug report - I'm sure this is a simple character encoding issue.
