### ISSUE TITLE
The downloaded project code zip file cannot be unzipped if operation ID is not defined.

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#885]
Operation ID is not defined in the following sample. When using it to auto-generate a project and download the zip file, the downloaded zip file cannot be unzipped. I am not sure whether we can add some prompts for this situation :)
The screenshot of unzipped is as follows:
![cannot_unzipped](https://user-images.githubusercontent.com/16347556/62751336-e9634000-ba95-11e9-8106-40e28abdcaa7.png)
The sample API design is as follows (please rename it to xxx.yaml first):
[sample.txt](https://github.com/Apicurio/apicurio-studio/files/3484567/sample.txt)

**Comment by EricWittmann** [comment]
The **Generate Project** feature is supposed to always create a valid ZIP file.  If something fails during generation, a text file should be added to the zip file that contains the reason for the failure.  I'll take a look at this to see where it is failing and why the above behavior is not happening.
