### ISSUE TITLE
Data type not created when null value is passed in example

### ISSUE THREAD

**Issue by tabrms** [Apicurio/apicurio-studio#893]
# How to reproduce
1. Create new API with OpenAPI 3.0.2
1. Create new data type and paste JSON sample data below to JSON example field
1. Hit Save button
1. **Issue: Screeen is closed, Data type has not been created and no error message is thrown. This leads to user who has no idea what just happened.**

# Expected behavior
* Example is processed and all JSON properties are converted into Data Type properties
* NULL values are processed, but property's data type is not selected for such properties
* In case of invalid input user will be left on New Data Type page and error information is displayed

# Conditions
* Apicurio Studio v0.2.34.Final
* Windows 10 1903
* Java(TM) SE Runtime Environment (build 1.8.0_202-b08)

# JSON sample data
```
{
    "Street": "Street 123",
    "City": "Prague",
    "Zip": "11000",
    "Region": null,
    "Country": "Czechia"
}
```

**Comment by EricWittmann** [comment]
What is the expected JSON Schema for that example?

**Comment by tabrms** [comment]
I would say something simple like this

```
{
    "type": "object",
    "title": "Schema",
    "default": null,
    "properties": {
        "Street": {
            "$id": "#/properties/Street",
            "type": "string",
            "title": "Street",
            "default": null,
            "examples": [
                "Street 123"
            ],
            "pattern": "^(.*)$"
        },
        "City": {
            "$id": "#/properties/City",
            "type": "string",
            "title": "City",
            "default": null,
            "examples": [
                "Prague"
            ],
            "pattern": "^(.*)$"
        },
        "Zip": {
            "$id": "#/properties/Zip",
            "type": "string",
            "title": "Zip",
            "default": null,
            "examples": [
                "11000"
            ],
            "pattern": "^(.*)$"
        },
        "Region": {
            "$id": "#/properties/Region",
            "type": "string",
            "title": "Region",
            "default": null,
            "examples": [
                null
            ],
            "pattern": "^(.*)$"
        },
        "Country": {
            "$id": "#/properties/Country",
            "type": "string",
            "title": "Country",
            "default": null,
            "examples": [
                "Czechia"
            ],
            "pattern": "^(.*)$"
        }
    }
}
```

**Comment by EricWittmann** [comment]
OK thanks.  The assumption here is that any property that is null in the example is a string.  That's probably a reasonable choice. :)
