### ISSUE TITLE
Cant use x-grouptag after last update

### ISSUE THREAD

**Issue by thanks92** [Apicurio/apicurio-studio#895]
After the last update, I can not use x-grouptag ([redoc extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-tagGroups)) to group my tags in the side menu.

```
{
  "x-tagGroups": [
    {
      "name": "User Management",
      "tags": ["Users", "API keys", "Admin"]
    },
    {
      "name": "Statistics",
      "tags": ["Main Stats", "Secondary Stats"]
    }
  ]
}
```

It worked well before, but not now.

**Comment by EricWittmann** [comment]
I just tested this on https://studio.apicur.io and was able to get it working without trouble.  Can you be more specific about what the problem is?  Or perhaps attach a full OpenAPI3 spec as a reproducer?

**Comment by thanks92** [comment]
Here is the code. 
https://redocly.github.io/redoc/openapi.yaml 

The problem occur when I edit the source code after I have imported the Swagger code.

Folow the steps to reproduce:
1. First I imported the code by paste the url.
2. Then I clicked on "edit api" and "live documentation". I everything works fine.
3. Now I want to change the source code, so I clicked on the buttion "source code" and changed the title (just added one more character). Then the error occur when I click on "live documentation" agian.

The error message:
![image](https://user-images.githubusercontent.com/8996276/63435240-db62d700-c426-11e9-89cb-2a0531e16bf6.png)

Thanks for the help.

**Comment by EricWittmann** [comment]
OK thanks - I'll try to reproduce this as soon as I have some time.  Sorry for the delay.  Thank you for the steps to reproduce.

**Comment by EricWittmann** [comment]
So it turns out that what you have discovered is a bug in the Edit Source Code action.  I am attaching the server stack trace here (for my own benefit):

![image](https://user-images.githubusercontent.com/1890703/63592272-33acec80-c57f-11e9-8d3b-84348ee0c575.png)

I will need to fix this bug and re-release Apicurio.  I will do that as soon as I can.

Thanks for the report and sorry for the inconvenience.

**Comment by EricWittmann** [comment]
OK I've fixed the bug - now I just need to release a new version of the data-models library and then a new version of Apicurio.

**Comment by EricWittmann** [comment]
An updated version of Apicurio is available on https://studio.apicur.io/ that should fix this bug.  If you continue to have issues please let me know.

The problem was actually with the "Replace Document" command and had nothing to do with the extension property. fwiw :)

**Comment by thanks92** [comment]
Thanks!
