### ISSUE TITLE
Add editor support for "x-tagGroups" vendor extension

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#896]
https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-tagGroups

As part of our eventual support for extensions, we should consider supporting this extension (as well as any others supported by redoc that might make sense).

**Comment by thanks92** [comment]
It works now!

**Comment by EricWittmann** [comment]
Excellent thanks for the feedback.  At some point we need to have better support for extensions - something that doesn't require dropping down to the Source tab.

**Comment by EricWittmann** [comment]
We do now have support for vendor extensions at various levels of the editor.  Good enough for now but we probably need some sort of form generation support.
