### ISSUE TITLE
Preview Documentation doesn't work in localhost

### ISSUE THREAD

**Issue by ghost** [Apicurio/apicurio-studio#898]
Hello.
I trying to use Apicurio Studio in own local environment.
Installation followed [this docs](https://apicurio-studio.readme.io/docs/setting-up-a-development-environment).

It worked roughly right, but “Preview Documentation” button is not working. When I click it, curio will just redirect to dashboard page. Other than that, “Download(JSON)” and “Download(YAML)” button has also doesn’t work too.
Could you please some help?

I could not identify where the problem is. But it seems that Java Servlet isn’t working in front-end. I guess that there are some environmental problems. Or there are missing or extra server modules.
Is there another points to install Apicurio Studio?

#### OS
macOS High Sierra 10.13.6
#### Apicurio Studio version
v0.2.28
#### “quickstart” version
v0.2.38.Final
#### Eclipse IDE for Enterprise Java Developers
Version: 2019-06 (4.12.0)
#### JBoss Tools
4.12.0.Final
#### added server modules
- apicurio-studio-platforms-wildfly-api(apicurio-studio-api)
- apicurio-studio-platforms-wildfly-ui(apicurio-studio)
- apicurio-studio-platforms-wildfly-ws(apicurio-studio-ws)

**Comment by yukinomuraa123** [comment]
Ok, I'll try build and deploy app.Thanks for help!

**Comment by yukinomuraa123** [comment]
Does "dev mode" mean that running front-end by "yarn start"?

**Comment by yukinomuraa123** [comment]
I understand. Thanks!
