### ISSUE TITLE
When try to convert the docker-compose using kompose FATAL error occures

### ISSUE THREAD

**Issue by srinika** [Apicurio/apicurio-studio#902]
We are in the process of having Apicurio on our k8s cluster with the help of kompose. We managed to convert and run all docker-compose files except for the 'docker-compose.apicurio.yml'. Following error occurred;

FATA services.apicurio-studio-db must be a mapping

We followed the manual docker-compose instructions available on https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose

**Comment by asheliahut** [comment]
Remove the line in the compose file for the DB. It will only be available in the context of run with the other docker compose file for the database you chose. If you run a standalone database the DB docker image is not needed

**Comment by srinika** [comment]
Thanks, @asheliahut. I was able to get the compose file converted successfully with mysql server docker instance running. With that I was able to get Apicurio studio successfully deployed on to our Kubernetes cluster.

We are in the process of getting all the manifest files into one file. Really satisfied with the product so far and will continue to evaluate.
