### ISSUE TITLE
Online documentation uses wrong hub api property name

### ISSUE THREAD

**Issue by reitsma** [Apicurio/apicurio-studio#911]
According to the documentation (running-on-an-external-server) I should use apicurio.github.config.hubUrl system property or CONFIG_HUB_URL environment property to set the Hub API url. In the code (io.apicurio.studio.fe.servlet.config.StudioUiConfiguration) I see that I should use apicurio-ui.hub-api.url resp APICURIO_UI_HUB_API_URL. 

I use Apache as front-end, so the explicit setting was necessary. With the updated setting it works. Without setting it the fq domain name was guessed correctly though (same server), but the protocol was wrong (http vs https).

**Comment by EricWittmann** [comment]
Thanks for this!  The value was **way** wrong in the docs.  Not sure how that happened!  I have fixed the docs.
