### ISSUE TITLE
Duplicate contextpath for Camel Project

### ISSUE THREAD

**Issue by weimeilin79** [Apicurio/apicurio-studio#924]
The camel route generated has two duplicated contextpath. 
Please use different name. 

<restConfiguration component="servlet" apiContextPath="/openapi.json"/>
produces="application/json"

`<restConfiguration component="servlet" apiContextPath="/openapi.json"/>

        <rest id="rest-for-openapi-document" path="/" enableCORS="true">
            <get id="openapi.json" produces="application/json" uri="openapi.json">
                <description>Gets the OpenAPI document for this service</description>
                <route id="route-for-openapi-document">
                    <setHeader id="setHeader-for-openapi-document" headerName="Exchange.CONTENT_TYPE">
                        <constant>application/vnd.oai.openapi+json</constant>
                    </setHeader>
                    <setBody id="setBody-for-openapi-document">
                        <constant>resource:classpath:openapi.json</constant>
                    </setBody>
                </route>
            </get>
        </rest>`

**Comment by EricWittmann** [comment]
I think this should be a bug filed here:  https://github.com/jboss-fuse/fuse-apicurito-generator/issues

Apicurio Studio doesn't currently support generating Fuse/Camel projects.

**Comment by hguerrero** [comment]
Added the issue to github and jira https://github.com/jboss-fuse/fuse-apicurito-generator/issues/57
