### ISSUE TITLE
Question: How to build Docker container

### ISSUE THREAD

**Issue by NPoi** [Apicurio/apicurio-studio#929]
Hello team,

I tried the installation with the method described on this page and it worked.
https://apicurio-studio.readme.io/docs/getting-started-using-docker

Next, I want to edit the source code and build an environment using docker-compose as well. However, I don't know how to make three Docker images: apicurio-studio-ui, apicurio-studio-ws, and apicurio-studio-api.

Will you tell me if there is a procedure document somewhere?

Regards,

Daisuke.

**Comment by EricWittmann** [comment]
Here is a script I use to perform a "snapshot" build of Apicurio, build the docker images, and then push them to docker hub:

https://github.com/Apicurio/apicurio-release/blob/master/staging-studio.sh

However, if you really want to make changes to Apicurio and test them quickly (iterative development) you might want to try this:  https://apicurio-studio.readme.io/docs/setting-up-a-development-environment

**Comment by turutosiya** [comment]
@EricWittmann 

Would you let me kmow what is the defference between `release-studio.sh` and `staging-studio.sh` ?

https://github.com/Apicurio/apicurio-release/blob/master/release-studio.sh

https://github.com/Apicurio/apicurio-release/blob/master/staging-studio.sh

**Comment by EricWittmann** [comment]
Release does a bunch of extra stuff related to actually releasing a new version of Apicurio Studio.  This includes things like:

* Pushing new artifacts into Maven Central
* Pushing a new module to NPM
* Tagging the repository
* Generating release notes
* Tagging a **release** in GitHub

Probably other stuff too, but that's off the top of my head.

The difference from a docker perspective is that different docker tags are generated for release vs. staging.  The staging docker image gets tagged with **latest** and **latest-snapshot**.  When doing a release the docker image gets **latest** but also **latest-release** and some specific version like **2.0.38.Final**.
