### ISSUE TITLE
Define a New Data Type: Can't define enum

### ISSUE THREAD

**Issue by kosmakoff** [Apicurio/apicurio-studio#979]
There is often the need to reuse the enumeration in several places across the schema. It is now only possible to create the enum data type manually, via `Source` tab, and set the `type` to `enum`, instead of `object`.

Please implement the editing of enumerations in UI.

**Comment by EricWittmann** [comment]
Funny you should request this feature right now, as I literally implemented support for re-usable simple types earlier this week.  It's not merged into master yet, but you can see the work here:

https://github.com/Apicurio/apicurio-studio/tree/feature/enhanced-type-editing

I'm working on enhancements to the type editor, including this as well as basic polymorphism support (allOf, anyOf, etc).

**Comment by EricWittmann** [comment]
This was implemented a few weeks ago and I forgot to close the issue.  Marking as closed.
